import * as stylex from "@stylexjs/stylex"

export const styles = stylex.create({
  layout: {
    backgroundColor: "rgb(var(--tbr-color-page))",
    color: "rgb(var(--tbr-color-text))",
    display: "block",
    minHeight: "100vh",
    overflowX: "hidden",
  },
  content: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    minWidth: 0,
    paddingBlockEnd: 66,
    paddingBlockStart: 16,
    paddingInline: 16,
    width: "100%",
  },
  greeting: {
    alignItems: "flex-start",
    display: "flex",
    flexWrap: "wrap",
    fontSize: 13,
    fontWeight: 600,
    gap: 12,
    justifyContent: "space-between",
  },
  greetingTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontWeight: 600,
  },
  muted: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontWeight: 400,
  },
  greetingActions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    justifyContent: "flex-start",
    opacity: 0.74,
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "opacity",
    transitionTimingFunction: "var(--tbr-ease)",
    ":focus-within": {
      opacity: 1,
    },
  },
  toolbarButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 11,
    fontWeight: 500,
    gap: 4,
    height: 28,
    justifyContent: "center",
    paddingInline: 10,
    whiteSpace: "nowrap",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  searchStage: {
    display: "flex",
    justifyContent: "center",
    marginBlockEnd: 4,
    marginBlockStart: 2,
    position: "relative",
    width: "100%",
  },
  searchInner: {
    maxWidth: 720,
    width: "min(100%, 720px)",
  },
  grid: {
    minWidth: 0,
  },
  gridContainer: {
    alignItems: "stretch",
    display: "grid",
    gap: 12,
    gridAutoFlow: "dense",
    gridAutoRows: "auto",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
  },
  emptyGroup: {
    alignItems: "center",
    appearance: "none",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    fontFamily: "inherit",
    fontSize: 14,
    gap: 8,
    gridColumn: "1 / -1",
    paddingBlock: 32,
    paddingInline: 24,
    textAlign: "center",
    ":hover": {
      opacity: 0.85,
    },
  },
  emptyIcon: {
    color: "rgb(var(--tbr-color-text-subtle))",
    marginBottom: 4,
    opacity: 0.5,
  },
  emptyText: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 14,
    fontWeight: 600,
  },
  emptyHint: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 13,
  },
  bar: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderTopColor: "rgb(var(--tbr-color-line))",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    bottom: 0,
    display: "flex",
    flexDirection: "row",
    gap: 6,
    height: 50,
    justifyContent: "space-around",
    left: 0,
    paddingBlock: 6,
    paddingInline: 12,
    position: "fixed",
    right: 0,
    zIndex: "var(--tbr-z-sticky, 100)",
  },
  barGroups: {
    alignItems: "center",
    display: "flex",
    flexDirection: "row",
    gap: 6,
    maxWidth: "100%",
    overflowX: "auto",
  },
  barGroup: {
    position: "relative",
  },
  barButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: 10,
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: 13,
    height: 38,
    justifyContent: "center",
    position: "relative",
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "background-color, border-color, color, box-shadow",
    transitionTimingFunction: "var(--tbr-ease)",
    width: 38,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  barButtonActive: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderColor: "rgb(var(--tbr-color-accent))",
    boxShadow: "inset 0 1px 3px rgb(var(--tbr-color-shadow) / 0.1)",
    color: "rgb(var(--tbr-color-accent))",
  },
  groupIcon: {
    fontSize: 13,
    fontWeight: 650,
    lineHeight: 1,
  },
  barDivider: {
    backgroundColor: "rgb(var(--tbr-color-line))",
    height: 24,
    marginInline: 4,
    width: 1,
  },
  inlinePop: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    bottom: 58,
    boxShadow: "0 8px 24px rgb(var(--tbr-color-shadow) / 0.22)",
    display: "flex",
    gap: 8,
    justifyContent: "center",
    left: 12,
    padding: 10,
    position: "fixed",
    right: 12,
    zIndex: 80,
  },
  inlineInput: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text))",
    flex: 1,
    fontFamily: "inherit",
    fontSize: 12,
    height: 30,
    outline: "none",
    paddingInline: 8,
    ":focus": {
      borderColor: "rgb(var(--tbr-color-accent))",
      boxShadow: "0 0 0 3px rgb(var(--tbr-color-accent) / 0.08)",
    },
  },
  inlineHint: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "inline-flex",
    fontSize: 10,
    fontWeight: 500,
    gap: 4,
    whiteSpace: "nowrap",
  },
  inlineKbd: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: 4,
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    fontFamily: "inherit",
    fontSize: 9,
    paddingBlock: 1,
    paddingInline: 4,
  },
  placeholder: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderColor: "rgb(var(--tbr-color-accent))",
    color: "rgb(var(--tbr-color-accent))",
  },
  pageIndicator: {
    alignItems: "center",
    bottom: 56,
    display: "flex",
    gap: 8,
    justifyContent: "center",
    left: 0,
    paddingBlock: 8,
    position: "fixed",
    right: 0,
    zIndex: "var(--tbr-z-sticky, 100)",
  },
  pageIndicatorDot: {
    backgroundColor: "rgb(var(--tbr-color-text-subtle))",
    borderRadius: "50%",
    height: 6,
    opacity: 0.3,
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "opacity, background-color, transform",
    transitionTimingFunction: "var(--tbr-ease)",
    width: 6,
  },
  pageIndicatorDotActive: {
    backgroundColor: "rgb(var(--tbr-color-accent))",
    opacity: 1,
    transform: "scale(1.2)",
  },
})
