import * as stylex from "@stylexjs/stylex"
import { color, font, motion, radius } from "@tabora/theme/tokens.stylex"

export const styles = stylex.create({
  page: {
    backgroundColor: color.page,
    color: color.text,
    display: "flex",
    flexDirection: "column",
    minHeight: "100dvh",
    overflow: "hidden",
    width: "100%",
  },
  scroll: {
    boxSizing: "border-box",
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: 16,
    minHeight: 0,
    overflowX: "hidden",
    overflowY: "auto",
    paddingBottom: "calc(28px + env(safe-area-inset-bottom))",
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
  },
  search: {
    width: "100%",
  },
  searchControl: {
    backgroundColor: color.surfaceSoft,
    borderColor: color.line,
    borderRadius: radius.control,
    borderStyle: "solid",
    borderWidth: 1,
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  group: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 0,
  },
  groupTitle: {
    color: color.textSubtle,
    fontSize: 11,
    fontWeight: font.bold,
    letterSpacing: "0.05em",
    lineHeight: 1.2,
    margin: 0,
    paddingLeft: 8,
    textTransform: "uppercase",
  },
  groupList: {
    backgroundColor: color.surface,
    borderColor: color.line,
    borderRadius: radius.card,
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  item: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: color.line,
    borderStyle: "solid",
    borderWidth: 0,
    borderBottomWidth: 1,
    color: color.text,
    cursor: "pointer",
    display: "flex",
    gap: 12,
    justifyContent: "space-between",
    minHeight: 56,
    paddingBlock: 12,
    paddingInline: 12,
    textAlign: "left",
    transitionDuration: motion.fast,
    transitionProperty: "background-color",
    transitionTimingFunction: motion.ease,
    width: "100%",
    ":last-child": {
      borderBottomWidth: 0,
    },
    ":active": {
      backgroundColor: color.surfaceSoft,
    },
    "@media (hover: hover)": {
      ":hover": {
        backgroundColor: color.surfaceHover,
      },
    },
  },
  itemLeading: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: 12,
  },
  icon: {
    alignItems: "center",
    borderRadius: radius.control,
    display: "flex",
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  iconOrange: {
    backgroundColor: "color-mix(in srgb, rgb(var(--tbr-color-orange)) 12%, transparent)",
    color: "rgb(var(--tbr-color-orange))",
  },
  iconBlue: {
    backgroundColor: "color-mix(in srgb, rgb(var(--tbr-color-blue)) 12%, transparent)",
    color: "rgb(var(--tbr-color-blue))",
  },
  iconGreen: {
    backgroundColor: "color-mix(in srgb, rgb(var(--tbr-color-green)) 12%, transparent)",
    color: "rgb(var(--tbr-color-green))",
  },
  iconPurple: {
    backgroundColor: "color-mix(in srgb, rgb(var(--tbr-color-purple)) 12%, transparent)",
    color: "rgb(var(--tbr-color-purple))",
  },
  itemContent: {
    display: "grid",
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  itemTitle: {
    fontSize: 14,
    fontWeight: font.semibold,
    lineHeight: 1.3,
    margin: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  itemDescription: {
    color: color.textMuted,
    fontSize: 11,
    lineHeight: 1.35,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  itemTrailing: {
    alignItems: "center",
    color: color.textSubtle,
    display: "flex",
    flexShrink: 0,
    gap: 8,
  },
  itemMeta: {
    fontSize: 11,
    fontWeight: font.semibold,
    whiteSpace: "nowrap",
  },
  empty: {
    color: color.textMuted,
    fontSize: 14,
    margin: 0,
    paddingBlock: 28,
    textAlign: "center",
  },
})
