import * as stylex from "@stylexjs/stylex"

import { color, font, radius, space, zIndex } from "@tabora/theme/tokens.stylex"

export const styles = stylex.create({
  root: {
    backgroundColor: color.page,
    color: color.text,
    display: "grid",
    fontFamily: font.sans,
    gridTemplateColumns: "200px minmax(0, 1fr)",
    height: "100dvh",
    minHeight: "100dvh",
    transitionDuration: "var(--tbr-dur-normal)",
    transitionProperty: "grid-template-columns",
    transitionTimingFunction: "var(--tbr-ease)",
    width: "100%",
    "@media (max-width: 767px)": {
      gridTemplateColumns: "minmax(0, 1fr)",
      paddingBottom: 64,
    },
  },
  rootCollapsed: {
    gridTemplateColumns: "64px 1fr",
    "@media (max-width: 767px)": {
      gridTemplateColumns: "minmax(0, 1fr)",
    },
  },
  sidebar: {
    backgroundColor: color.surface,
    borderRightColor: color.line,
    borderRightStyle: "solid",
    borderRightWidth: 1,
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    "@media (max-width: 767px)": {
      borderRightWidth: 0,
      borderTopColor: color.line,
      borderTopStyle: "solid",
      borderTopWidth: 1,
      bottom: 0,
      height: 64,
      left: 0,
      position: "fixed",
      right: 0,
      width: "100%",
      zIndex: zIndex.sticky,
    },
  },
  brand: {
    alignItems: "center",
    borderBottomColor: color.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    gap: space.s3,
    height: 52,
    paddingInline: space.s5,
    "@media (max-width: 767px)": {
      display: "none",
    },
  },
  brandMark: {
    width: 28,
    height: 28,
    flexShrink: 0,
  },
  brandName: {
    fontSize: 14,
    fontWeight: font.semibold,
  },
  brandCollapsed: {
    justifyContent: "center",
    paddingInline: space.s3,
  },
  nav: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: space.s1,
    minHeight: 0,
    overflowY: "auto",
    paddingBlock: space.s4,
    paddingInline: space.s3,
    "@media (max-width: 767px)": {
      display: "grid",
      flex: "none",
      gap: 0,
      gridTemplateColumns: "repeat(8, minmax(0, 1fr))",
      height: "100%",
      overflow: "hidden",
      paddingBlock: space.s2,
      paddingInline: space.s2,
      width: "100%",
    },
  },
  navItem: {
    alignItems: "center",
    borderRadius: radius.control,
    color: color.textMuted,
    cursor: "pointer",
    display: "flex",
    fontSize: 13,
    gap: space.s3,
    height: 34,
    paddingInline: space.s3,
    textDecoration: "none",
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "background-color, color",
    transitionTimingFunction: "var(--tbr-ease)",
    ":hover": {
      backgroundColor: color.surfaceHover,
      color: color.text,
    },
    "@media (max-width: 767px)": {
      gap: 0,
      height: 48,
      justifyContent: "center",
      paddingInline: 0,
    },
  },
  navItemActive: {
    backgroundColor: color.accentSoft,
    color: color.accent,
    fontWeight: font.semibold,
  },
  navItemCollapsed: {
    gap: 0,
    justifyContent: "center",
    paddingInline: 0,
  },
  navLabel: {
    "@media (max-width: 767px)": {
      display: "none",
    },
  },
  sidebarFooter: {
    alignItems: "center",
    borderTopColor: color.line,
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    gap: space.s3,
    justifyContent: "space-between",
    minHeight: 52,
    paddingBlock: space.s3,
    paddingInline: space.s4,
    "@media (max-width: 767px)": {
      display: "none",
    },
  },
  footerIdentity: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  footerRole: {
    color: color.textSubtle,
    fontSize: 11,
  },
  footerEmail: {
    color: color.text,
    fontSize: 12,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sidebarFooterCollapsed: {
    justifyContent: "center",
    paddingInline: space.s3,
  },
  main: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
  },
  topbar: {
    alignItems: "center",
    backgroundColor: color.surface,
    borderBottomColor: color.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    gap: space.s4,
    height: 52,
    justifyContent: "space-between",
    paddingInline: space.s6,
    "@media (max-width: 767px)": {
      height: 44,
      paddingInline: space.s4,
    },
  },
  topbarTitle: {
    fontSize: 15,
    fontWeight: font.semibold,
  },
  topbarTitleGroup: {
    alignItems: "center",
    display: "flex",
    gap: space.s2,
  },
  topbarActions: {
    alignItems: "center",
    display: "flex",
    gap: space.s3,
  },
  envBadge: {
    color: color.textSubtle,
    fontSize: 12,
    "@media (max-width: 767px)": {
      display: "none",
    },
  },
  content: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: space.s6,
    "@media (max-width: 767px)": {
      padding: space.s5,
    },
  },
})
