import * as stylex from "@stylexjs/stylex"

import { color, font, radius, shadow, zIndex } from "../stylexTokens.stylex"

export const styles = stylex.create({
  overlay: {
    alignItems: "center",
    backdropFilter: "blur(4px)",
    backgroundColor: "rgb(var(--tbr-color-scrim) / 0.18)",
    display: "flex",
    inset: 0,
    justifyContent: "center",
    position: "fixed",
    zIndex: zIndex.modal,
  },
  modal: {
    backgroundColor: color.surface,
    borderColor: color.line,
    borderRadius: radius.panel,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: shadow.floating,
    display: "flex",
    flexDirection: "column",
    height: 520,
    maxHeight: "calc(100vh - 32px)",
    maxWidth: "calc(100vw - 32px)",
    overflow: "hidden",
    width: 740,
    "@media (max-width: 768px)": {
      height: "calc(100vh - 24px)",
      maxHeight: "calc(100vh - 24px)",
      maxWidth: "calc(100vw - 24px)",
    },
  },
  header: {
    alignItems: "center",
    backgroundColor: color.surface,
    borderBottomColor: color.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexShrink: 0,
    justifyContent: "space-between",
    paddingBlock: 10,
    paddingInline: 12,
  },
  headerTitles: { minWidth: 0 },
  title: { color: color.text, fontSize: 15, fontWeight: font.bold, letterSpacing: 0 },
  kicker: { color: color.textMuted, fontSize: 11, marginTop: 2 },
  headerContext: { alignItems: "center", display: "flex", gap: 6 },
  pill: {
    alignItems: "center",
    backgroundColor: color.surfaceSoft,
    borderColor: color.line,
    borderRadius: radius.pill,
    borderStyle: "solid",
    borderWidth: 1,
    color: color.textMuted,
    display: "inline-flex",
    fontSize: 11,
    height: 24,
    paddingInline: 8,
    whiteSpace: "nowrap",
    "@media (max-width: 480px)": { display: "none" },
  },
  iconButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: radius.control,
    color: color.textMuted,
    cursor: "pointer",
    display: "flex",
    height: 28,
    justifyContent: "center",
    width: 28,
    ":hover": { backgroundColor: color.surfaceHover, color: color.text },
    ":focus-visible": {
      outlineColor: color.focus,
      outlineOffset: 2,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  body: {
    display: "grid",
    flex: 1,
    gridTemplateColumns: "minmax(282px, 0.46fr) minmax(344px, 0.54fr)",
    minHeight: 0,
    overflow: "hidden",
    "@media (max-width: 768px)": {
      gridTemplateColumns: "minmax(0, 1fr)",
    },
  },
  left: {
    backgroundColor: color.surface,
    borderRightColor: color.line,
    borderRightStyle: "solid",
    borderRightWidth: 1,
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    "@media (max-width: 768px)": { borderRightWidth: 0 },
  },
  searchArea: {
    borderBottomColor: color.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    paddingBlock: 8,
    paddingInline: 10,
  },
  searchWrap: { position: "relative" },
  searchIcon: {
    color: color.textSubtle,
    left: 12,
    pointerEvents: "none",
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
  },
  searchInput: {
    backgroundColor: color.surfaceSoft,
    borderColor: color.line,
    borderRadius: radius.control,
    borderStyle: "solid",
    borderWidth: 1,
    color: color.text,
    fontFamily: font.sans,
    fontSize: 13,
    height: 36,
    outline: "none",
    paddingLeft: 34,
    paddingRight: 12,
    width: "100%",
    ":focus": {
      borderColor: color.accent,
      boxShadow: "0 0 0 3px rgb(var(--tbr-color-accent) / 0.12)",
    },
    "::placeholder": { color: color.textSubtle },
  },
  tabs: {
    borderBottomColor: color.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexShrink: 0,
    gap: 3,
    overflowX: "auto",
    paddingBlock: 6,
    paddingInline: 10,
  },
  tab: {
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: radius.pill,
    borderStyle: "solid",
    borderWidth: 1,
    color: color.textMuted,
    cursor: "pointer",
    fontFamily: font.sans,
    fontSize: 11,
    fontWeight: font.medium,
    height: 28,
    paddingInline: 8,
    whiteSpace: "nowrap",
    ":hover": { backgroundColor: color.surfaceHover, color: color.text },
    ":focus-visible": {
      outlineColor: color.focus,
      outlineOffset: 2,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  selected: {
    backgroundColor: color.accentSoft,
    borderColor: color.accent,
    color: color.accent,
    fontWeight: font.semibold,
  },
  list: { flex: 1, overflowY: "auto", paddingBottom: 8, paddingInline: 6, paddingTop: 4 },
  empty: { color: color.textSubtle, fontSize: 13, paddingBlock: 26, textAlign: "center" },
  item: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: radius.control,
    borderStyle: "solid",
    borderWidth: 1,
    color: color.text,
    cursor: "pointer",
    display: "grid",
    fontFamily: font.sans,
    gap: 7,
    gridTemplateColumns: "24px minmax(0, 1fr) auto",
    marginBottom: 1,
    minHeight: 46,
    paddingBlock: 6,
    paddingInline: 7,
    textAlign: "left",
    width: "100%",
    ":hover": { backgroundColor: color.surfaceHover, borderColor: color.lineStrong },
    ":focus-visible": {
      outlineColor: color.focus,
      outlineOffset: -2,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  itemIcon: {
    alignItems: "center",
    backgroundColor: color.surfaceSoft,
    borderColor: color.line,
    borderRadius: radius.r2,
    borderStyle: "solid",
    borderWidth: 1,
    color: color.textMuted,
    display: "flex",
    fontSize: 10,
    fontWeight: font.bold,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  itemInfo: { display: "flex", flexDirection: "column", minWidth: 0 },
  itemName: {
    fontSize: 12,
    fontWeight: font.semibold,
    lineHeight: 1.25,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  itemDescription: {
    color: color.textMuted,
    fontSize: 11,
    lineHeight: 1.28,
    marginTop: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  itemMeta: {
    alignItems: "flex-end",
    display: "flex",
    flexDirection: "column",
    gap: 3,
    minWidth: 38,
  },
  source: {
    alignItems: "center",
    backgroundColor: color.surface,
    borderColor: color.line,
    borderRadius: radius.r1,
    borderStyle: "solid",
    borderWidth: 1,
    color: color.textSubtle,
    display: "inline-flex",
    fontSize: 10,
    lineHeight: 1,
    paddingBlock: 2,
    paddingInline: 5,
  },
  sizeHint: { color: color.textSubtle, fontSize: 10, fontVariantNumeric: "tabular-nums" },
  right: {
    backgroundColor: color.surfaceSoft,
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    overflowY: "auto",
    padding: 12,
    "@media (max-width: 768px)": { display: "none" },
  },
  previewEmpty: {
    alignItems: "center",
    color: color.textSubtle,
    display: "flex",
    flex: 1,
    fontSize: 13,
    justifyContent: "center",
  },
  previewHead: {
    alignItems: "flex-start",
    display: "flex",
    gap: 10,
    justifyContent: "space-between",
    marginBottom: 8,
  },
  previewLabel: {
    color: color.textSubtle,
    fontSize: 11,
    fontWeight: font.bold,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
  },
  previewTitle: { color: color.text, fontSize: 17, fontWeight: font.bold, marginTop: 4 },
  previewStatus: {
    backgroundColor: color.surface,
    borderColor: color.line,
    borderRadius: radius.pill,
    borderStyle: "solid",
    borderWidth: 1,
    color: color.textMuted,
    fontSize: 11,
    paddingBlock: 4,
    paddingInline: 7,
    whiteSpace: "nowrap",
  },
  previewArea: {
    backgroundColor: color.surface,
    borderColor: color.line,
    borderRadius: radius.card,
    borderStyle: "solid",
    borderWidth: 1,
    marginBottom: 8,
    minHeight: 198,
    overflow: "hidden",
    padding: 9,
  },
  workspacePreview: { display: "grid", gap: 8, gridTemplateRows: "auto 1fr", minHeight: 178 },
  workspaceBar: {
    alignItems: "center",
    color: color.textSubtle,
    display: "flex",
    fontSize: 10,
    justifyContent: "space-between",
  },
  workspaceGroup: {
    alignItems: "center",
    color: color.textMuted,
    display: "inline-flex",
    fontWeight: font.semibold,
    gap: 6,
  },
  dot: { backgroundColor: color.accent, borderRadius: radius.pill, height: 6, width: 6 },
  workspaceGrid: {
    backgroundColor: color.surfaceSoft,
    borderColor: color.line,
    borderRadius: radius.panel,
    borderStyle: "solid",
    borderWidth: 1,
    minHeight: 154,
    padding: 9,
  },
  previewWidget: {
    backgroundColor: color.surface,
    borderColor: color.lineStrong,
    borderRadius: radius.card,
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 7,
    minHeight: 117,
    padding: 10,
    width: 187,
  },
  previewS: { minHeight: 97, width: 146 },
  previewL: { minHeight: 128, width: 228 },
  previewXL: { minHeight: 115, width: "min(100%, 268px)" },
  previewWidgetHead: {
    alignItems: "center",
    display: "flex",
    gap: 8,
    justifyContent: "space-between",
  },
  previewWidgetTitle: {
    color: color.text,
    fontSize: 12,
    fontWeight: font.bold,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  badge: {
    alignItems: "center",
    backgroundColor: color.accentSoft,
    borderRadius: radius.pill,
    color: color.accent,
    display: "inline-flex",
    flexShrink: 0,
    fontSize: 10,
    fontWeight: font.semibold,
    height: 18,
    paddingInline: 6,
  },
  thirdParty: { backgroundColor: color.surfaceHover, color: color.warning },
  previewWidgetBody: { color: color.textMuted, fontSize: 11, lineHeight: 1.45 },
  detailRow: {
    display: "grid",
    gap: 8,
    gridTemplateColumns: "minmax(0, 1fr) minmax(142px, 0.72fr)",
  },
  box: {
    backgroundColor: color.surface,
    borderColor: color.line,
    borderRadius: radius.panel,
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 9,
  },
  sizeLabel: { display: "flex", flexDirection: "column" },
  boxTitle: { color: color.text, fontSize: 12, fontWeight: font.semibold },
  boxDescription: { color: color.textSubtle, fontSize: 10, lineHeight: 1.35 },
  sizeOptions: {
    backgroundColor: color.page,
    borderColor: color.line,
    borderRadius: radius.control,
    borderStyle: "solid",
    borderWidth: 1,
    display: "inline-flex",
    gap: 2,
    padding: 3,
    width: "fit-content",
  },
  sizeButton: {
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: radius.control,
    borderStyle: "solid",
    borderWidth: 1,
    color: color.textMuted,
    cursor: "pointer",
    fontFamily: font.sans,
    fontSize: 12,
    fontWeight: font.semibold,
    height: 28,
    minWidth: 36,
    paddingInline: 10,
    ":hover": { backgroundColor: color.surfaceHover, borderColor: color.lineStrong },
    ":disabled": { cursor: "not-allowed", opacity: 0.4 },
  },
  metaCard: { height: "100%" },
  metaRow: {
    color: color.textMuted,
    display: "flex",
    fontSize: 11,
    gap: 12,
    justifyContent: "space-between",
  },
  metaValue: { color: color.text, fontWeight: font.semibold, textAlign: "right" },
  footer: {
    alignItems: "center",
    backgroundColor: color.surface,
    borderTopColor: color.line,
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    flexShrink: 0,
    gap: 12,
    justifyContent: "space-between",
    paddingBlock: 8,
    paddingInline: 12,
  },
  footerLeft: {
    alignItems: "center",
    display: "flex",
    gap: 8,
    minWidth: 0,
    "@media (max-width: 480px)": { display: "none" },
  },
  marketplace: { color: color.textMuted, fontSize: 12, textDecoration: "none" },
  divider: { backgroundColor: color.line, height: 14, width: 1 },
  footerHint: { color: color.textSubtle, fontSize: 11, whiteSpace: "nowrap" },
  footerActions: { alignItems: "center", display: "flex", flexShrink: 0, gap: 6 },
  button: {
    alignItems: "center",
    backgroundColor: color.surface,
    borderColor: color.line,
    borderRadius: radius.control,
    borderStyle: "solid",
    borderWidth: 1,
    color: color.text,
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: font.sans,
    fontSize: 13,
    fontWeight: font.semibold,
    height: 32,
    paddingInline: 12,
    ":hover": { backgroundColor: color.surfaceHover, borderColor: color.lineStrong },
    ":disabled": { cursor: "not-allowed", opacity: 0.5 },
  },
  buttonSubtle: {
    backgroundColor: "transparent",
    borderColor: "transparent",
    color: color.textMuted,
  },
  buttonPrimary: { backgroundColor: color.accent, borderColor: color.accent, color: color.inverse },
})
