import * as stylex from "@stylexjs/stylex"

import { color, font, radius, space } from "@tabora/theme/tokens.stylex"

export const styles = stylex.create({
  root: {
    backgroundColor: color.page,
    color: color.text,
    display: "grid",
    fontFamily: font.sans,
    gridTemplateColumns: "232px 1fr",
    height: "100vh",
    transitionDuration: "var(--tbr-dur-normal)",
    transitionProperty: "grid-template-columns",
    transitionTimingFunction: "var(--tbr-ease)",
    width: "100%",
  },
  rootCollapsed: {
    gridTemplateColumns: "64px 1fr",
  },
  sidebar: {
    backgroundColor: color.surface,
    borderRightColor: color.line,
    borderRightStyle: "solid",
    borderRightWidth: 1,
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
  },
  brand: {
    alignItems: "center",
    borderBottomColor: color.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    gap: space.s3,
    height: 56,
    paddingInline: space.s5,
  },
  brandMark: {
    alignItems: "center",
    backgroundColor: color.accent,
    borderRadius: radius.control,
    color: color.inverse,
    display: "flex",
    height: 26,
    justifyContent: "center",
    width: 26,
  },
  brandName: {
    fontSize: 14,
    fontWeight: font.semibold,
  },
  brandCollapsed: {
    justifyContent: "center",
    paddingInline: space.s3,
  },
  nav: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: space.s1,
    minHeight: 0,
    overflowY: "auto",
    paddingBlock: space.s4,
    paddingInline: space.s3,
  },
  navItem: {
    alignItems: "center",
    borderRadius: radius.control,
    color: color.textMuted,
    cursor: "pointer",
    display: "flex",
    fontSize: 13,
    gap: space.s3,
    height: 36,
    paddingInline: space.s3,
    textDecoration: "none",
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "background-color, color",
    transitionTimingFunction: "var(--tbr-ease)",
    ":hover": {
      backgroundColor: color.surfaceHover,
      color: color.text,
    },
  },
  navItemActive: {
    backgroundColor: color.accentSoft,
    color: color.accent,
    fontWeight: font.semibold,
  },
  navItemCollapsed: {
    gap: 0,
    justifyContent: "center",
    paddingInline: 0,
  },
  sidebarFooter: {
    alignItems: "center",
    borderTopColor: color.line,
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    gap: space.s3,
    justifyContent: "space-between",
    minHeight: 52,
    paddingBlock: space.s3,
    paddingInline: space.s4,
  },
  footerIdentity: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  footerRole: {
    color: color.textSubtle,
    fontSize: 11,
  },
  footerEmail: {
    color: color.text,
    fontSize: 12,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sidebarFooterCollapsed: {
    justifyContent: "center",
    paddingInline: space.s3,
  },
  main: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
  },
  topbar: {
    alignItems: "center",
    backgroundColor: color.surface,
    borderBottomColor: color.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    gap: space.s4,
    height: 56,
    justifyContent: "space-between",
    paddingInline: space.s8,
  },
  topbarTitle: {
    fontSize: 15,
    fontWeight: font.semibold,
  },
  topbarTitleGroup: {
    alignItems: "center",
    display: "flex",
    gap: space.s2,
  },
  topbarActions: {
    alignItems: "center",
    display: "flex",
    gap: space.s3,
  },
  envBadge: {
    color: color.textSubtle,
    fontSize: 12,
  },
  content: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: space.s8,
  },
})
