import * as stylex from "@stylexjs/stylex"

export const cardStyles = stylex.create({
  brandCard: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderRadius: "inherit",
    color: "rgb(var(--tbr-color-text))",
    display: "flex",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    padding: 0,
    width: "100%",
  },
  brandCardSmall: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderRadius: "inherit",
    color: "rgb(var(--tbr-color-text))",
    containerType: "inline-size",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    justifyContent: "space-between",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    padding: "clamp(6px, 6cqw, 12px)",
    width: "100%",
  },
  brandVisual: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderRightColor: "rgb(var(--tbr-color-line))",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    color: "rgb(var(--tbr-color-accent))",
    display: "flex",
    flex: "0 0 35%",
    height: "100%",
    justifyContent: "center",
    minHeight: 0,
    minWidth: 0,
  },
  brandContent: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    gap: 6,
    justifyContent: "flex-end",
    minWidth: 0,
    padding: 14,
  },
  brandVisualSmall: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-accent))",
    display: "flex",
    height: "clamp(34px, 30cqw, 56px)",
    justifyContent: "center",
    width: "clamp(34px, 30cqw, 56px)",
  },
  brandContentSmall: {
    display: "flex",
    flexDirection: "column",
    gap: "clamp(2px, 3cqw, 5px)",
    minWidth: 0,
  },
  brandTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 16,
    fontWeight: 650,
    letterSpacing: "-0.01em",
    whiteSpace: "nowrap",
  },
  brandRule: {
    backgroundColor: "rgb(var(--tbr-color-accent))",
    height: 2,
    marginTop: 1,
    width: 24,
  },
  brandRuleSmall: {
    backgroundColor: "rgb(var(--tbr-color-accent))",
    height: 2,
    marginTop: 1,
    width: "clamp(16px, 20cqw, 24px)",
  },
  brandMeta: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontFamily: "var(--tbr-font-mono)",
    fontSize: 10,
    fontWeight: 500,
    letterSpacing: "0.06em",
    lineHeight: 1.3,
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  brandMetaSmall: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontFamily: "var(--tbr-font-mono)",
    fontSize: "clamp(7px, 6cqw, 10px)",
    fontWeight: 500,
    letterSpacing: "0.03em",
    lineHeight: 1.3,
    overflow: "hidden",
    textOverflow: "ellipsis",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  brandTitleSmall: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: "clamp(12px, 9cqw, 15px)",
    fontWeight: 650,
    letterSpacing: "-0.01em",
    whiteSpace: "nowrap",
  },
})
