packages:
  - apps/*
  - packages/*
  - plugins/*
  - plugins/*/*
  - tooling/*
  - backend/app

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vitest: 4.1.10

allowBuilds:
  "@prisma/client": false
  "@swc/core": false
  argon2: true
  better-sqlite3: true
  braintrust: true
  core-js-pure: false
  esbuild: true
  isolated-vm: true
  oracledb: true
  protobufjs: true
  sharp: true
  spawn-sync: true
  sqlite3: true
  vue-demi: true

catalogs:
  node:
    "@types/node": ^26.2.0
  build:
    "@stylexjs/unplugin": ^0.19.0
    tsdown: ^0.22.14
    typescript: ^7.0.2
    vite: ^8.2.1
    vite-plugin-solid: ^2.11.14
    vite-plus: ^0.2.8
  style:
    "@stylexjs/stylex": ^0.19.0
  data:
    dexie: ^4.4.4
    zod: ^4.4.3
  ai:
    "@tanstack/ai": ^0.51.0
    "@tanstack/ai-client": ^0.29.1
    "@tanstack/ai-openai": ^0.22.2
  test:
    "@vitest/browser-playwright": ^4.1.10
    fake-indexeddb: ^6.2.5
    happy-dom: ^20.11.2
    playwright: ^1.62.1
    vitest: ^4.1.10
  ui:
    "@kobalte/core": ^0.13.12
    "@solid-primitives/event-bus": ^1.1.4
    "@solid-primitives/media": ^2.3.6
    "@solid-primitives/timer": ^1.4.4
    "@solidjs/router": ^1.0.0
    "@tanstack/charts": ^0.8.0
    "@tanstack/charts-scales": ^0.8.0
    "@tanstack/solid-charts": ^0.8.0
    "@tanstack/solid-query": ^5.101.4
    "@tiptap/core": 3.30.2
    "@tiptap/extension-audio": 3.30.2
    "@tiptap/extension-file-handler": 3.30.2
    "@tiptap/extension-image": 3.30.2
    "@tiptap/extension-link": 3.30.2
    "@tiptap/extension-placeholder": 3.30.2
    "@tiptap/extension-task-item": 3.30.2
    "@tiptap/extension-task-list": 3.30.2
    "@tiptap/extension-text-align": 3.30.2
    "@tiptap/extension-underline": 3.30.2
    "@tiptap/pm": 3.30.2
    "@tiptap/starter-kit": 3.30.2
    lucide-solid: ^1.31.0
    solid-js: ^1.9.14
  toolkit:
    es-toolkit: ^1.50.0

minimumReleaseAgeExclude:
  - vite-plugin-solid@2.11.14
  - fastify@5.11.2
  - "@tanstack/charts-scales@0.8.0"
  - "@tanstack/charts@0.8.0"
  - "@tanstack/router-core@1.171.20"
  - "@tanstack/router-generator@1.167.26"
  - "@tanstack/router-plugin@1.168.28"
  - "@tanstack/solid-charts@0.8.0"
  - "@tanstack/solid-router@1.170.23"
  - "@tanstack/solid-start-client@1.168.22"
  - "@tanstack/solid-start-server@1.167.29"
  - "@tanstack/solid-start@1.168.40"
  - "@tanstack/start-client-core@1.170.20"
  - "@tanstack/start-plugin-core@1.171.32"
  - "@tanstack/start-server-core@1.169.24"
  - "@tanstack/start-storage-context@1.167.22"
  - lucide-solid@1.31.0
  - pg-protocol@1.16.0
  - pg@8.23.0
  - "@tanstack/ai-event-client@0.11.1"
  - "@tanstack/ai-openai@0.22.2"
  - "@tanstack/ai@0.51.0"
  - "@tanstack/openai-base@0.10.7"
  - "@tanstack/ai-client@0.29.1"
