import * as stylex from "@stylexjs/stylex"
import { color, font, radius, space } from "@tabora/theme/tokens.stylex"

export const styles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    minWidth: 0,
  },
  accountRoot: {
    alignContent: "center",
    display: "grid",
    gap: 10,
    marginInline: "auto",
    minHeight: 248,
    width: "min(100%, 322px)",
  },
  stack: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
    minWidth: 0,
  },
  accountGroup: {
    backgroundColor: "transparent",
    borderRadius: 0,
    borderStyle: "none",
    borderWidth: 0,
    gap: 10,
    padding: 0,
  },
  accountActions: {
    display: "grid",
    gap: 7,
  },
  accountActionsInline: {
    alignItems: "center",
    display: "grid",
    gap: 8,
    gridTemplateColumns: "minmax(0, 1fr) auto",
  },
  accountActionNote: {
    color: color.textSubtle,
    fontSize: 10,
    lineHeight: 1.35,
    margin: 0,
  },
  accountStatus: {
    backgroundColor: color.surfaceSoft,
    borderColor: color.line,
    borderRadius: radius.control,
    borderStyle: "solid",
    borderWidth: 1,
    minHeight: 42,
  },
  accountStatusValue: {
    color: color.text,
    fontSize: 11,
    fontWeight: font.semibold,
    overflowWrap: "anywhere",
  },
  groupTitleRow: {
    alignItems: "center",
    color: color.text,
    display: "flex",
    fontSize: 11,
    fontWeight: font.bold,
    gap: 8,
    justifyContent: "space-between",
    lineHeight: 1.25,
    minHeight: 22,
    minWidth: 0,
    paddingInline: 2,
  },
  groupMeta: {
    color: color.textSubtle,
    flexShrink: 0,
    fontSize: 10,
    fontWeight: font.semibold,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  group: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    display: "grid",
    gap: 8,
    padding: 0,
  },
  groupHeading: {
    display: "grid",
    gap: space.s1,
  },
  groupTitle: {
    color: color.text,
    fontSize: 11,
    fontWeight: font.bold,
    lineHeight: 1.25,
  },
  groupDescription: {
    color: color.textSubtle,
    fontSize: 11,
    lineHeight: 1.4,
    margin: 0,
  },
  text: {
    color: color.text,
    fontSize: 12,
    lineHeight: 1.45,
    margin: 0,
  },
  textMuted: {
    color: color.textMuted,
  },
  textDanger: {
    color: color.danger,
  },
  field: {
    display: "grid",
    gap: space.s1,
  },
  fieldLabel: {
    color: color.text,
    fontSize: 12,
    fontWeight: font.semibold,
  },
  fieldDescription: {
    color: color.textSubtle,
    fontSize: 11,
    lineHeight: 1.4,
    margin: 0,
  },
  status: {
    alignItems: "center",
    backgroundColor: color.surfaceSoft,
    borderColor: color.line,
    borderRadius: radius.control,
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    gap: space.s2,
    justifyContent: "space-between",
    minHeight: 34,
    paddingBlock: space.s2,
    paddingInline: space.s3,
  },
  statusLabel: {
    color: color.textMuted,
    fontSize: 11,
  },
  statusValue: {
    color: color.text,
    fontSize: 11,
    lineHeight: 1.4,
    overflowWrap: "anywhere",
    textAlign: "right",
  },
  statusSuccess: {
    color: color.success,
  },
  statusWarning: {
    color: color.warning,
  },
  statusDanger: {
    color: color.danger,
  },
  statusAccent: {
    color: color.accent,
  },
  rowMeta: {
    color: color.textMuted,
    fontSize: 11,
    fontWeight: font.semibold,
    whiteSpace: "nowrap",
  },
  actions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: space.s2,
  },
  loading: {
    display: "grid",
    gap: space.s2,
    paddingBlock: space.s2,
  },
})
