import * as stylex from "@stylexjs/stylex"

export const styles = stylex.create({
  // S variant (semantic card)
  small: {
    width: "100%",
    height: "100%",
    minWidth: 0,
    minHeight: 0,
    padding: "clamp(7px, 8cqw, 11px)",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr) auto",
    gap: "clamp(4px, 5cqw, 7px)",
    cursor: "pointer",
    containerType: "inline-size",
  },
  smallHead: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 4,
  },
  smallDate: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontFamily: "ui-monospace, 'SFMono-Regular', 'SF Mono', Menlo, monospace",
    fontSize: "clamp(4px, 5cqw, 7px)",
  },
  smallState: {
    color: "rgb(var(--tbr-color-accent))",
    fontSize: "clamp(4px, 5cqw, 7px)",
    fontWeight: 700,
  },
  smallCopy: {
    display: "-webkit-box",
    overflow: "hidden",
    alignSelf: "center",
    fontSize: "clamp(7px, 9cqw, 11px)",
    fontWeight: 520,
    lineHeight: 1.45,
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 4,
  },
  smallCopyEmpty: {
    color: "rgb(var(--tbr-color-text-subtle))",
  },
  smallFoot: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 4,
    paddingTop: "clamp(3px, 4cqw, 5px)",
    borderTop: "1px solid rgb(var(--tbr-color-line))",
  },
  smallTag: {
    overflow: "hidden",
    color: "rgb(var(--tbr-color-accent))",
    fontSize: "clamp(4px, 5cqw, 7px)",
    fontWeight: 700,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  smallReplies: {
    flex: "0 0 auto",
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: "clamp(4px, 5cqw, 6px)",
  },

  // M variant
  medium: {
    width: "100%",
    height: "100%",
    minWidth: 0,
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr) auto",
    gap: 6,
    padding: 8,
    border: "1px solid rgb(var(--tbr-color-line))",
    borderRadius: 9,
    background:
      "radial-gradient(circle at 100% 0, color-mix(in srgb, rgb(var(--tbr-color-accent)) 11%, transparent), transparent 38%), rgb(var(--tbr-color-surface))",
    overflow: "hidden",
  },
  mediumHead: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 7,
  },
  mediumFoot: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 7,
  },

  // L variant
  large: {
    width: "100%",
    height: "100%",
    minWidth: 0,
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "auto auto minmax(0, 1fr) auto",
    gap: 7,
    padding: 9,
    border: "1px solid rgb(var(--tbr-color-line))",
    borderRadius: 9,
    background:
      "radial-gradient(circle at 100% 0, color-mix(in srgb, rgb(var(--tbr-color-accent)) 11%, transparent), transparent 38%), rgb(var(--tbr-color-surface))",
    overflow: "hidden",
  },
  largeHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 7,
  },
  largeFoot: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 7,
  },

  // XL variant
  xlarge: {
    width: "100%",
    height: "100%",
    minWidth: 0,
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "auto auto minmax(0, 1fr) auto",
    gap: 7,
    padding: 10,
    border: "1px solid rgb(var(--tbr-color-line))",
    borderRadius: 9,
    background:
      "radial-gradient(circle at 100% 0, color-mix(in srgb, rgb(var(--tbr-color-accent)) 11%, transparent), transparent 38%), rgb(var(--tbr-color-surface))",
    overflow: "hidden",
  },
  xlargeHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 7,
  },
  xlargeFoot: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 7,
  },

  // Shared elements
  kicker: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 7,
    fontWeight: 750,
    letterSpacing: "0.11em",
    textTransform: "uppercase",
  },
  addButton: {
    display: "grid",
    placeItems: "center",
    width: 25,
    height: 25,
    flex: "0 0 auto",
    border:
      "1px solid color-mix(in srgb, rgb(var(--tbr-color-accent)) 30%, rgb(var(--tbr-color-line)))",
    borderRadius: 7,
    background:
      "color-mix(in srgb, rgb(var(--tbr-color-accent)) 8%, rgb(var(--tbr-color-surface)))",
    color: "rgb(var(--tbr-color-accent))",
    font: "700 14px/1 inherit",
    cursor: "pointer",
    ":hover": {
      background: "rgb(var(--tbr-color-accent))",
      color: "rgb(var(--tbr-color-accent-text))",
    },
  },
  latest: {
    minHeight: 0,
    display: "grid",
    alignContent: "start",
    color: "rgb(var(--tbr-color-text))",
    fontSize: 11,
    fontWeight: 540,
    lineHeight: 1.52,
    whiteSpace: "pre-wrap",
    overflow: "hidden",
    cursor: "pointer",
  },
  latestEmpty: {
    color: "rgb(var(--tbr-color-text-subtle))",
  },
  widgetTime: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 7,
  },
  widgetCount: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 7,
  },
  widgetTag: {
    overflow: "hidden",
    color: "rgb(var(--tbr-color-accent))",
    fontSize: 7,
    fontWeight: 700,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  capture: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 7,
    padding: "7px 8px",
    border:
      "1px solid color-mix(in srgb, rgb(var(--tbr-color-accent)) 24%, rgb(var(--tbr-color-line)))",
    borderRadius: 7,
    background:
      "color-mix(in srgb, rgb(var(--tbr-color-accent)) 5%, rgb(var(--tbr-color-surface-soft)))",
    color: "rgb(var(--tbr-color-text-muted))",
    fontFamily: "inherit",
    fontSize: 8,
    textAlign: "left",
    cursor: "text",
  },
  captureText: {
    color: "rgb(var(--tbr-color-text-muted))",
  },
  captureMark: {
    color: "rgb(var(--tbr-color-accent))",
    fontSize: 13,
    lineHeight: 1,
  },
  previewList: {
    minHeight: 0,
    display: "grid",
    alignContent: "start",
    gap: 5,
    overflow: "hidden",
  },
  previewListXL: {
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    alignContent: "start",
    gap: 6,
    overflow: "hidden",
  },
  preview: {
    minWidth: 0,
    display: "grid",
    gap: 3,
    padding: "6px 7px",
    border: "1px solid rgb(var(--tbr-color-line))",
    borderRadius: 7,
    background: "rgb(var(--tbr-color-surface-soft))",
    cursor: "pointer",
  },
  previewFirst: {
    gridColumn: "1 / -1",
  },
  previewHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 7,
  },
  previewTime: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 7,
  },
  previewContent: {
    overflow: "hidden",
    color: "rgb(var(--tbr-color-text))",
    fontSize: 8,
    lineHeight: 1.4,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  viewAll: {
    padding: 0,
    borderStyle: "none",
    borderWidth: 0,
    background: "transparent",
    color: "rgb(var(--tbr-color-text-muted))",
    font: "650 8px/1 inherit",
    cursor: "pointer",
    ":hover": {
      color: "rgb(var(--tbr-color-accent))",
    },
  },

  // Expand view styles (preserved from original)
  cardFooter: {
    paddingBlockStart: 8,
    paddingInline: 2,
  },
  expandRoot: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    display: "flex",
    flex: 1,
    flexDirection: {
      default: "row",
      "@media (max-width: 720px)": "column",
    },
    minHeight: 0,
  },
  side: {
    backgroundColor: "rgb(var(--tbr-color-page))",
    borderBottomColor: {
      default: "transparent",
      "@media (max-width: 720px)": "rgb(var(--tbr-color-line))",
    },
    borderBottomStyle: "solid",
    borderBottomWidth: {
      default: 0,
      "@media (max-width: 720px)": 1,
    },
    borderRightColor: "rgb(var(--tbr-color-line))",
    borderRightStyle: "solid",
    borderRightWidth: {
      default: 1,
      "@media (max-width: 720px)": 0,
    },
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    maxHeight: {
      default: "none",
      "@media (max-width: 720px)": 260,
    },
    overflowY: "auto",
    width: {
      default: 192,
      "@media (max-width: 720px)": "100%",
    },
  },
  sideSearch: {
    paddingBlock: 8,
    paddingInline: 12,
  },
  sideCalendar: {
    paddingBlockEnd: 8,
    paddingInline: 12,
  },
  sideSection: {
    paddingInline: 12,
  },
  sideSectionTitle: {
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "block",
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: 0,
    paddingBlockEnd: 2,
    paddingBlockStart: 6,
    textTransform: "uppercase",
  },
  sideList: {
    paddingBlock: 2,
    paddingInline: 12,
  },
  sideTags: {
    paddingBlockEnd: 8,
    paddingInline: 12,
  },
  sideButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: 12,
    gap: 6,
    minHeight: 28,
    paddingBlock: 3,
    paddingInline: 8,
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "background-color, color",
    transitionTimingFunction: "var(--tbr-ease)",
    width: "100%",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 1,
    },
  },
  sideButtonActive: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    color: "rgb(var(--tbr-color-accent))",
  },
  sideCount: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 10,
    marginLeft: "auto",
  },
  sideCountActive: {
    color: "rgb(var(--tbr-color-accent))",
  },
  sideHash: {
    color: "rgb(var(--tbr-color-text-subtle))",
    flexShrink: 0,
    fontWeight: 500,
  },
  sideHashActive: {
    color: "rgb(var(--tbr-color-accent))",
  },
  sideEmpty: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 11,
    paddingBlock: 3,
    paddingInline: 8,
  },
  main: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minWidth: 0,
    overflowY: "auto",
    paddingBlock: 12,
    paddingInline: 16,
  },
  captureExpand: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    flexShrink: 0,
    marginBottom: 10,
    overflow: "hidden",
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "border-color, box-shadow",
    transitionTimingFunction: "var(--tbr-ease)",
    ":focus-within": {
      borderColor: "rgb(var(--tbr-color-accent))",
      boxShadow: "0 0 0 3px rgb(var(--tbr-color-accent) / 0.08)",
    },
  },
  captureInner: {
    alignItems: "flex-start",
    display: "flex",
    gap: 8,
    paddingBlockEnd: 4,
    paddingBlockStart: 8,
    paddingInline: 12,
  },
  textarea: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "rgb(var(--tbr-color-text))",
    flex: 1,
    fontFamily: "inherit",
    fontSize: 14,
    lineHeight: 1.45,
    minHeight: 36,
    outline: "none",
    paddingBlock: 2,
    resize: "vertical",
    width: "100%",
    "::placeholder": {
      color: "rgb(var(--tbr-color-text-subtle))",
    },
  },
  editTextarea: {
    minHeight: 100,
  },
  captureFooter: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    paddingBlockEnd: 8,
    paddingBlockStart: 4,
    paddingInline: 12,
  },
  savePill: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "inline-flex",
    fontSize: 12,
    fontWeight: 600,
    gap: 4,
    height: 28,
    paddingInline: 12,
  },
  noteList: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
  },
  note: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    marginBottom: 8,
    overflow: "hidden",
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "border-color",
    transitionTimingFunction: "var(--tbr-ease)",
    ":hover": {
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
  },
  noteEditing: {
    borderColor: "rgb(var(--tbr-color-accent))",
    boxShadow: "0 0 0 3px rgb(var(--tbr-color-accent) / 0.08)",
  },
  noteDisplay: {
    cursor: "pointer",
    paddingBlockEnd: 8,
    paddingBlockStart: 12,
    paddingInline: 16,
  },
  noteTime: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "flex",
    fontSize: 12,
    gap: 6,
    lineHeight: 1.35,
    marginBottom: 4,
  },
  star: {
    color: "rgb(var(--tbr-color-accent))",
    display: "inline-flex",
  },
  noteContent: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 14,
    lineHeight: 1.45,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  highlight: {
    backgroundColor: "rgb(var(--tbr-color-accent) / 0.15)",
    borderRadius: 2,
    paddingInline: 1,
  },
  tags: {
    display: "flex",
    flexWrap: "wrap",
    gap: 4,
    marginTop: 4,
  },
  tag: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderRadius: "var(--tbr-radius-pill)",
    color: "rgb(var(--tbr-color-accent))",
    fontSize: 11,
    paddingBlock: 1,
    paddingInline: 8,
  },
  noteFooter: {
    alignItems: "center",
    display: "flex",
    marginTop: 4,
  },
  meta: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 12,
  },
  actions: {
    display: "flex",
    gap: 2,
    marginLeft: "auto",
  },
  edit: {
    display: "flex",
    flexDirection: "column",
  },
  editArea: {
    paddingBlockEnd: 8,
    paddingBlockStart: 12,
    paddingInline: 16,
  },
  editFooter: {
    alignItems: "center",
    borderTopColor: "rgb(var(--tbr-color-line))",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    justifyContent: "space-between",
    paddingBlock: 7,
    paddingInline: 14,
  },
  saved: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "flex",
    fontSize: 12,
    gap: 4,
  },
  savedDot: {
    backgroundColor: "rgb(var(--tbr-color-accent))",
    borderRadius: "50%",
    height: 5,
    width: 5,
  },
  editButtons: {
    display: "flex",
    gap: 4,
  },
  empty: {
    paddingBlock: 24,
    paddingInline: 16,
    textAlign: "center",
  },
  emptyIcon: {
    color: "rgb(var(--tbr-color-text-subtle))",
    marginBottom: 8,
    opacity: 0.4,
  },
  emptyText: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 14,
  },
  emptyHint: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 12,
    marginTop: 4,
  },
})
