import * as stylex from "@stylexjs/stylex"

export const composerStyles = stylex.create({
  composerBar: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderTop: "1px solid rgb(var(--tbr-color-line))",
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    gap: 8,
    paddingBlock: 8,
    paddingInline: 16,
  },
  composerShell: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: "8px 10px 7px",
    position: "relative",
    width: "min(100%, 760px)",
    ":focus-within": {
      borderColor: "rgb(var(--tbr-color-accent))",
    },
  },
  composerAttachmentList: {
    display: "grid",
    gap: 6,
    gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))",
    marginBottom: 2,
    maxHeight: 82,
    overflowY: "auto",
  },
  composerAttachment: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    gap: 6,
    minWidth: 0,
    padding: "5px 6px 5px 8px",
  },
  composerAttachmentName: {
    color: "rgb(var(--tbr-color-text))",
    flex: 1,
    fontSize: 12,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  composerAttachmentSize: {
    color: "rgb(var(--tbr-color-text-subtle))",
    flexShrink: 0,
    fontSize: 10,
  },
  composerAttachmentRemove: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-subtle))",
    cursor: "pointer",
    display: "inline-flex",
    flexShrink: 0,
    height: 22,
    justifyContent: "center",
    padding: 0,
    width: 22,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      borderColor: "rgb(var(--tbr-color-accent))",
      outline: "none",
    },
  },
  composerToolbar: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    justifyContent: "space-between",
    minHeight: 28,
  },
  composerLeading: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: 4,
  },
  composerChips: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 4,
    justifyContent: "flex-end",
    minWidth: 0,
    marginInlineStart: "auto",
  },
  composerChip: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    fontSize: 12,
    gap: 4,
    height: 28,
    maxWidth: "min(220px, 100%)",
    padding: "0 8px",
    whiteSpace: "nowrap",
    transitionDuration: "120ms",
    transitionProperty: "background-color, border-color, color",
    transitionTimingFunction: "ease",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      borderColor: "rgb(var(--tbr-color-accent))",
      outline: "none",
    },
  },
  composerContextButton: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-hover))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    height: 28,
    justifyContent: "center",
    minWidth: 28,
    padding: 0,
    position: "relative",
    transitionDuration: "120ms",
    transitionProperty: "background-color, border-color, color",
    transitionTimingFunction: "ease",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      borderColor: "rgb(var(--tbr-color-accent))",
      outline: "none",
    },
  },
  composerContextLabel: {
    borderStyle: "none",
    borderWidth: 0,
    clip: "rect(0 0 0 0)",
    clipPath: "inset(50%)",
    height: 1,
    margin: -1,
    overflow: "hidden",
    padding: 0,
    position: "absolute",
    whiteSpace: "nowrap",
    width: 1,
  },
  composerAttachmentInput: {
    display: "none",
  },
  composerSendButton: {
    height: 28,
    width: 28,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent))",
      borderColor: "rgb(var(--tbr-color-accent))",
    },
    ":active": {
      backgroundColor: "rgb(var(--tbr-color-accent))",
      borderColor: "rgb(var(--tbr-color-accent))",
    },
    ":disabled:hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-soft))",
      borderColor: "rgb(var(--tbr-color-line))",
      color: "rgb(var(--tbr-color-text-subtle))",
    },
  },
  composerStopButton: {
    height: 28,
    width: 28,
  },
  composerRunActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: 4,
  },
  editBanner: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderRadius: "var(--tbr-radius-control)",
    display: "flex",
    gap: 8,
    justifyContent: "space-between",
    padding: "6px 10px",
  },
  editBannerText: {
    color: "rgb(var(--tbr-color-accent))",
    fontSize: 12,
    fontWeight: 600,
  },
  composerTextarea: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    flex: 1,
    fontSize: 14,
    lineHeight: 1.5,
    height: 56,
    minHeight: 56,
    minWidth: 0,
    paddingBlock: 0,
    paddingInline: 0,
    resize: "none",
    width: "100%",
    "::placeholder": {
      color: "rgb(var(--tbr-color-text-subtle))",
    },
    ":focus": {
      boxShadow: "none",
      outline: "none",
    },
  },
})
