import * as stylex from "@stylexjs/stylex"

/** Inline composer tool menu; intentionally separate from the general chat layout sheet. */
export const slashMenuStyles = stylex.create({
  menu: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line-strong))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 8px 24px rgb(var(--tbr-color-shadow) / 14%)",
    display: "grid",
    gap: 2,
    left: 0,
    maxHeight: 280,
    overflowY: "auto",
    padding: 4,
    position: "absolute",
    right: 0,
    bottom: "calc(100% + 6px)",
    zIndex: 3,
  },
  command: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "flex",
    gap: 10,
    minHeight: 32,
    paddingBlock: 4,
    paddingInline: 8,
    textAlign: "left",
    width: "100%",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line))",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      borderColor: "rgb(var(--tbr-color-focus))",
      outline: "none",
    },
    ":disabled": {
      cursor: "not-allowed",
      opacity: 0.45,
    },
  },
  commandActive: {
    backgroundColor: "rgb(var(--tbr-color-surface-hover))",
    borderColor: "rgb(var(--tbr-color-line))",
    color: "rgb(var(--tbr-color-text))",
  },
  commandCopy: {
    alignItems: "baseline",
    display: "flex",
    gap: 6,
    minWidth: 0,
  },
  commandTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 12,
    fontWeight: 600,
    lineHeight: 1.3,
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
  commandDescription: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 11,
    lineHeight: 1.3,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  modelList: {
    display: "grid",
    gap: 6,
  },
  modelGroup: {
    display: "grid",
    gap: 2,
  },
  modelGroupLabel: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 11,
    fontWeight: 650,
    padding: "4px 8px 2px",
  },
  commandGroupLabel: {
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "block",
    fontSize: 10.5,
    fontWeight: 650,
    letterSpacing: 0.2,
    padding: "6px 8px 1px",
    textAlign: "left",
    textTransform: "uppercase",
    width: "100%",
  },
})
