import * as stylex from "@stylexjs/stylex"

/** Compact context-window indicator used only by the composer. */
export const contextUsageStyles = stylex.create({
  meter: {
    alignItems: "center",
    display: "flex",
    justifyContent: "flex-end",
    minHeight: 28,
    width: "auto",
  },
  indicator: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: "var(--tbr-radius-pill)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "help",
    display: "inline-flex",
    height: 24,
    justifyContent: "center",
    minWidth: 24,
    padding: 1,
    position: "relative",
    transitionDuration: "120ms",
    transitionProperty: "background-color, border-color, color",
    transitionTimingFunction: "ease",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      borderColor: "rgb(var(--tbr-color-accent))",
      outline: "none",
    },
  },
  ring: {
    display: "block",
    height: 20,
    overflow: "visible",
    width: 20,
  },
  ringTrack: {
    fill: "none",
    stroke: "rgb(var(--tbr-color-line))",
    strokeWidth: 2.5,
  },
  ringProgress: {
    fill: "none",
    stroke: "rgb(var(--tbr-color-accent))",
    strokeLinecap: "round",
    strokeWidth: 2.5,
    transitionDuration: "180ms",
    transitionProperty: "stroke-dashoffset",
    transitionTimingFunction: "cubic-bezier(0.2, 0, 0, 1)",
  },
  percent: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 8,
    fontWeight: 650,
    lineHeight: 1,
    pointerEvents: "none",
    position: "absolute",
  },
  tooltip: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line-strong))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 8px 24px rgb(var(--tbr-color-shadow) / 14%)",
    display: "grid",
    gap: 3,
    minWidth: 184,
    padding: "8px 10px",
    pointerEvents: "none",
    position: "absolute",
    right: 0,
    bottom: "calc(100% + 6px)",
    zIndex: 2,
  },
  tooltipTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 12,
    fontWeight: 650,
    lineHeight: 1.3,
  },
  tooltipValue: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontFamily: "var(--tbr-font-mono)",
    fontSize: 11,
    lineHeight: 1.3,
  },
  tooltipHint: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 10,
    lineHeight: 1.3,
  },
})
