import * as stylex from "@stylexjs/stylex"

export const styles = stylex.create({
  // Card variants (S semantic card, M/L/XL content card)
  small: {
    width: "100%",
    height: "100%",
    minWidth: 0,
    minHeight: 0,
    padding: "clamp(7px, 8cqw, 11px)",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr) auto",
    gap: "clamp(4px, 5cqw, 7px)",
    cursor: "pointer",
    containerType: "inline-size",
  },
  smallHead: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 4,
  },
  smallPreview: {
    display: "-webkit-box",
    overflow: "hidden",
    alignSelf: "center",
    fontSize: "clamp(7px, 9cqw, 11px)",
    fontWeight: 520,
    lineHeight: 1.45,
    whiteSpace: "pre-wrap",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 4,
  },
  smallPreviewEmpty: {
    color: "rgb(var(--tbr-color-text-subtle))",
  },
  smallFoot: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 4,
    paddingTop: "clamp(3px, 4cqw, 5px)",
    borderTop: "1px solid rgb(var(--tbr-color-line))",
  },
  smallMeta: {
    overflow: "hidden",
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: "clamp(4px, 5cqw, 7px)",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  smallState: {
    color: "rgb(var(--tbr-color-accent))",
    fontSize: "clamp(4px, 5cqw, 7px)",
    fontWeight: 700,
  },

  card: {
    width: "100%",
    height: "100%",
    minWidth: 0,
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr) auto",
    gap: 7,
    padding: 9,
    border: "1px solid rgb(var(--tbr-color-line))",
    borderRadius: 9,
    backgroundColor: "rgb(var(--tbr-color-surface))",
    overflow: "hidden",
  },
  cardHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 7,
  },
  kicker: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 7,
    fontWeight: 750,
    letterSpacing: "0.11em",
    textTransform: "uppercase",
  },
  cardState: {
    color: "rgb(var(--tbr-color-accent))",
    fontSize: 7,
    fontWeight: 700,
  },
  composer: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  composerInput: {
    flex: 1,
    minWidth: 0,
  },
  previewList: {
    minHeight: 0,
    display: "grid",
    alignContent: "start",
    gap: 5,
    overflow: "hidden",
  },
  previewBubble: {
    minWidth: 0,
    display: "grid",
    gap: 3,
    padding: "6px 7px",
    border: "1px solid rgb(var(--tbr-color-line))",
    borderRadius: 7,
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    cursor: "pointer",
  },
  previewRole: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 7,
    fontWeight: 650,
  },
  previewContent: {
    minWidth: 0,
    width: "100%",
    overflow: "hidden",
    color: "rgb(var(--tbr-color-text))",
    fontSize: 8,
    lineHeight: 1.45,
    whiteSpace: "pre-wrap",
    display: "-webkit-box",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
  },
  previewEmpty: {
    minHeight: 0,
    alignSelf: "center",
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 8,
    lineHeight: 1.5,
  },

  // Expand view
  expandRoot: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minHeight: "min(468px, calc(100vh - 116px))",
    minWidth: 0,
  },
  expandHeader: {
    alignItems: "center",
    borderBottomColor: "rgb(var(--tbr-color-line))",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexShrink: 0,
    gap: 8,
    paddingBlock: 8,
    paddingInline: 12,
    "@media (min-width: 720px)": {
      display: "none",
    },
  },
  historyToggle: {
    flexShrink: 0,
  },
  activeTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 13,
    fontWeight: 650,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  expandBody: {
    display: "flex",
    flex: 1,
    flexDirection: "row",
    minHeight: 0,
  },
  side: {
    backgroundColor: "rgb(var(--tbr-color-page))",
    borderRightColor: "rgb(var(--tbr-color-line))",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    overflowY: "auto",
    width: 216,
    "@media (max-width: 720px)": {
      display: "none",
    },
  },
  sideHead: {
    paddingBlock: 10,
    paddingInline: 12,
  },
  newChatButton: {
    width: "100%",
  },
  sideList: {
    display: "grid",
    gap: 2,
    paddingBlock: 2,
    paddingInline: 8,
    paddingBottom: 12,
  },
  sideEmpty: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 12,
    paddingBlock: 4,
    paddingInline: 12,
  },
  conversationRow: {
    alignItems: "center",
    borderRadius: "var(--tbr-radius-control)",
    display: "flex",
    gap: 2,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
    },
  },
  conversationRowActive: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    },
  },
  conversationMain: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "inherit",
    cursor: "pointer",
    display: "grid",
    flex: 1,
    fontFamily: "inherit",
    gap: 1,
    minWidth: 0,
    paddingBlock: 6,
    paddingInline: 8,
    textAlign: "left",
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 1,
    },
  },
  conversationTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 13,
    fontWeight: 540,
    lineHeight: 1.35,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  conversationMeta: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 10,
  },
  conversationActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: 0,
    paddingRight: 4,
  },
  main: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minWidth: 0,
  },
  thread: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: 10,
    minHeight: 0,
    overflowY: "auto",
    paddingBlock: 12,
    paddingInline: 16,
  },
  turn: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    maxWidth: "100%",
  },
  turnUser: {
    alignItems: "flex-end",
  },
  turnAssistant: {
    alignItems: "flex-start",
  },
  roleLabel: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 10,
    fontWeight: 650,
    marginBottom: 3,
  },
  userBubble: {
    maxWidth: "min(560px, 100%)",
    padding: "8px 12px",
    border: "1px solid rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    color: "rgb(var(--tbr-color-text))",
    fontSize: 14,
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  assistantBubble: {
    maxWidth: "min(680px, 100%)",
    color: "rgb(var(--tbr-color-text))",
    fontSize: 14,
    lineHeight: 1.55,
    wordBreak: "break-word",
  },
  empty: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 0,
  },
  statusBar: {
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    gap: 8,
    paddingBlock: 10,
    paddingInline: 16,
  },
  statusActions: {
    alignItems: "center",
    display: "flex",
    gap: 8,
  },
  noticeStrip: {
    flexShrink: 0,
    paddingBlock: 6,
    paddingInline: 16,
  },
  notice: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 12,
  },
  generating: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 12,
  },
  composerBar: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderTop: "1px solid rgb(var(--tbr-color-line))",
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    gap: 8,
    paddingBlock: 10,
    paddingInline: 16,
  },
  composerRow: {
    alignItems: "flex-end",
    display: "flex",
    gap: 8,
  },
  editBanner: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderRadius: "var(--tbr-radius-control)",
    display: "flex",
    gap: 8,
    justifyContent: "space-between",
    padding: "6px 10px",
  },
  editBannerText: {
    color: "rgb(var(--tbr-color-accent))",
    fontSize: 12,
    fontWeight: 600,
  },
  userTurnRow: {
    alignItems: "flex-end",
    display: "flex",
    gap: 4,
    maxWidth: "100%",
  },
  optionsForm: {
    display: "grid",
    gap: 12,
  },
  optionsLabel: {
    display: "grid",
    gap: 4,
  },
  optionsLabelText: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 12,
    fontWeight: 600,
  },
  optionsHint: {
    color: "rgb(var(--tbr-color-danger))",
    fontSize: 11,
  },
  composerTextarea: {
    flex: 1,
    minWidth: 0,
    resize: "none",
  },
})
