import * as stylex from "@stylexjs/stylex"

export const styles = stylex.create({
  // Quiet mark: a non-interactive brand lockup, aligned with the Refined Sage widget system.
  brandCard: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderRadius: "inherit",
    color: "rgb(var(--tbr-color-text))",
    display: "flex",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    padding: 0,
    width: "100%",
  },
  brandCardSmall: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderRadius: "inherit",
    color: "rgb(var(--tbr-color-text))",
    containerType: "inline-size",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    justifyContent: "space-between",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    padding: "clamp(6px, 6cqw, 12px)",
    width: "100%",
  },
  brandVisual: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderRightColor: "rgb(var(--tbr-color-line))",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    color: "rgb(var(--tbr-color-accent))",
    display: "flex",
    flex: "0 0 35%",
    height: "100%",
    justifyContent: "center",
    minHeight: 0,
    minWidth: 0,
  },
  brandContent: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    gap: 6,
    justifyContent: "flex-end",
    minWidth: 0,
    padding: 14,
  },
  brandVisualSmall: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-accent))",
    display: "flex",
    height: "clamp(34px, 30cqw, 56px)",
    justifyContent: "center",
    width: "clamp(34px, 30cqw, 56px)",
  },
  brandContentSmall: {
    display: "flex",
    flexDirection: "column",
    gap: "clamp(2px, 3cqw, 5px)",
    minWidth: 0,
  },
  brandTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 16,
    fontWeight: 650,
    letterSpacing: "-0.01em",
    whiteSpace: "nowrap",
  },
  brandRule: {
    backgroundColor: "rgb(var(--tbr-color-accent))",
    height: 2,
    marginTop: 1,
    width: 24,
  },
  brandRuleSmall: {
    backgroundColor: "rgb(var(--tbr-color-accent))",
    height: 2,
    marginTop: 1,
    width: "clamp(16px, 20cqw, 24px)",
  },
  brandMeta: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontFamily: "var(--tbr-font-mono)",
    fontSize: 10,
    fontWeight: 500,
    letterSpacing: "0.06em",
    lineHeight: 1.3,
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  brandMetaSmall: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontFamily: "var(--tbr-font-mono)",
    fontSize: "clamp(7px, 6cqw, 10px)",
    fontWeight: 500,
    letterSpacing: "0.03em",
    lineHeight: 1.3,
    overflow: "hidden",
    textOverflow: "ellipsis",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  brandTitleSmall: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: "clamp(12px, 9cqw, 15px)",
    fontWeight: 650,
    letterSpacing: "-0.01em",
    whiteSpace: "nowrap",
  },

  // Expand view
  expandRoot: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minHeight: "min(468px, calc(100vh - 116px))",
    minWidth: 0,
  },
  expandHeader: {
    alignItems: "center",
    borderBottomColor: "rgb(var(--tbr-color-line))",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexShrink: 0,
    gap: 8,
    paddingBlock: 8,
    paddingInline: 12,
    "@media (min-width: 720px)": {
      display: "none",
    },
  },
  historyToggle: {
    flexShrink: 0,
  },
  activeTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 13,
    fontWeight: 650,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  expandBody: {
    display: "flex",
    flex: 1,
    flexDirection: "row",
    minHeight: 0,
  },
  side: {
    backgroundColor: "rgb(var(--tbr-color-page))",
    borderRightColor: "rgb(var(--tbr-color-line))",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    overflowY: "auto",
    width: 216,
    "@media (max-width: 720px)": {
      display: "none",
    },
  },
  sideHead: {
    display: "grid",
    gap: 8,
    paddingBlock: 10,
    paddingInline: 8,
  },
  sideHeading: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 11,
    fontWeight: 650,
    letterSpacing: "0.04em",
  },
  newChatButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-text))",
    display: "flex",
    fontSize: 13,
    fontWeight: 540,
    gap: 8,
    height: 32,
    justifyContent: "flex-start",
    paddingInline: 8,
    textAlign: "left",
    transitionDuration: "120ms",
    transitionProperty: "background-color, border-color",
    transitionTimingFunction: "ease",
    width: "100%",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
    ":focus-visible": {
      outlineColor: "rgb(var(--tbr-color-focus))",
      outlineOffset: 1,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  newChatShortcut: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "rgb(var(--tbr-color-text-subtle))",
    fontFamily: "var(--tbr-font-mono)",
    fontSize: 10,
    fontWeight: 500,
    lineHeight: 1.35,
    marginInlineStart: "auto",
    padding: 0,
  },
  sideList: {
    display: "grid",
    gap: 2,
    paddingBlock: 2,
    paddingInline: 8,
    paddingBottom: 12,
  },
  sideEmpty: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 12,
    paddingBlock: 4,
    paddingInline: 12,
  },
  conversationRow: {
    alignItems: "center",
    borderRadius: "var(--tbr-radius-control)",
    display: "flex",
    gap: 2,
    borderColor: "transparent",
    borderStyle: "solid",
    borderWidth: 1,
    boxSizing: "border-box",
    height: 32,
    position: "relative",
    transitionDuration: "120ms",
    transitionProperty: "background-color, border-color",
    transitionTimingFunction: "ease",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
  },
  conversationRowActive: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderColor: "rgb(var(--tbr-color-accent))",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent-soft))",
      borderColor: "rgb(var(--tbr-color-accent))",
    },
  },
  conversationMain: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "inherit",
    cursor: "pointer",
    display: "flex",
    flex: 1,
    fontFamily: "inherit",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
    height: "100%",
    minHeight: 0,
    paddingBlock: 0,
    paddingInline: 8,
    textAlign: "left",
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 1,
    },
  },
  conversationTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 13,
    fontWeight: 540,
    lineHeight: 1.35,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
    minWidth: 0,
  },
  conversationMeta: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 11,
    flexShrink: 0,
    transitionDuration: "120ms",
    transitionProperty: "opacity",
    transitionTimingFunction: "ease",
  },
  conversationMetaHidden: {
    opacity: 0,
  },
  conversationActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    opacity: 0,
    pointerEvents: "none",
    position: "absolute",
    right: 4,
    top: "50%",
    transform: "translateY(-50%)",
    transitionDuration: "120ms",
    transitionProperty: "opacity",
    transitionTimingFunction: "ease",
    ":focus-within": {
      opacity: 1,
    },
  },
  conversationActionsVisible: {
    opacity: 1,
    pointerEvents: "auto",
  },
  main: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minWidth: 0,
  },
  thread: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: 10,
    minHeight: 0,
    overflowY: "auto",
    paddingBlock: 12,
    paddingInline: 16,
  },
  reasoning: {
    borderLeftColor: "rgb(var(--tbr-color-line-strong))",
    borderLeftStyle: "solid",
    borderLeftWidth: 2,
    color: "rgb(var(--tbr-color-text-muted))",
    marginBottom: 8,
    maxWidth: "min(680px, 100%)",
    paddingInlineStart: 8,
  },
  reasoningTrigger: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 12,
    fontWeight: 540,
    gap: 5,
    minHeight: 24,
    padding: 0,
    ":hover": { color: "rgb(var(--tbr-color-text))" },
    ":focus-visible": {
      outlineColor: "rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  reasoningChevron: {
    transitionDuration: "120ms",
    transitionProperty: "transform",
    transitionTimingFunction: "ease",
  },
  reasoningChevronOpen: { transform: "rotate(90deg)" },
  reasoningContent: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 12,
    lineHeight: 1.55,
    paddingBlock: 4,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  turn: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    maxWidth: "100%",
  },
  turnUser: {
    alignItems: "flex-end",
  },
  turnAssistant: {
    alignItems: "flex-start",
  },
  userBubble: {
    maxWidth: "min(560px, 100%)",
    padding: "8px 12px",
    border: "1px solid rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    color: "rgb(var(--tbr-color-text))",
    fontSize: 14,
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  userMessageContent: {
    display: "grid",
    gap: 8,
  },
  userMessageText: {
    whiteSpace: "pre-wrap",
  },
  userAttachmentList: {
    display: "grid",
    gap: 6,
    maxWidth: "min(100%, 420px)",
  },
  userAttachment: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    overflow: "hidden",
  },
  userAttachmentButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "rgb(var(--tbr-color-text))",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    gap: 8,
    minHeight: 48,
    padding: 6,
    textAlign: "left",
    width: "100%",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
    },
    ":focus-visible": {
      outlineColor: "rgb(var(--tbr-color-focus))",
      outlineOffset: -2,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
    ":disabled": {
      cursor: "default",
    },
    ":disabled:hover": {
      backgroundColor: "transparent",
    },
  },
  userAttachmentIcon: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    display: "inline-flex",
    flexShrink: 0,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  userAttachmentThumbnail: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "block",
    flexShrink: 0,
    height: 34,
    objectFit: "cover",
    width: 34,
  },
  userAttachmentInfo: {
    display: "grid",
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  userAttachmentName: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 12,
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  userAttachmentMeta: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 11,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  userAttachmentAffordance: {
    color: "rgb(var(--tbr-color-text-subtle))",
    flexShrink: 0,
  },
  userAttachmentDetail: {
    borderTopColor: "rgb(var(--tbr-color-line))",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "grid",
    gap: 6,
    padding: 6,
  },
  userAttachmentImage: {
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "block",
    height: "auto",
    maxHeight: 240,
    maxWidth: "100%",
    objectFit: "contain",
  },
  userAttachmentPreview: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-text-muted))",
    fontFamily: "var(--tbr-font-mono)",
    fontSize: 11,
    lineHeight: 1.45,
    margin: 0,
    maxHeight: 168,
    overflow: "auto",
    padding: 8,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  userMessageImage: {
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "block",
    height: "auto",
    maxHeight: 240,
    maxWidth: "min(100%, 420px)",
    objectFit: "contain",
  },
  assistantBubble: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 14,
    lineHeight: 1.55,
    wordBreak: "break-word",
  },
  assistantMessageRow: {
    alignItems: "flex-start",
    display: "flex",
    flexDirection: "column",
    maxWidth: "100%",
  },
  messageActions: {
    alignItems: "center",
    display: "flex",
    gap: 2,
    opacity: 0,
    transitionDuration: "120ms",
    transitionProperty: "opacity",
    transitionTimingFunction: "ease",
    ":hover": {
      opacity: 1,
    },
    ":focus-within": {
      opacity: 1,
    },
  },
  empty: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minHeight: 0,
    backgroundColor: "rgb(var(--tbr-color-page-muted))",
  },
  emptyWelcome: {
    alignItems: "center",
    display: "flex",
    flex: 1,
    minHeight: 0,
    justifyContent: "center",
    paddingBlock: 28,
    paddingInline: 24,
  },
  emptyWelcomeContent: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    gap: 16,
    maxWidth: 760,
    textAlign: "center",
    width: "100%",
  },
  emptyTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: "clamp(20px, 3vw, 28px)",
    fontWeight: 650,
    letterSpacing: "-0.02em",
    lineHeight: 1.25,
  },
  emptyComposer: {
    width: "100%",
  },
  emptyWelcomeIcon: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-accent))",
    display: "flex",
    height: 40,
    justifyContent: "center",
    marginBottom: 8,
    width: 40,
  },
  statusBar: {
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    gap: 8,
    paddingBlock: 10,
    paddingInline: 16,
  },
  statusActions: {
    alignItems: "center",
    display: "flex",
    gap: 8,
  },
  noticeStrip: {
    flexShrink: 0,
    paddingBlock: 6,
    paddingInline: 16,
  },
  notice: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 12,
  },
  generating: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 12,
  },
  generatingRow: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "flex",
    gap: 6,
  },
  queueList: {
    display: "grid",
    gap: 4,
    margin: "0 16px 8px",
  },
  queueItem: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    gap: 6,
    minHeight: 30,
    paddingInlineStart: 8,
  },
  queueItemText: {
    color: "rgb(var(--tbr-color-text-muted))",
    flex: 1,
    fontSize: 12,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  composerBar: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderTop: "1px solid rgb(var(--tbr-color-line))",
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    gap: 8,
    paddingBlock: 8,
    paddingInline: 16,
  },
  composerShell: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: "8px 10px 7px",
    width: "min(100%, 760px)",
    ":focus-within": {
      borderColor: "rgb(var(--tbr-color-accent))",
    },
  },
  composerAttachmentList: {
    display: "grid",
    gap: 6,
    gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))",
    marginBottom: 2,
    maxHeight: 82,
    overflowY: "auto",
  },
  composerAttachment: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    gap: 6,
    minWidth: 0,
    padding: "5px 6px 5px 8px",
  },
  composerAttachmentName: {
    color: "rgb(var(--tbr-color-text))",
    flex: 1,
    fontSize: 12,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  composerAttachmentSize: {
    color: "rgb(var(--tbr-color-text-subtle))",
    flexShrink: 0,
    fontSize: 10,
  },
  composerAttachmentRemove: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-subtle))",
    cursor: "pointer",
    display: "inline-flex",
    flexShrink: 0,
    height: 22,
    justifyContent: "center",
    padding: 0,
    width: 22,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      borderColor: "rgb(var(--tbr-color-accent))",
      outline: "none",
    },
  },
  composerToolbar: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    justifyContent: "space-between",
    minHeight: 28,
  },
  composerLeading: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: 4,
  },
  composerChips: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 4,
    justifyContent: "flex-end",
    minWidth: 0,
    marginInlineStart: "auto",
  },
  composerChip: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    fontSize: 12,
    gap: 4,
    height: 28,
    maxWidth: "min(220px, 100%)",
    padding: "0 8px",
    whiteSpace: "nowrap",
    transitionDuration: "120ms",
    transitionProperty: "background-color, border-color, color",
    transitionTimingFunction: "ease",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      borderColor: "rgb(var(--tbr-color-accent))",
      outline: "none",
    },
  },
  composerContextButton: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-hover))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    height: 28,
    justifyContent: "center",
    minWidth: 28,
    padding: 0,
    position: "relative",
    transitionDuration: "120ms",
    transitionProperty: "background-color, border-color, color",
    transitionTimingFunction: "ease",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      borderColor: "rgb(var(--tbr-color-accent))",
      outline: "none",
    },
  },
  composerContextLabel: {
    borderStyle: "none",
    borderWidth: 0,
    clip: "rect(0 0 0 0)",
    clipPath: "inset(50%)",
    height: 1,
    margin: -1,
    overflow: "hidden",
    padding: 0,
    position: "absolute",
    whiteSpace: "nowrap",
    width: 1,
  },
  composerAttachmentInput: {
    display: "none",
  },
  composerSendButton: {
    height: 28,
    width: 28,
    ":disabled": {
      backgroundColor: "rgb(var(--tbr-color-surface))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
      color: "rgb(var(--tbr-color-text-muted))",
      opacity: 1,
    },
  },
  composerRunActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: 4,
  },
  contextList: {
    display: "grid",
    gap: 6,
  },
  contextItem: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderRadius: "var(--tbr-radius-control)",
    display: "flex",
    gap: 8,
    padding: "6px 8px",
  },
  contextItemMain: {
    display: "grid",
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  contextItemLabel: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 12,
    fontWeight: 600,
  },
  contextItemPreview: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 11,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  editBanner: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderRadius: "var(--tbr-radius-control)",
    display: "flex",
    gap: 8,
    justifyContent: "space-between",
    padding: "6px 10px",
  },
  editBannerText: {
    color: "rgb(var(--tbr-color-accent))",
    fontSize: 12,
    fontWeight: 600,
  },
  userTurnRow: {
    alignItems: "flex-end",
    display: "flex",
    gap: 4,
    maxWidth: "100%",
  },
  optionsForm: {
    display: "grid",
    gap: 12,
  },
  optionsLabel: {
    display: "grid",
    gap: 4,
  },
  optionsLabelText: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 12,
    fontWeight: 600,
  },
  optionsHint: {
    color: "rgb(var(--tbr-color-danger))",
    fontSize: 11,
  },
  composerTextarea: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    flex: 1,
    fontSize: 14,
    lineHeight: 1.5,
    height: 56,
    minHeight: 56,
    minWidth: 0,
    paddingBlock: 0,
    paddingInline: 0,
    resize: "none",
    width: "100%",
    "::placeholder": {
      color: "rgb(var(--tbr-color-text-subtle))",
    },
    ":focus": {
      boxShadow: "none",
      outline: "none",
    },
  },
})
