import * as stylex from "@stylexjs/stylex"

/** Provider-supplied reasoning summary presentation. */
export const reasoningStyles = stylex.create({
  root: {
    display: "grid",
    gap: 4,
    marginBottom: 6,
    maxWidth: "min(680px, 100%)",
  },
  toggle: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    fontSize: 12,
    gap: 5,
    justifySelf: "start",
    lineHeight: 1.35,
    paddingBlock: 3,
    paddingInline: 4,
    textAlign: "left",
    transitionDuration: "120ms",
    transitionProperty: "background-color, color",
    transitionTimingFunction: "ease",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      outlineColor: "rgb(var(--tbr-color-focus))",
      outlineOffset: 1,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  chevron: {
    color: "rgb(var(--tbr-color-text-subtle))",
    flexShrink: 0,
    height: 13,
    width: 13,
  },
  icon: {
    color: "rgb(var(--tbr-color-accent))",
    flexShrink: 0,
    height: 14,
    width: 14,
  },
  label: {
    fontWeight: 540,
  },
  content: {
    borderLeftColor: "rgb(var(--tbr-color-line))",
    borderLeftStyle: "solid",
    borderLeftWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    fontFamily: "var(--tbr-font-mono)",
    fontSize: 12,
    lineHeight: 1.5,
    marginInlineStart: 10,
    maxWidth: "100%",
    paddingBlock: 2,
    paddingInlineStart: 12,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
})
