import * as stylex from "@stylexjs/stylex"

export const messageStyles = stylex.create({
  thread: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: 10,
    minHeight: 0,
    overflowY: "auto",
    paddingBlock: 12,
    paddingInline: 16,
  },
  turn: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    maxWidth: "100%",
  },
  turnUser: {
    alignItems: "flex-end",
  },
  turnAssistant: {
    alignItems: "flex-start",
  },
  userBubble: {
    maxWidth: "min(560px, 100%)",
    padding: "8px 12px",
    border: "1px solid rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    color: "rgb(var(--tbr-color-text))",
    fontSize: 14,
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  userMessageContent: {
    display: "grid",
    gap: 8,
  },
  userMessageText: {
    whiteSpace: "pre-wrap",
  },
  userAttachmentList: {
    display: "grid",
    gap: 6,
    maxWidth: "min(100%, 420px)",
  },
  userAttachment: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    overflow: "hidden",
  },
  userAttachmentButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "rgb(var(--tbr-color-text))",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    gap: 8,
    minHeight: 48,
    padding: 6,
    textAlign: "left",
    width: "100%",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
    },
    ":focus-visible": {
      outlineColor: "rgb(var(--tbr-color-focus))",
      outlineOffset: -2,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
    ":disabled": {
      cursor: "default",
    },
    ":disabled:hover": {
      backgroundColor: "transparent",
    },
  },
  userAttachmentIcon: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    display: "inline-flex",
    flexShrink: 0,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  userAttachmentThumbnail: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "block",
    flexShrink: 0,
    height: 34,
    objectFit: "cover",
    width: 34,
  },
  userAttachmentInfo: {
    display: "grid",
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  userAttachmentName: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 12,
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  userAttachmentMeta: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 11,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  userAttachmentAffordance: {
    color: "rgb(var(--tbr-color-text-subtle))",
    flexShrink: 0,
  },
  userAttachmentDetail: {
    borderTopColor: "rgb(var(--tbr-color-line))",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "grid",
    gap: 6,
    padding: 6,
  },
  userAttachmentImage: {
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "block",
    height: "auto",
    maxHeight: 240,
    maxWidth: "100%",
    objectFit: "contain",
  },
  userAttachmentPreview: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-text-muted))",
    fontFamily: "var(--tbr-font-mono)",
    fontSize: 11,
    lineHeight: 1.45,
    margin: 0,
    maxHeight: 168,
    overflow: "auto",
    padding: 8,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  userMessageImage: {
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "block",
    height: "auto",
    maxHeight: 240,
    maxWidth: "min(100%, 420px)",
    objectFit: "contain",
  },
  assistantBubble: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 14,
    lineHeight: 1.55,
    wordBreak: "break-word",
  },
  assistantMessageRow: {
    alignItems: "flex-start",
    display: "flex",
    flexDirection: "column",
    maxWidth: "100%",
  },
  messageActions: {
    alignItems: "center",
    display: "flex",
    gap: 2,
    opacity: 0,
    transitionDuration: "120ms",
    transitionProperty: "opacity",
    transitionTimingFunction: "ease",
    ":hover": {
      opacity: 1,
    },
    ":focus-within": {
      opacity: 1,
    },
  },
  generating: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 12,
  },
  generatingRow: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "flex",
    gap: 6,
  },
  queueList: {
    display: "grid",
    gap: 4,
    margin: "0 16px 8px",
  },
  queueItem: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    gap: 6,
    minHeight: 30,
    paddingInlineStart: 8,
  },
  queueItemText: {
    color: "rgb(var(--tbr-color-text-muted))",
    flex: 1,
    fontSize: 12,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  userTurnRow: {
    alignItems: "flex-end",
    display: "flex",
    gap: 4,
    maxWidth: "100%",
  },
})
