import * as stylex from "@stylexjs/stylex"

export const conversationListStyles = stylex.create({
  sideHead: {
    display: "grid",
    gap: 8,
    paddingBlock: 10,
    paddingInline: 8,
  },
  sideHeading: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 11,
    fontWeight: 650,
    letterSpacing: "0.04em",
  },
  newChatButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-text))",
    display: "flex",
    fontSize: 13,
    fontWeight: 540,
    gap: 8,
    height: 32,
    justifyContent: "flex-start",
    paddingInline: 8,
    textAlign: "left",
    transitionDuration: "120ms",
    transitionProperty: "background-color, border-color",
    transitionTimingFunction: "ease",
    width: "100%",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
    ":focus-visible": {
      outlineColor: "rgb(var(--tbr-color-focus))",
      outlineOffset: 1,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  newChatShortcut: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "rgb(var(--tbr-color-text-subtle))",
    fontFamily: "var(--tbr-font-mono)",
    fontSize: 10,
    fontWeight: 500,
    lineHeight: 1.35,
    marginInlineStart: "auto",
    padding: 0,
  },
  sideList: {
    display: "grid",
    gap: 2,
    paddingBlock: 2,
    paddingInline: 8,
    paddingBottom: 12,
  },
  sideEmpty: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 12,
    paddingBlock: 4,
    paddingInline: 12,
  },
  conversationRow: {
    alignItems: "center",
    borderRadius: "var(--tbr-radius-control)",
    display: "flex",
    gap: 2,
    borderColor: "transparent",
    borderStyle: "solid",
    borderWidth: 1,
    boxSizing: "border-box",
    height: 32,
    position: "relative",
    transitionDuration: "120ms",
    transitionProperty: "background-color, border-color",
    transitionTimingFunction: "ease",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
  },
  conversationRowActive: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderColor: "rgb(var(--tbr-color-accent))",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent-soft))",
      borderColor: "rgb(var(--tbr-color-accent))",
    },
  },
  conversationMain: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "inherit",
    cursor: "pointer",
    display: "flex",
    flex: 1,
    fontFamily: "inherit",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
    height: "100%",
    minHeight: 0,
    paddingBlock: 0,
    paddingInline: 8,
    textAlign: "left",
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 1,
    },
  },
  conversationTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 13,
    fontWeight: 540,
    lineHeight: 1.35,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
    minWidth: 0,
  },
  conversationMeta: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 11,
    flexShrink: 0,
    transitionDuration: "120ms",
    transitionProperty: "opacity",
    transitionTimingFunction: "ease",
  },
  conversationMetaHidden: {
    opacity: 0,
  },
  conversationActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    opacity: 0,
    pointerEvents: "none",
    position: "absolute",
    right: 4,
    top: "50%",
    transform: "translateY(-50%)",
    transitionDuration: "120ms",
    transitionProperty: "opacity",
    transitionTimingFunction: "ease",
    ":focus-within": {
      opacity: 1,
    },
  },
  conversationActionsVisible: {
    opacity: 1,
    pointerEvents: "auto",
  },
})
