import * as stylex from "@stylexjs/stylex"
import type { CompiledStyles, InlineStyles, StyleXArray } from "@stylexjs/stylex"

type XStyle = StyleXArray<
  (null | undefined | CompiledStyles) | boolean | Readonly<[CompiledStyles, InlineStyles]>
>

const mobile = "@media (max-width: 768px)"

export const styles = stylex.create({
  layout: {
    backgroundColor: "rgb(var(--tbr-color-page))",
    color: "rgb(var(--tbr-color-text))",
    display: {
      default: "grid",
      [mobile]: "block",
    },
    gridTemplateColumns: "56px minmax(0, 1fr)",
    minHeight: "100vh",
    overflowX: "hidden",
  },
  rail: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderRightColor: {
      default: "rgb(var(--tbr-color-line))",
      [mobile]: "transparent",
    },
    borderRightStyle: "solid",
    borderRightWidth: {
      default: 1,
      [mobile]: 0,
    },
    borderTopColor: {
      default: "transparent",
      [mobile]: "rgb(var(--tbr-color-line))",
    },
    borderTopStyle: "solid",
    borderTopWidth: {
      default: 0,
      [mobile]: 1,
    },
    bottom: {
      default: "auto",
      [mobile]: 0,
    },
    boxShadow: "1px 0 0 rgb(var(--tbr-color-shadow) / 0.02)",
    display: "flex",
    flexDirection: {
      default: "column",
      [mobile]: "row",
    },
    gap: 6,
    height: {
      default: "100vh",
      [mobile]: 50,
    },
    justifyContent: {
      default: "flex-start",
      [mobile]: "space-around",
    },
    left: {
      default: "auto",
      [mobile]: 0,
    },
    paddingBlock: {
      default: 14,
      [mobile]: 6,
    },
    paddingInline: {
      default: 8,
      [mobile]: 12,
    },
    position: {
      default: "sticky",
      [mobile]: "fixed",
    },
    right: {
      default: "auto",
      [mobile]: 0,
    },
    top: {
      default: 0,
      [mobile]: "auto",
    },
    zIndex: "var(--tbr-z-sticky, 100)",
  },
  railLogo: {
    color: "rgb(var(--tbr-color-accent))",
    display: {
      default: "block",
      [mobile]: "none",
    },
    height: 36,
    marginBottom: 8,
    width: 36,
  },
  railGroups: {
    alignItems: "center",
    display: "flex",
    flexDirection: {
      default: "column",
      [mobile]: "row",
    },
    gap: 6,
  },
  railGroup: {
    position: "relative",
  },
  railButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: 6,
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: 13,
    height: 38,
    justifyContent: "center",
    position: "relative",
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "background-color, border-color, color, box-shadow",
    transitionTimingFunction: "var(--tbr-ease)",
    width: 38,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent-soft))",
      borderColor: "rgb(var(--tbr-color-accent))",
      color: "rgb(var(--tbr-color-accent))",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  railButtonActive: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderColor: "rgb(var(--tbr-color-accent))",
    boxShadow: "inset 0 1px 3px rgb(var(--tbr-color-shadow) / 0.1)",
    color: "rgb(var(--tbr-color-accent))",
  },
  groupIcon: {
    fontSize: 13,
    fontWeight: 650,
    lineHeight: 1,
  },
  groupShortcut: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-pill)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    display: {
      default: "block",
      [mobile]: "none",
    },
    fontFamily: "var(--tbr-font-mono)",
    fontSize: 9,
    height: 14,
    lineHeight: "12px",
    minWidth: 14,
    paddingInline: 3,
    pointerEvents: "none",
    position: "absolute",
    right: -4,
    top: -4,
  },
  groupTip: {
    backgroundColor: "rgb(var(--tbr-color-text))",
    borderRadius: 5,
    color: "rgb(var(--tbr-color-page))",
    display: {
      default: "block",
      [mobile]: "none",
    },
    fontSize: 11,
    left: 46,
    opacity: 0,
    paddingBlock: 4,
    paddingInline: 8,
    pointerEvents: "none",
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    whiteSpace: "nowrap",
    zIndex: 60,
  },
  placeholderWrap: {
    position: "relative",
  },
  placeholder: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderColor: "rgb(var(--tbr-color-accent))",
    color: "rgb(var(--tbr-color-accent))",
  },
  inlinePop: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    bottom: {
      default: "auto",
      [mobile]: 58,
    },
    boxShadow: "0 8px 24px rgb(var(--tbr-color-shadow) / 0.22)",
    display: "flex",
    gap: 8,
    justifyContent: {
      default: "flex-start",
      [mobile]: "center",
    },
    left: {
      default: 46,
      [mobile]: 12,
    },
    padding: 10,
    position: {
      default: "absolute",
      [mobile]: "fixed",
    },
    right: {
      default: "auto",
      [mobile]: 12,
    },
    top: {
      default: "50%",
      [mobile]: "auto",
    },
    transform: {
      default: "translateY(-50%)",
      [mobile]: "none",
    },
    width: {
      default: "max-content",
      [mobile]: "auto",
    },
    zIndex: 80,
  },
  inlineInput: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text))",
    fontFamily: "inherit",
    fontSize: 12,
    height: 30,
    outline: "none",
    paddingInline: 8,
    width: 150,
    ":focus": {
      borderColor: "rgb(var(--tbr-color-accent))",
      boxShadow: "0 0 0 3px rgb(var(--tbr-color-accent) / 0.08)",
    },
  },
  inlineHint: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "inline-flex",
    fontSize: 10,
    fontWeight: 500,
    gap: 4,
    whiteSpace: "nowrap",
  },
  inlineKbd: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: 4,
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    fontFamily: "inherit",
    fontSize: 9,
    paddingBlock: 1,
    paddingInline: 4,
  },
  divider: {
    backgroundColor: "rgb(var(--tbr-color-line))",
    height: {
      default: 1,
      [mobile]: 24,
    },
    marginBlock: {
      default: 4,
      [mobile]: 0,
    },
    marginInline: {
      default: 0,
      [mobile]: 4,
    },
    width: {
      default: 24,
      [mobile]: 1,
    },
  },
  spacer: {
    display: {
      default: "block",
      [mobile]: "none",
    },
    flex: 1,
  },
  layoutLabel: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minWidth: 0,
  },
  layoutName: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 12,
    fontWeight: 650,
    lineHeight: 1.2,
  },
  layoutDescription: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 10,
    lineHeight: 1.2,
    marginTop: 1,
  },
  groupMenu: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 12px 32px rgb(var(--tbr-color-shadow) / 0.22)",
    padding: 6,
    position: "fixed",
    width: 212,
    zIndex: "var(--tbr-z-dropdown, 200)",
  },
  menuItem: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-text))",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: 12,
    justifyContent: "space-between",
    minHeight: 32,
    paddingBlock: 7,
    paddingInline: 9,
    textAlign: "left",
    width: "100%",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
    },
    ":disabled": {
      backgroundColor: "transparent",
      color: "rgb(var(--tbr-color-text-subtle))",
      cursor: "default",
      opacity: 0.48,
    },
  },
  menuItemDanger: {
    color: "rgb(var(--tbr-color-danger))",
  },
  menuKbd: {
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: 4,
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    fontFamily: "inherit",
    fontSize: 10,
    paddingBlock: 1,
    paddingInline: 5,
  },
  menuSeparator: {
    backgroundColor: "rgb(var(--tbr-color-line))",
    height: 1,
    marginBlock: 5,
    marginInline: 4,
  },
  menuLabel: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 10,
    fontWeight: 650,
    paddingBlockEnd: 5,
    paddingBlockStart: 3,
    paddingInline: 8,
    textTransform: "uppercase",
  },
  menuIcons: {
    display: "grid",
    gap: 4,
    gridTemplateColumns: "repeat(7, 1fr)",
    paddingBlockEnd: 3,
    paddingInline: 4,
  },
  menuIcon: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 12,
    height: 24,
    justifyContent: "center",
    width: 24,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent-soft))",
      borderColor: "rgb(var(--tbr-color-accent))",
      color: "rgb(var(--tbr-color-accent))",
    },
  },
  menuIconActive: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderColor: "rgb(var(--tbr-color-accent))",
    color: "rgb(var(--tbr-color-accent))",
  },
  dashboardContent: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    marginInline: "auto",
    maxWidth: 1440,
    minWidth: 0,
    paddingBlockEnd: {
      default: 24,
      [mobile]: 66,
    },
    paddingBlockStart: {
      default: 24,
      [mobile]: 16,
    },
    paddingInline: {
      default: 32,
      [mobile]: 16,
    },
    width: "100%",
  },
  dashboardTopbar: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  greeting: {
    alignItems: {
      default: "center",
      [mobile]: "flex-start",
    },
    display: "flex",
    flexWrap: {
      default: "nowrap",
      [mobile]: "wrap",
    },
    fontSize: 13,
    fontWeight: 600,
    gap: 12,
    justifyContent: "space-between",
  },
  greetingTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontWeight: 600,
  },
  muted: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontWeight: 400,
  },
  greetingActions: {
    alignItems: "center",
    display: "flex",
    flexWrap: {
      default: "nowrap",
      [mobile]: "wrap",
    },
    gap: 6,
    justifyContent: {
      default: "flex-end",
      [mobile]: "flex-start",
    },
  },
  toolbarButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 11,
    fontWeight: 500,
    gap: 4,
    height: 28,
    justifyContent: "center",
    paddingInline: 10,
    whiteSpace: "nowrap",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  searchStage: {
    display: "flex",
    justifyContent: "center",
    marginBlockEnd: 4,
    marginBlockStart: 2,
    position: "relative",
    width: "100%",
  },
  searchInner: {
    maxWidth: 720,
    width: "min(100%, 720px)",
  },
  grid: {
    minWidth: 0,
  },
  gridContainer: {
    alignItems: "start",
    display: "grid",
    gap: 10,
    gridAutoRows: "auto",
    gridTemplateColumns: {
      default: "repeat(16, minmax(0, 1fr))",
      [mobile]: "minmax(0, 1fr)",
    },
  },
  emptyGroup: {
    alignItems: "center",
    appearance: "none",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    fontFamily: "inherit",
    fontSize: 14,
    gap: 8,
    gridColumn: "1 / -1",
    paddingBlock: 32,
    paddingInline: 24,
    textAlign: "center",
    ":hover": {
      opacity: 0.85,
    },
  },
  emptyIcon: {
    color: "rgb(var(--tbr-color-text-subtle))",
    marginBottom: 4,
    opacity: 0.5,
  },
  emptyText: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 14,
    fontWeight: 600,
  },
  emptyHint: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 13,
  },
  emptyAction: {
    color: "rgb(var(--tbr-color-accent))",
    fontWeight: 600,
  },
  focusShell: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    minHeight: "100vh",
    paddingBlockEnd: {
      default: 0,
      [mobile]: 66,
    },
    paddingBlockStart: "clamp(40px, 8vh, 80px)",
    paddingInline: {
      default: 0,
      [mobile]: 16,
    },
  },
  focusContent: {
    display: "flex",
    flexDirection: "column",
    gap: {
      default: 12,
      [mobile]: 18,
    },
    maxWidth: "clamp(680px, 90vw, 880px)",
    paddingBlock: {
      default: 24,
      [mobile]: 0,
    },
    paddingInline: {
      default: 32,
      [mobile]: 0,
    },
    width: "100%",
  },
  focusTopbar: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "flex",
    fontSize: 12,
    gap: {
      default: 0,
      [mobile]: 12,
    },
    justifyContent: "space-between",
  },
  focusGreeting: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    flexWrap: {
      default: "nowrap",
      [mobile]: "wrap",
    },
    fontSize: 13,
    fontWeight: 600,
    gap: 10,
    minWidth: 0,
  },
  focusMuted: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 11,
    fontWeight: 400,
  },
  focusActions: {
    alignItems: "center",
    display: "inline-flex",
    gap: 8,
  },
  focusControl: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    fontFamily: "inherit",
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "background-color, border-color, color",
    transitionTimingFunction: "var(--tbr-ease)",
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  focusIconButton: {
    alignItems: "center",
    borderRadius: "var(--tbr-radius-pill)",
    display: "inline-flex",
    height: 27,
    justifyContent: "center",
    width: 27,
    ":hover": {
      borderColor: "rgb(var(--tbr-color-accent))",
      color: "rgb(var(--tbr-color-text))",
    },
  },
  focusCommand: {
    alignItems: "center",
    borderRadius: "var(--tbr-radius-pill)",
    display: "inline-flex",
    fontSize: 11,
    gap: 5,
    justifyContent: "center",
    minWidth: {
      default: "auto",
      [mobile]: 136,
    },
    paddingBlock: 4,
    paddingInline: 10,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent-soft))",
      borderColor: "rgb(var(--tbr-color-accent))",
      color: "rgb(var(--tbr-color-accent))",
    },
  },
  focusKbd: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderRadius: "var(--tbr-radius-pill)",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 10,
    fontWeight: 650,
    height: 18,
    justifyContent: "center",
    minWidth: 31,
  },
  hero: {
    aspectRatio: "21 / 9",
  },
  heroRender: {
    height: "100%",
    overflow: "hidden",
  },
  focusEmpty: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "dashed",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 13,
    height: "100%",
    width: "100%",
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  satellites: {
    display: "grid",
    gap: {
      default: 8,
      [mobile]: 10,
    },
    gridTemplateColumns: {
      default: "repeat(4, minmax(0, 1fr))",
      [mobile]: "1fr",
    },
  },
  satellite: {
    alignItems: {
      default: "stretch",
      [mobile]: "center",
    },
    aspectRatio: {
      default: "3 / 2",
      [mobile]: "auto",
    },
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: 6,
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "flex",
    flexDirection: {
      default: "column",
      [mobile]: "row",
    },
    fontFamily: "inherit",
    minHeight: {
      default: 0,
      [mobile]: 58,
    },
    overflow: "hidden",
    padding: 12,
    position: "relative",
    transitionDuration: "var(--tbr-dur-normal)",
    transitionProperty: "background-color, border-color, box-shadow, transform",
    transitionTimingFunction: "var(--tbr-ease)",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
      boxShadow: "0 6px 16px rgb(var(--tbr-color-shadow) / 0.1)",
      transform: "translateY(-2px)",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  satelliteTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 13,
    fontWeight: 650,
    lineHeight: 1.25,
  },
  satelliteMeta: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 11,
    lineHeight: 1.2,
  },
})

export function className(...values: XStyle[]) {
  return stylex.attrs(...values).class
}
