import * as stylex from "@stylexjs/stylex"

export const styles = stylex.create({
  root: {
    color: "rgb(var(--tbr-color-text))",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    width: "100%",
  },
  // S：光感轨道 + 居中温度，四角为城市/状态/温度区间。
  // 1×1 卡片尺寸随网格列宽变化，字号与间距用容器查询单位跟随，避免小卡上文字挤压。
  // 注意：cqw 按查询容器的内容盒计算，若在此处加 padding，子元素的 cqw 会连带缩小。
  // 因此内边距交给唯一的常规流子元素 smallHead，绝对定位的轨道/温度/底栏各自带偏移。
  rootSmall: {
    backgroundColor:
      "color-mix(in srgb, rgb(var(--tbr-color-accent-soft)) 58%, rgb(var(--tbr-color-surface)))",
    borderRadius: "inherit",
    containerType: "inline-size",
    overflow: "hidden",
    position: "relative",
  },
  // M：左侧实况 + 右侧 3 小时
  // 设计稿给非 S 尺寸的卡片体统一留 9px 内缩，着色块在内缩之内
  rootMedium: {
    display: "grid",
    padding: 9,
  },
  mediumCard: {
    backgroundColor:
      "color-mix(in srgb, rgb(var(--tbr-color-accent-soft)) 44%, rgb(var(--tbr-color-surface)))",
    borderRadius: "var(--tbr-radius-control)",
    display: "grid",
    gap: 8,
    gridTemplateColumns: "minmax(70px, 0.82fr) minmax(0, 1.18fr)",
    minHeight: 0,
    minWidth: 0,
  },
  // L：实况 hero + 四项指标 + 5 小时
  rootLarge: {
    display: "grid",
    gap: 8,
    gridTemplateRows: "auto auto minmax(0, 1fr)",
    padding: 9,
  },
  // XL：实况摘要 + 逐小时面板 + 未来三天
  rootExtraLarge: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: "112px minmax(0, 1fr) 118px",
    padding: 9,
  },
  smallHead: {
    alignItems: "center",
    display: "flex",
    fontSize: "clamp(7px, 7cqw, 10px)",
    fontWeight: 700,
    gap: 6,
    justifyContent: "space-between",
    minWidth: 0,
    padding: "clamp(7px, 8cqw, 12px)",
  },
  smallLocation: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontWeight: 500,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  // 轨道环：外圈描边 + 内层浅色圆盘 + 右上高亮点
  smallOrbit: {
    borderColor: "color-mix(in srgb, rgb(var(--tbr-color-accent)) 30%, transparent)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    height: "min(66cqw, 82px)",
    left: "45%",
    position: "absolute",
    top: "49%",
    transform: "translate(-50%, -50%)",
    width: "min(66cqw, 82px)",
    "::before": {
      backgroundColor: "rgb(var(--tbr-color-surface))",
      borderRadius: "50%",
      boxShadow: "0 8px 24px color-mix(in srgb, rgb(var(--tbr-color-accent)) 20%, transparent)",
      content: "''",
      inset: "21%",
      position: "absolute",
    },
    "::after": {
      backgroundColor: "rgb(var(--tbr-color-accent))",
      borderRadius: "50%",
      boxShadow:
        "0 0 0 min(4cqw, 5px) color-mix(in srgb, rgb(var(--tbr-color-surface)) 72%, transparent)",
      content: "''",
      height: "min(8cqw, 9px)",
      position: "absolute",
      right: "4%",
      top: "18%",
      width: "min(8cqw, 9px)",
    },
  },
  smallTemp: {
    // 与设计稿一致：大号读数走等宽数字，避免温度跳动时宽度抖动
    fontFamily: "var(--tbr-font-mono)",
    fontSize: "clamp(15px, 22cqw, 28px)",
    fontVariantNumeric: "tabular-nums",
    fontWeight: 760,
    left: "50%",
    letterSpacing: "-0.06em",
    lineHeight: 1.1,
    position: "absolute",
    top: "50%",
    transform: "translate(-50%, -50%)",
  },
  smallFoot: {
    bottom: "clamp(6px, 7cqw, 11px)",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    fontSize: "clamp(6px, 6cqw, 9px)",
    justifyContent: "space-between",
    left: "clamp(7px, 8cqw, 12px)",
    position: "absolute",
    right: "clamp(7px, 8cqw, 12px)",
  },
  stack: { display: "grid", gap: 8, padding: 8 },
  now: { alignContent: "center", display: "grid", gap: 7, minWidth: 0 },
  nowMedium: { paddingBlock: 7, paddingInlineStart: 8 },
  nowExtraLarge: { alignContent: "start", gap: 9 },
  eyebrow: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    gap: 6,
    justifyContent: "space-between",
    lineHeight: 1,
    minWidth: 0,
  },
  eyebrowStart: { justifyContent: "flex-start" },
  city: {
    fontSize: 9,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  air: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderRadius: "var(--tbr-radius-pill)",
    color: "rgb(var(--tbr-color-accent))",
    display: "inline-flex",
    flexShrink: 0,
    fontSize: 8,
    fontWeight: 700,
    minHeight: 18,
    paddingInline: 6,
    whiteSpace: "nowrap",
  },
  nowLine: { alignItems: "center", display: "flex", gap: 8, minWidth: 0 },
  temp: {
    fontSize: 30,
    fontVariantNumeric: "tabular-nums",
    fontWeight: 720,
    letterSpacing: "-0.06em",
    lineHeight: 0.9,
  },
  tempMedium: { fontSize: 25 },
  copy: { display: "grid", gap: 2, minWidth: 0 },
  title: {
    fontSize: 11,
    lineHeight: 1.1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  muted: { color: "rgb(var(--tbr-color-text-subtle))", fontSize: 8, whiteSpace: "nowrap" },
  hero: {
    alignItems: "center",
    backgroundColor:
      "color-mix(in srgb, rgb(var(--tbr-color-accent-soft)) 48%, rgb(var(--tbr-color-surface)))",
    borderRadius: "var(--tbr-radius-control)",
    display: "flex",
    gap: 10,
    justifyContent: "space-between",
    minWidth: 0,
    paddingBlock: 9,
    paddingInline: 10,
  },
  summary: {
    alignContent: "space-between",
    backgroundColor:
      "color-mix(in srgb, rgb(var(--tbr-color-accent-soft)) 52%, rgb(var(--tbr-color-surface)))",
    borderRadius: "var(--tbr-radius-control)",
    display: "grid",
    gap: 10,
    minWidth: 0,
    padding: 11,
  },
  note: { color: "rgb(var(--tbr-color-text-muted))", fontSize: 8, lineHeight: 1.45, margin: 0 },
  metrics: {
    display: "grid",
    gap: 5,
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
  },
  metric: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 2,
    minWidth: 0,
    padding: 6,
  },
  metricLabel: { color: "rgb(var(--tbr-color-text-subtle))", fontSize: 8 },
  value: {
    fontSize: 10,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  forecastPanel: {
    display: "grid",
    gap: 8,
    gridTemplateRows: "auto minmax(0, 1fr)",
    minWidth: 0,
    paddingBlock: 3,
  },
  forecastHead: {
    alignItems: "center",
    display: "flex",
    gap: 8,
    justifyContent: "space-between",
  },
  forecastTitle: { fontSize: 10 },
  forecastMeta: { color: "rgb(var(--tbr-color-text-subtle))", fontSize: 8 },
  hours: { display: "grid", minHeight: 0, minWidth: 0 },
  hoursMedium: {
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    paddingBlock: 7,
    paddingInlineEnd: 5,
  },
  hoursFramed: {
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    overflow: "hidden",
  },
  hoursLarge: { gridTemplateColumns: "repeat(5, minmax(0, 1fr))" },
  hoursExtraLarge: { gridTemplateColumns: "repeat(6, minmax(0, 1fr))" },
  hour: {
    alignContent: "center",
    borderLeftColor: "rgb(var(--tbr-color-line))",
    borderLeftStyle: "solid",
    borderLeftWidth: 1,
    display: "grid",
    gap: 3,
    justifyItems: "center",
    minWidth: 0,
    textAlign: "center",
  },
  hourFirst: { borderLeftWidth: 0 },
  hourCompact: { gap: 2 },
  hourTime: { color: "rgb(var(--tbr-color-text-subtle))", fontSize: 8, whiteSpace: "nowrap" },
  hourTemp: { fontSize: 11, fontVariantNumeric: "tabular-nums", lineHeight: 1 },
  hourState: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 8,
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  dailyPanel: {
    borderLeftColor: "rgb(var(--tbr-color-line))",
    borderLeftStyle: "solid",
    borderLeftWidth: 1,
    display: "grid",
    gap: 5,
    gridTemplateRows: "auto repeat(3, minmax(0, 1fr))",
    minWidth: 0,
    paddingInlineStart: 11,
  },
  dailyTitle: { alignSelf: "center", fontSize: 10 },
  day: {
    alignItems: "center",
    display: "grid",
    fontSize: 8,
    gap: 5,
    gridTemplateColumns: "28px minmax(0, 1fr) auto",
    minWidth: 0,
  },
  dayLabel: { color: "rgb(var(--tbr-color-text-muted))" },
  dayState: {
    fontSize: 9,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  dayRange: {
    color: "rgb(var(--tbr-color-text))",
    fontStyle: "normal",
    fontVariantNumeric: "tabular-nums",
    whiteSpace: "nowrap",
  },
  expand: { height: "100%", minHeight: 0 },
  expandBody: {
    display: "grid",
    gap: 14,
    gridTemplateColumns: {
      default: "minmax(0, 1fr) 220px",
      "@media (max-width: 680px)": "1fr",
    },
    height: "100%",
    minHeight: 0,
    padding: 16,
  },
  main: { alignContent: "start", display: "grid", gap: 12, minWidth: 0 },
  side: {
    alignContent: "start",
    display: { default: "grid", "@media (max-width: 680px)": "none" },
    gap: 10,
  },
  nowPanel: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 10,
    gridTemplateColumns: "48px auto minmax(0, 1fr) auto",
    padding: 12,
  },
  icon: { color: "rgb(var(--tbr-color-accent))", display: "grid", placeItems: "center" },
  aqi: { alignItems: "end", display: "grid", gap: 2, justifyItems: "end" },
  panel: {
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    overflow: "hidden",
  },
  panelHead: {
    alignItems: "center",
    borderBottomColor: "rgb(var(--tbr-color-line))",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    fontSize: 11,
    justifyContent: "space-between",
    paddingBlock: 8,
    paddingInline: 10,
  },
  list: { display: "grid" },
  row: {
    alignItems: "center",
    borderBottomColor: "rgb(var(--tbr-color-line))",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 10,
    gridTemplateColumns: "72px minmax(0, 1fr) auto",
    minHeight: 40,
    paddingInline: 10,
  },
  rowText: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "inline-flex",
    fontSize: 11,
    gap: 5,
  },
  rowMeta: { color: "rgb(var(--tbr-color-text-subtle))", fontSize: 11, fontStyle: "normal" },
  advice: { gridTemplateColumns: "56px minmax(0, 1fr) auto" },
  sidePanel: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 8,
    padding: 10,
  },
  miniGrid: { display: "grid", gap: 6, gridTemplateColumns: "repeat(2, minmax(0, 1fr))" },
  mini: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderRadius: "var(--tbr-radius-control)",
    display: "grid",
    gap: 2,
    padding: 8,
  },
})
