import * as stylex from "@stylexjs/stylex"

export const styles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    fontSize: 12,
    height: "100%",
    minHeight: 0,
  },
  toolbar: {
    alignItems: "center",
    borderBottomColor: "rgb(var(--tbr-color-line) / 0.5)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexShrink: 0,
    gap: 4,
    paddingBlockEnd: 5,
    paddingBlockStart: 7,
    paddingInline: 10,
  },
  tab: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: "var(--tbr-radius-1)",
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 11,
    gap: 4,
    paddingBlock: 2,
    paddingInline: 8,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent) / 0.06)",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 1,
    },
  },
  active: {
    backgroundColor: "rgb(var(--tbr-color-accent) / 0.1)",
    color: "rgb(var(--tbr-color-accent))",
    fontWeight: 500,
  },
  badge: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-accent) / 0.15)",
    borderRadius: "var(--tbr-radius-pill)",
    color: "rgb(var(--tbr-color-accent))",
    display: "inline-flex",
    fontSize: 10,
    fontVariantNumeric: "tabular-nums",
    fontWeight: 600,
    height: 16,
    justifyContent: "center",
    minWidth: 16,
    paddingInline: 4,
  },
  spacer: {
    flex: 1,
  },
  outlineButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-1)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 11,
    gap: 3,
    paddingBlock: 2,
    paddingInline: 8,
    ":hover": {
      borderColor: "rgb(var(--tbr-color-accent))",
      color: "rgb(var(--tbr-color-accent))",
    },
  },
  list: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    paddingBlock: 4,
  },
  group: {
    marginBottom: 2,
  },
  groupHeader: {
    alignItems: "center",
    borderRadius: "var(--tbr-radius-1)",
    cursor: "pointer",
    display: "flex",
    gap: 4,
    paddingBlock: 4,
    paddingInline: 10,
    userSelect: "none",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent) / 0.04)",
    },
  },
  arrow: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    flexShrink: 0,
  },
  groupName: {
    color: "rgb(var(--tbr-color-text-secondary))",
    flex: 1,
    fontSize: 11,
    fontWeight: 600,
  },
  count: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderRadius: "var(--tbr-radius-pill)",
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 10,
    paddingBlock: 1,
    paddingInline: 5,
  },
  groupItems: {
    paddingLeft: 4,
  },
  item: {
    alignItems: "center",
    borderRadius: "var(--tbr-radius-1)",
    display: "flex",
    gap: 6,
    minHeight: 26,
    paddingBlock: 3,
    paddingLeft: 18,
    paddingRight: 10,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent) / 0.04)",
    },
  },
  done: {
    opacity: 0.55,
  },
  priorityDot: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    width: 10,
  },
  text: {
    color: "rgb(var(--tbr-color-text))",
    flex: 1,
    fontSize: 12,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  textDone: {
    color: "rgb(var(--tbr-color-text-muted))",
    textDecoration: "line-through",
  },
  due: {
    color: "rgb(var(--tbr-color-text-muted))",
    flexShrink: 0,
    fontSize: 10,
    fontVariantNumeric: "tabular-nums",
  },
  overdue: {
    color: "rgb(var(--tbr-color-danger))",
  },
  skeleton: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    paddingBlock: 8,
    paddingInline: 10,
  },
  expandRoot: {
    display: "flex",
    flexDirection: "column",
    fontSize: 13,
    height: "100%",
    minHeight: 0,
  },
  header: {
    alignItems: "center",
    borderBottomColor: "rgb(var(--tbr-color-line))",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    gap: 12,
    paddingBlock: 12,
    paddingInline: 16,
  },
  title: {
    flex: 1,
    fontSize: 16,
    fontWeight: 600,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-accent))",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-inverse))",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: 13,
    fontWeight: 500,
    gap: 4,
    paddingBlock: 6,
    paddingInline: 12,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent-hover))",
    },
  },
  tabs: {
    borderBottomColor: "rgb(var(--tbr-color-line))",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    gap: 4,
    paddingInline: 16,
  },
  filters: {
    alignItems: "center",
    display: "flex",
    gap: 6,
    paddingBlock: 8,
    paddingInline: 16,
  },
  toolButton: {
    backgroundColor: "transparent",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 11,
    paddingBlock: 5,
    paddingInline: 9,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      color: "rgb(var(--tbr-color-text))",
    },
  },
  tableHeader: {
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "grid",
    fontSize: 10,
    gap: 8,
    gridTemplateColumns: "36px minmax(180px, 1fr) 80px 90px 90px",
    paddingBlock: 6,
    paddingInline: 16,
  },
  expandList: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
  },
  expandRow: {
    alignItems: "center",
    borderBottomColor: "rgb(var(--tbr-color-line))",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 8,
    gridTemplateColumns: "36px minmax(180px, 1fr) 80px 90px 90px",
    minHeight: 42,
    paddingInline: 16,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
    },
  },
  cell: {
    minWidth: 0,
  },
  priorityTag: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 11,
  },
  priorityHigh: {
    color: "rgb(var(--tbr-color-danger))",
  },
  priorityMedium: {
    color: "rgb(var(--tbr-color-warning))",
  },
  priorityLow: {
    color: "rgb(var(--tbr-color-accent))",
  },
  assignee: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderRadius: "var(--tbr-radius-pill)",
    color: "rgb(var(--tbr-color-accent))",
    fontSize: 10,
    paddingBlock: 2,
    paddingInline: 7,
  },
  addRow: {
    paddingBlock: 8,
    paddingInline: 16,
  },
  addButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: 12,
    gap: 4,
    paddingBlock: 8,
    paddingInline: 16,
    ":hover": {
      color: "rgb(var(--tbr-color-accent))",
    },
  },
  board: {
    color: "rgb(var(--tbr-color-text-muted))",
    display: "grid",
    flex: 1,
    placeItems: "center",
  },
})
