import * as stylex from "@stylexjs/stylex"

export const styles = stylex.create({
  // 四个尺寸各是一套独立版式（S 进度环 / M 下一项 / L 时间轴 / XL 看板），
  // 只有外壳与勾选圈共用，其余不复用，跟设计稿一致。
  card: {
    borderRadius: "inherit",
    color: "rgb(var(--tbr-color-text))",
    // 查询容器放在外层：S 的 padding 自己用 cqw，容器若是同一元素则解析不到
    containerType: "inline-size",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    width: "100%",
  },
  // 设计稿全局 border-box；带边框的盒子不跟上就会宽出 2px
  hit: {
    appearance: "none",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    boxSizing: "border-box",
    color: "inherit",
    cursor: "pointer",
    fontFamily: "inherit",
    margin: 0,
    minHeight: 0,
    minWidth: 0,
    padding: 0,
    textAlign: "left",
  },
  check: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line-strong))",
    borderRadius: "var(--tbr-radius-pill)",
    borderStyle: "solid",
    borderWidth: 1,
    boxSizing: "border-box",
    display: "grid",
    flex: "0 0 auto",
    height: 14,
    placeItems: "center",
    width: 14,
  },
  checkDone: {
    backgroundColor: "rgb(var(--tbr-color-accent))",
    borderColor: "rgb(var(--tbr-color-accent))",
    boxShadow: "inset 0 0 0 3px rgb(var(--tbr-color-surface))",
  },
  // S：进度环 + 下一项，字号与内距按容器宽度缩放
  small: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderRadius: "inherit",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    justifyContent: "space-between",
    padding: "clamp(8px, 9cqw, 13px)",
  },
  smallHead: {
    alignItems: "center",
    display: "flex",
    fontSize: "clamp(6px, 7cqw, 10px)",
    fontWeight: 750,
    justifyContent: "space-between",
  },
  mono: {
    fontFamily: "var(--tbr-font-mono)",
    fontVariantNumeric: "tabular-nums",
  },
  // 45° 起笔 + 上右两边着色，是设计稿画进度环的方式
  smallRing: {
    alignSelf: "center",
    borderColor: "rgb(var(--tbr-color-accent-soft))",
    borderRadius: "50%",
    borderStyle: "solid",
    borderTopColor: "rgb(var(--tbr-color-accent))",
    borderRightColor: "rgb(var(--tbr-color-accent))",
    borderWidth: "clamp(4px, 5cqw, 7px)",
    boxSizing: "border-box",
    display: "grid",
    height: "clamp(38px, 45cqw, 58px)",
    placeItems: "center",
    position: "relative",
    transform: "rotate(45deg)",
    width: "clamp(38px, 45cqw, 58px)",
  },
  smallRingEmpty: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "color-mix(in srgb, rgb(var(--tbr-color-accent)) 42%, rgb(var(--tbr-color-line)))",
    borderStyle: "dashed",
    borderTopColor:
      "color-mix(in srgb, rgb(var(--tbr-color-accent)) 42%, rgb(var(--tbr-color-line)))",
    borderRightColor:
      "color-mix(in srgb, rgb(var(--tbr-color-accent)) 42%, rgb(var(--tbr-color-line)))",
    borderWidth: 1,
  },
  smallRingValue: {
    fontSize: "clamp(8px, 10cqw, 14px)",
    fontWeight: 760,
    transform: "rotate(-45deg)",
  },
  smallNext: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: "clamp(5px, 6cqw, 8px)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  // M：只展示下一项 + 进度条
  medium: {
    backgroundImage:
      "radial-gradient(circle at 8% 10%, color-mix(in srgb, rgb(var(--tbr-color-accent)) 13%, transparent), transparent 42%)",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderRadius: "inherit",
    display: "grid",
    gap: 6,
    gridTemplateRows: "auto minmax(0, 1fr) 3px",
    height: "100%",
    minHeight: 0,
    paddingBlock: "8px 7px",
    paddingInline: 9,
  },
  nextHead: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "flex",
    fontSize: 7,
    fontWeight: 700,
    gap: 6,
    justifyContent: "space-between",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
  },
  nextHeadCount: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 8,
    letterSpacing: 0,
  },
  nextTask: {
    alignItems: "center",
    backgroundColor:
      "color-mix(in srgb, rgb(var(--tbr-color-accent)) 6%, rgb(var(--tbr-color-surface)))",
    borderColor: "color-mix(in srgb, rgb(var(--tbr-color-accent)) 22%, rgb(var(--tbr-color-line)))",
    borderRadius: 7,
    borderStyle: "solid",
    borderWidth: 1,
    boxSizing: "border-box",
    display: "grid",
    gap: 7,
    gridTemplateColumns: "14px minmax(0, 1fr) auto",
    minWidth: 0,
    paddingBlock: 5,
    paddingInline: 7,
  },
  nextTaskEmpty: {
    backgroundColor:
      "color-mix(in srgb, rgb(var(--tbr-color-accent)) 3%, rgb(var(--tbr-color-surface)))",
    borderStyle: "dashed",
  },
  nextCopy: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
  },
  nextTitle: {
    fontSize: 9,
    lineHeight: 1.15,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  nextMeta: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 7,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  nextArrow: {
    color: "rgb(var(--tbr-color-accent))",
    fontSize: 12,
  },
  nextProgress: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderRadius: "var(--tbr-radius-pill)",
    overflow: "hidden",
  },
  nextProgressFill: {
    backgroundColor: "rgb(var(--tbr-color-accent))",
    borderRadius: "inherit",
    display: "block",
    height: "100%",
  },
  // L：时间轴。左侧竖线是独立元素而不是伪元素，空态直接不渲染
  large: {
    backgroundImage:
      "linear-gradient(155deg, color-mix(in srgb, rgb(var(--tbr-color-accent)) 7%, rgb(var(--tbr-color-surface))), rgb(var(--tbr-color-surface)) 48%)",
    borderRadius: "inherit",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    padding: 9,
  },
  timelineHead: {
    alignItems: "center",
    display: "flex",
    gap: 8,
    justifyContent: "space-between",
    marginBottom: 5,
  },
  timelineTitle: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
  },
  timelineKicker: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 8,
    fontWeight: 700,
    letterSpacing: "0.1em",
  },
  timelineHeading: {
    fontSize: 14,
    lineHeight: 1.1,
  },
  timelineRing: {
    backgroundImage:
      "conic-gradient(rgb(var(--tbr-color-accent)) var(--todo-progress, 0%), rgb(var(--tbr-color-surface-soft)) 0)",
    borderRadius: "50%",
    boxSizing: "border-box",
    display: "grid",
    flex: "0 0 auto",
    height: 36,
    placeItems: "center",
    width: 36,
    "::before": {
      backgroundColor: "rgb(var(--tbr-color-surface))",
      borderRadius: "50%",
      content: "",
      gridArea: "1 / 1",
      height: 28,
      width: 28,
    },
  },
  timelineRingEmpty: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    backgroundImage: "none",
    borderColor: "color-mix(in srgb, rgb(var(--tbr-color-accent)) 42%, rgb(var(--tbr-color-line)))",
    borderStyle: "dashed",
    borderWidth: 1,
  },
  timelineRingValue: {
    fontSize: 8,
    gridArea: "1 / 1",
    zIndex: 1,
  },
  tab: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: "var(--tbr-radius-1)",
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 11,
    gap: 4,
    paddingBlock: 2,
    paddingInline: 8,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent) / 0.06)",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 1,
    },
  },
  active: {
    backgroundColor: "rgb(var(--tbr-color-accent) / 0.1)",
    color: "rgb(var(--tbr-color-accent))",
    fontWeight: 500,
  },
  badge: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-accent) / 0.15)",
    borderRadius: "var(--tbr-radius-pill)",
    color: "rgb(var(--tbr-color-accent))",
    display: "inline-flex",
    fontSize: 10,
    fontVariantNumeric: "tabular-nums",
    fontWeight: 600,
    height: 16,
    justifyContent: "center",
    minWidth: 16,
    paddingInline: 4,
  },
  spacer: {
    flex: 1,
  },
  timelineList: {
    alignContent: "start",
    display: "grid",
    flex: 1,
    gap: 3,
    minHeight: 0,
    overflow: "hidden",
    position: "relative",
  },
  timelineAxis: {
    backgroundColor: "rgb(var(--tbr-color-line))",
    bottom: 14,
    left: 35,
    position: "absolute",
    top: 14,
    width: 1,
  },
  timelineRow: {
    alignItems: "center",
    borderRadius: 7,
    display: "grid",
    gap: 4,
    gridTemplateColumns: "27px 9px minmax(0, 1fr) auto",
    minHeight: 28,
    minWidth: 0,
    paddingBlock: 2,
    paddingLeft: 0,
    paddingRight: 4,
    position: "relative",
    width: "100%",
    zIndex: 1,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
    },
  },
  timelineTime: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 8,
    textAlign: "right",
  },
  timelineNode: {
    backgroundColor: "rgb(var(--tbr-color-accent))",
    borderRadius: "50%",
    boxShadow: "0 0 0 1px rgb(var(--tbr-color-accent))",
    height: 7,
    width: 7,
  },
  timelineNodeDone: {
    backgroundColor: "rgb(var(--tbr-color-text-subtle))",
    boxShadow: "0 0 0 1px rgb(var(--tbr-color-text-subtle))",
  },
  timelineText: {
    fontSize: 10,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  timelineTextDone: {
    color: "rgb(var(--tbr-color-text-subtle))",
    textDecoration: "line-through",
  },
  timelineTag: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderRadius: "var(--tbr-radius-1)",
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 6.5,
    paddingBlock: 1,
    paddingInline: 3,
  },
  timelineEmpty: {
    alignItems: "center",
    backgroundColor:
      "color-mix(in srgb, rgb(var(--tbr-color-accent)) 3%, rgb(var(--tbr-color-surface)))",
    borderColor: "color-mix(in srgb, rgb(var(--tbr-color-accent)) 38%, rgb(var(--tbr-color-line)))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "dashed",
    borderWidth: 1,
    display: "grid",
    flex: 1,
    fontSize: 9,
    fontWeight: 600,
    gap: 8,
    gridTemplateColumns: "minmax(0, 1fr) auto",
    lineHeight: 1.2,
    minHeight: 0,
    padding: 10,
  },
  timelineEmptyPlus: {
    color: "rgb(var(--tbr-color-accent))",
    fontSize: 13,
  },
  timelineFoot: {
    borderTopColor: "rgb(var(--tbr-color-line))",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "flex",
    fontSize: 7,
    gap: 6,
    justifyContent: "space-between",
    marginTop: 4,
    paddingTop: 4,
  },
  timelineFootLead: {
    flex: "0 0 auto",
  },
  timelineFootTail: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  group: {
    marginBottom: 2,
  },
  groupHeader: {
    alignItems: "center",
    borderRadius: "var(--tbr-radius-1)",
    cursor: "pointer",
    display: "flex",
    gap: 4,
    paddingBlock: 4,
    paddingInline: 10,
    userSelect: "none",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent) / 0.04)",
    },
  },
  arrow: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    flexShrink: 0,
  },
  groupName: {
    color: "rgb(var(--tbr-color-text-secondary))",
    flex: 1,
    fontSize: 11,
    fontWeight: 600,
  },
  count: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderRadius: "var(--tbr-radius-pill)",
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 10,
    paddingBlock: 1,
    paddingInline: 5,
  },
  done: {
    opacity: 0.55,
  },
  textDone: {
    color: "rgb(var(--tbr-color-text-muted))",
    textDecoration: "line-through",
  },
  overdue: {
    color: "rgb(var(--tbr-color-danger))",
  },
  // XL：两列看板
  extraLarge: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderRadius: "inherit",
    display: "grid",
    gap: 9,
    gridTemplateRows: "auto minmax(0, 1fr)",
    height: "100%",
    minHeight: 0,
    padding: 12,
  },
  boardHead: {
    alignItems: "center",
    display: "flex",
    gap: 12,
    justifyContent: "space-between",
  },
  boardTitle: {
    alignItems: "baseline",
    display: "flex",
    gap: 7,
  },
  boardHeading: {
    fontSize: 13,
  },
  boardKicker: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 8,
    letterSpacing: "0.08em",
  },
  boardSummary: {
    display: "flex",
    gap: 5,
  },
  boardChip: {
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-pill)",
    borderStyle: "solid",
    borderWidth: 1,
    boxSizing: "border-box",
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 8,
    paddingBlock: 3,
    paddingInline: 6,
  },
  boardColumns: {
    display: "grid",
    gap: 8,
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    minHeight: 0,
  },
  boardColumn: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    minHeight: 0,
    minWidth: 0,
    padding: 8,
  },
  boardColumnHead: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    fontSize: 8,
    fontWeight: 650,
    justifyContent: "space-between",
  },
  boardStack: {
    alignContent: "start",
    display: "grid",
    gap: 5,
    minHeight: 0,
    overflow: "hidden",
  },
  boardTask: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: 7,
    borderStyle: "solid",
    borderWidth: 1,
    boxSizing: "border-box",
    display: "grid",
    gap: 7,
    gridTemplateColumns: "14px minmax(0, 1fr) auto",
    minWidth: 0,
    padding: 7,
    width: "100%",
    ":hover": {
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
  },
  boardTaskText: {
    fontSize: 9,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  boardTaskTextDone: {
    color: "rgb(var(--tbr-color-text-subtle))",
    textDecoration: "line-through",
  },
  boardTaskDue: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 7,
    fontStyle: "normal",
  },
  boardEmpty: {
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: 7,
    borderStyle: "dashed",
    borderWidth: 1,
    boxSizing: "border-box",
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "grid",
    fontSize: 8,
    minHeight: 42,
    placeItems: "center",
  },
  boardEmptyAction: {
    borderColor: "color-mix(in srgb, rgb(var(--tbr-color-accent)) 38%, rgb(var(--tbr-color-line)))",
    color: "rgb(var(--tbr-color-accent))",
    width: "100%",
  },
  expandRoot: {
    display: "flex",
    flexDirection: "column",
    fontSize: 13,
    height: "100%",
    minHeight: 0,
  },
  header: {
    alignItems: "center",
    borderBottomColor: "rgb(var(--tbr-color-line))",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    gap: 12,
    paddingBlock: 12,
    paddingInline: 16,
  },
  title: {
    flex: 1,
    fontSize: 16,
    fontWeight: 600,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-accent))",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-inverse))",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: 13,
    fontWeight: 500,
    gap: 4,
    paddingBlock: 6,
    paddingInline: 12,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent-hover))",
    },
  },
  tabs: {
    borderBottomColor: "rgb(var(--tbr-color-line))",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    gap: 4,
    paddingInline: 16,
  },
  filters: {
    alignItems: "center",
    display: "flex",
    gap: 6,
    paddingBlock: 8,
    paddingInline: 16,
  },
  toolButton: {
    backgroundColor: "transparent",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 11,
    paddingBlock: 5,
    paddingInline: 9,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      color: "rgb(var(--tbr-color-text))",
    },
  },
  tableHeader: {
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "grid",
    fontSize: 10,
    gap: 8,
    gridTemplateColumns: "36px minmax(180px, 1fr) 80px 90px 90px",
    paddingBlock: 6,
    paddingInline: 16,
  },
  expandList: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
  },
  expandRow: {
    alignItems: "center",
    borderBottomColor: "rgb(var(--tbr-color-line))",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 8,
    gridTemplateColumns: "36px minmax(180px, 1fr) 80px 90px 90px",
    minHeight: 42,
    paddingInline: 16,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
    },
  },
  cell: {
    minWidth: 0,
  },
  priorityTag: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 11,
  },
  priorityHigh: {
    color: "rgb(var(--tbr-color-danger))",
  },
  priorityMedium: {
    color: "rgb(var(--tbr-color-warning))",
  },
  priorityLow: {
    color: "rgb(var(--tbr-color-accent))",
  },
  assignee: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderRadius: "var(--tbr-radius-pill)",
    color: "rgb(var(--tbr-color-accent))",
    fontSize: 10,
    paddingBlock: 2,
    paddingInline: 7,
  },
  addRow: {
    paddingBlock: 8,
    paddingInline: 16,
  },
  addButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: 12,
    gap: 4,
    paddingBlock: 8,
    paddingInline: 16,
    ":hover": {
      color: "rgb(var(--tbr-color-accent))",
    },
  },
  board: {
    color: "rgb(var(--tbr-color-text-muted))",
    display: "grid",
    flex: 1,
    placeItems: "center",
  },
})
