import * as stylex from "@stylexjs/stylex"

export const styles = stylex.create({
  // Card variants
  card: {
    width: "100%",
    height: "100%",
    minWidth: 0,
    minHeight: 0,
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr) auto",
    gap: 8,
    padding: 10,
    border: "1px solid rgb(var(--tbr-color-line))",
    borderRadius: 9,
    background: "rgb(var(--tbr-color-surface))",
    overflow: "hidden",
    containerType: "inline-size",
    cursor: "pointer",
  },
  cardHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 7,
  },
  kicker: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 7,
    fontWeight: 750,
    letterSpacing: "0.11em",
    textTransform: "uppercase",
  },
  count: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 8,
  },
  cardList: {
    minHeight: 0,
    display: "grid",
    alignContent: "start",
    gap: 5,
    overflow: "hidden",
  },
  cardItem: {
    minWidth: 0,
    display: "grid",
    gap: 2,
    padding: "6px 7px",
    border: "1px solid rgb(var(--tbr-color-line))",
    borderRadius: 7,
    background: "rgb(var(--tbr-color-surface-soft))",
  },
  cardItemTitle: {
    overflow: "hidden",
    color: "rgb(var(--tbr-color-text))",
    fontSize: 9,
    fontWeight: 620,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  cardItemPreview: {
    minWidth: 0,
    overflow: "hidden",
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 8,
    lineHeight: 1.4,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
  },
  cardEmpty: {
    display: "grid",
    placeItems: "center",
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 9,
    textAlign: "center",
  },
  cardFoot: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 7,
  },
  cardTime: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 7,
  },
  viewAll: {
    display: "inline-flex",
    alignItems: "center",
    gap: 2,
    padding: 0,
    borderStyle: "none",
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 7,
    fontWeight: 650,
    lineHeight: 1,
    cursor: "pointer",
    ":hover": {
      color: "rgb(var(--tbr-color-accent))",
    },
  },
  addButton: {
    display: "grid",
    placeItems: "center",
    width: 22,
    height: 22,
    flex: "0 0 auto",
    border:
      "1px solid color-mix(in srgb, rgb(var(--tbr-color-accent)) 30%, rgb(var(--tbr-color-line)))",
    borderRadius: 6,
    background:
      "color-mix(in srgb, rgb(var(--tbr-color-accent)) 8%, rgb(var(--tbr-color-surface)))",
    color: "rgb(var(--tbr-color-accent))",
    cursor: "pointer",
    ":hover": {
      background: "rgb(var(--tbr-color-accent))",
      color: "rgb(var(--tbr-color-accent-text))",
    },
  },

  // Expand two-column layout
  root: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    display: "flex",
    flex: 1,
    flexDirection: {
      default: "row",
      "@media (max-width: 720px)": "column",
    },
    minHeight: {
      default: "min(520px, calc(100vh - 116px))",
      "@media (max-width: 720px)": 0,
    },
  },
  side: {
    backgroundColor: "rgb(var(--tbr-color-page))",
    borderBottomColor: {
      default: "transparent",
      "@media (max-width: 720px)": "rgb(var(--tbr-color-line))",
    },
    borderBottomStyle: "solid",
    borderBottomWidth: {
      default: 0,
      "@media (max-width: 720px)": 1,
    },
    borderRightColor: "rgb(var(--tbr-color-line))",
    borderRightStyle: "solid",
    borderRightWidth: {
      default: 1,
      "@media (max-width: 720px)": 0,
    },
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    maxHeight: {
      default: "none",
      "@media (max-width: 720px)": 280,
    },
    width: {
      default: 248,
      "@media (max-width: 720px)": "100%",
    },
  },
  sideHeader: {
    alignItems: "center",
    display: "flex",
    gap: 8,
    justifyContent: "space-between",
    paddingBlock: 10,
    paddingInline: 10,
  },
  sideTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 14,
    fontWeight: 650,
  },
  newButton: {
    flexShrink: 0,
  },
  sideSearch: {
    paddingBlockEnd: 6,
    paddingInline: 10,
  },
  sideList: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    paddingBlockEnd: 10,
    paddingInline: 10,
  },
  docItem: {
    borderColor: "transparent",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    marginBottom: 2,
    position: "relative",
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "background-color, border-color",
    transitionTimingFunction: "var(--tbr-ease)",
    width: "100%",
    backgroundColor: "transparent",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
  },
  docItemActive: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderColor: "rgb(var(--tbr-color-accent))",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent-soft))",
      borderColor: "rgb(var(--tbr-color-accent))",
    },
  },
  docItemMain: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "inherit",
    cursor: "pointer",
    display: "grid",
    fontFamily: "inherit",
    gap: 3,
    paddingBlock: 8,
    paddingInline: 10,
    textAlign: "left",
    width: "100%",
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: -2,
    },
  },
  docItemActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    opacity: 0,
    pointerEvents: "none",
    position: "absolute",
    right: 4,
    top: 4,
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "opacity",
    transitionTimingFunction: "var(--tbr-ease)",
    ":focus-within": {
      opacity: 1,
      pointerEvents: "auto",
    },
  },
  docItemActionsVisible: {
    opacity: 1,
    pointerEvents: "auto",
  },
  docItemTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 13,
    fontWeight: 580,
    lineHeight: 1.35,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  docItemTitleActive: {
    color: "rgb(var(--tbr-color-accent))",
  },
  docItemPreview: {
    color: "rgb(var(--tbr-color-text-muted))",
    display: "-webkit-box",
    fontSize: 12,
    lineHeight: 1.4,
    overflow: "hidden",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 1,
    wordBreak: "break-word",
  },
  docItemTime: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 11,
  },
  sideEmpty: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 12,
    paddingBlock: 16,
    paddingInline: 10,
    textAlign: "center",
  },
  main: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minWidth: 0,
    overflow: "hidden",
  },
  editorHeader: {
    alignItems: "center",
    borderBottomColor: "rgb(var(--tbr-color-line))",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    gap: 8,
    justifyContent: "space-between",
    paddingBlock: 8,
    paddingInline: 12,
  },
  titleInput: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "rgb(var(--tbr-color-text))",
    flex: 1,
    fontFamily: "inherit",
    fontSize: 18,
    fontWeight: 650,
    minWidth: 0,
    outline: "none",
    paddingBlock: 2,
    "::placeholder": {
      color: "rgb(var(--tbr-color-text-subtle))",
    },
  },
  headerActions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: 4,
  },
  savedHint: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 11,
    marginRight: 4,
  },
  editorBody: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
  },
  editor: {
    height: "100%",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: 0,
    ":focus-within": {
      borderColor: "transparent",
      boxShadow: "none",
    },
  },
  editorContent: {
    minHeight: "100%",
  },
  emptyMain: {
    alignItems: "center",
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: 8,
    justifyContent: "center",
    paddingInline: 24,
    textAlign: "center",
  },
  emptyIcon: {
    color: "rgb(var(--tbr-color-text-subtle))",
    opacity: 0.4,
  },
  emptyTitle: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 15,
    fontWeight: 560,
  },
  emptyHint: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 13,
  },
})
