import * as stylex from "@stylexjs/stylex"

const mobile = "@media (max-width: 560px)"

const interactiveSurface = {
  backgroundColor: "rgb(var(--tbr-color-surface-soft))",
  borderColor: "rgb(var(--tbr-color-line))",
  borderRadius: 6,
  borderStyle: "solid",
  borderWidth: 1,
}

export const styles = stylex.create({
  searchRoot: {
    maxWidth: 720,
    position: "relative",
    width: "100%",
  },
  searchBar: {
    alignItems: "center",
    backgroundColor:
      "color-mix(in srgb, rgb(var(--tbr-color-surface)) 92%, rgb(var(--tbr-color-page)))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow:
      "0 2px 8px rgb(var(--tbr-color-shadow) / 0.04), inset 0 1px 0 rgb(var(--tbr-color-surface) / 0.72)",
    display: "flex",
    gap: 10,
    height: 46,
    paddingInline: 12,
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "background-color, border-color, box-shadow",
    transitionTimingFunction: "var(--tbr-ease)",
    ":hover": {
      backgroundColor:
        "color-mix(in srgb, rgb(var(--tbr-color-surface)) 96%, rgb(var(--tbr-color-page)))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
    ":focus-within": {
      borderColor:
        "color-mix(in srgb, rgb(var(--tbr-color-accent)) 34%, rgb(var(--tbr-color-line)))",
      boxShadow:
        "0 0 0 3px rgb(var(--tbr-color-accent) / 0.12), inset 0 1px 0 rgb(var(--tbr-color-surface) / 0.72)",
    },
  },
  searchProvider: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    position: "relative",
  },
  searchProviderButton: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-pill)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 11,
    fontWeight: 550,
    gap: 5,
    height: 24,
    paddingInlineEnd: 7,
    paddingInlineStart: 6,
    whiteSpace: "nowrap",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  searchProviderButtonFocused: {
    borderColor: "color-mix(in srgb, rgb(var(--tbr-color-accent)) 18%, rgb(var(--tbr-color-line)))",
    color: "rgb(var(--tbr-color-text))",
  },
  searchProviderDot: {
    backgroundColor: "rgb(var(--tbr-color-accent))",
    borderRadius: "50%",
    height: 6,
    width: 6,
  },
  searchProviderLabel: {
    maxWidth: 120,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  searchProviderCaret: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "inline-flex",
    opacity: 0.58,
  },
  searchProviderDropdown: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 4px 16px rgb(var(--tbr-color-shadow) / 0.08)",
    left: 0,
    minWidth: 160,
    overflow: "hidden",
    position: "absolute",
    top: "calc(100% + 4px)",
    zIndex: 20,
  },
  searchProviderOption: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: 0,
    color: "rgb(var(--tbr-color-text))",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: 12,
    fontWeight: 400,
    gap: 8,
    height: "auto",
    justifyContent: "flex-start",
    lineHeight: 1.4,
    paddingBlock: 7,
    paddingInline: 12,
    textAlign: "left",
    width: "100%",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
    },
  },
  selected: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    color: "rgb(var(--tbr-color-accent))",
    fontWeight: 600,
  },
  searchCheck: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-accent))",
    display: "inline-flex",
    width: 14,
  },
  searchDivider: {
    backgroundColor: "rgb(var(--tbr-color-line))",
    flexShrink: 0,
    height: 18,
    width: 1,
  },
  searchDividerFocused: {
    backgroundColor:
      "color-mix(in srgb, rgb(var(--tbr-color-accent)) 18%, rgb(var(--tbr-color-line)))",
  },
  searchKbd: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "inline-flex",
    flexShrink: 0,
    fontFamily: "var(--tbr-font-mono)",
    fontSize: 10,
    height: 18,
    justifyContent: "center",
    opacity: 0.68,
    paddingInline: 5,
  },
  searchKbdFocused: {
    opacity: 0.35,
    transform: "translateX(-1px)",
  },
  // 搜索框内的输入框在原型里透明无边框、撑满剩余空间，避免出现「盒中盒」。
  searchField: {
    backgroundColor: "transparent",
    borderWidth: 0,
    borderRadius: 0,
    boxShadow: "none",
    flex: 1,
    fontSize: 13.5,
    height: "100%",
    minWidth: 0,
    paddingBlock: 0,
    paddingInline: 0,
    ":hover": {
      borderWidth: 0,
    },
    ":focus": {
      borderWidth: 0,
      boxShadow: "none",
      outlineStyle: "none",
    },
    ":focus-visible": {
      boxShadow: "none",
      outlineStyle: "none",
    },
  },
  searchInput: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    boxShadow: "none",
    color: "rgb(var(--tbr-color-text))",
    fontSize: 13.5,
    height: "100%",
    minWidth: 0,
    paddingInline: 0,
    ":focus": {
      borderColor: "transparent",
      boxShadow: "none",
      outline: "none",
    },
    "::placeholder": {
      color: "rgb(var(--tbr-color-text-subtle))",
    },
  },
  searchState: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 11,
    marginTop: 5,
    paddingInline: 2,
  },
  searchSuggestions: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 4px 20px rgb(var(--tbr-color-shadow) / 0.08)",
    left: 0,
    position: "absolute",
    right: 0,
    top: "calc(100% + 4px)",
    zIndex: 20,
  },
  panelStack: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  group: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    display: "grid",
    gap: 8,
    padding: 0,
  },
  groupTitle: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text))",
    display: "flex",
    fontSize: 11,
    fontWeight: 650,
    gap: 8,
    justifyContent: "space-between",
    lineHeight: 1.25,
    minHeight: 22,
    paddingInline: 2,
  },
  groupTitleMeta: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 10,
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowMeta: {
    color: "rgb(var(--tbr-color-text-muted))",
    flexShrink: 0,
    fontSize: 11,
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  rangeControl: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "grid",
    fontSize: 11,
    fontWeight: 600,
    gap: 8,
    gridTemplateColumns: "minmax(92px, 1fr) 42px",
    minWidth: 170,
    width: {
      default: "auto",
      [mobile]: "100%",
    },
  },
  checkList: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    justifyContent: {
      default: "flex-end",
      [mobile]: "flex-start",
    },
    minWidth: 220,
    width: {
      default: "auto",
      [mobile]: "100%",
    },
  },
  checkChip: {
    ...interactiveSurface,
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "inline-flex",
    height: 28,
    paddingInline: 8,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent-soft))",
      borderColor: "rgb(var(--tbr-color-accent))",
      color: "rgb(var(--tbr-color-text))",
    },
  },
  swatchRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    justifyContent: {
      default: "flex-end",
      [mobile]: "flex-start",
    },
  },
  swatch: {
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    cursor: "pointer",
    height: 28,
    padding: 0,
    width: 28,
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  stepper: {
    ...interactiveSurface,
    alignItems: "center",
    display: "inline-flex",
    height: 30,
    overflow: "hidden",
  },
  keybind: {
    ...interactiveSurface,
    alignItems: "center",
    display: "inline-flex",
    gap: 5,
    height: 30,
    paddingInline: 8,
  },
  inlineActions: {
    alignItems: "center",
    display: "inline-flex",
    gap: 7,
    justifyContent: {
      default: "flex-end",
      [mobile]: "flex-start",
    },
    minWidth: 0,
    width: {
      default: "auto",
      [mobile]: "100%",
    },
  },
  wideInlineActions: {
    width: {
      default: 244,
      [mobile]: "100%",
    },
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  listItem: {
    ...interactiveSurface,
    alignItems: "center",
    display: "grid",
    gap: 10,
    gridTemplateColumns: {
      default: "minmax(0, 1fr) auto",
      [mobile]: "minmax(0, 1fr)",
    },
    minHeight: 42,
    paddingBlock: 9,
    paddingInline: 10,
  },
  listName: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 12,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  listNameActive: {
    color: "rgb(var(--tbr-color-text))",
    fontWeight: 650,
  },
  successText: {
    color: "rgb(var(--tbr-color-success))",
    fontSize: 12,
  },
  warningList: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 12,
    margin: 0,
    paddingLeft: 18,
  },
  providerList: {
    display: "flex",
    flexDirection: "column",
    gap: 7,
  },
  // 经 xstyle 传入 ListRow，与 ListRow.root 在同一次 stylex.attrs() 里合并。
  // 走 class 传入时两边的 padding / minHeight / borderRadius 由样式表规则顺序决定胜负，不可控。
  providerRow: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: 7,
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 10,
    gridTemplateColumns: {
      default: "minmax(0, 1fr) auto",
      [mobile]: "minmax(0, 1fr)",
    },
    minHeight: "auto",
    paddingBlock: 8,
    paddingInline: 8,
    width: "100%",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
    },
  },
  // ListRow.root 的 :hover 是独立 key，选中行 hover 时会把 accent-soft 盖成灰色，这里钉住。
  providerRowSelected: {
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    },
  },
  disabled: {
    opacity: 0.58,
  },
  // 覆盖 Button 基础样式的泄漏项：buttonBase 的 justifyContent: center 会把内容簇整体居中，
  // 每行簇宽不同（Google / DuckDuckGo）导致标题左缘参差；buttonMd 的 paddingInline: 12 在
  // StyleX 里以 longhand 胜过这里的 padding 简写；height: 36 与行高叠加把行撑高；
  // lineHeight: 1 让 CJK 字形光学偏下。全部显式声明。
  providerMain: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "inherit",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontWeight: "inherit",
    gap: 10,
    height: "auto",
    justifyContent: "flex-start",
    lineHeight: "normal",
    minWidth: 0,
    paddingBlock: 0,
    paddingInline: 0,
    textAlign: "left",
    width: "100%",
    ":disabled": {
      cursor: "not-allowed",
      // 行上已有 styles.disabled 的 0.58；Button 的 :disabled 0.5 会叠乘到约 0.29。
      opacity: 1,
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  // 设计稿把类型标签放在行尾 meta 区（.field-note），与开关同侧，标题左缘因此对齐。
  providerKind: {
    color: "rgb(var(--tbr-color-text-subtle))",
    flexShrink: 0,
    fontSize: 10,
    lineHeight: 1.3,
    whiteSpace: "nowrap",
  },
  providerText: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
  },
  providerTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 12,
    fontWeight: 650,
    lineHeight: 1.25,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  providerAlias: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 11,
    fontWeight: 400,
    lineHeight: 1.3,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  // Check 图标与「当前」需要 flex 居中，靠基线对齐会错位；minWidth 保证各行开关纵向对齐。
  providerState: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-accent))",
    display: "inline-flex",
    fontSize: 11,
    fontWeight: 600,
    gap: 3,
    justifyContent: "flex-end",
    minWidth: 42,
    whiteSpace: "nowrap",
  },
  pluginHelp: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 11,
    lineHeight: 1.35,
    margin: 0,
  },
  pluginCard: {
    ...interactiveSurface,
    alignItems: "center",
    display: "grid",
    gap: 10,
    gridTemplateColumns: {
      default: "minmax(0, 1fr) auto",
      [mobile]: "minmax(0, 1fr)",
    },
    minHeight: 42,
    minWidth: 0,
    paddingBlock: 9,
    paddingInline: 10,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
  },
  pluginMain: {
    minWidth: 0,
  },
  pluginName: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 12,
    fontWeight: 650,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  pluginId: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontFamily: "var(--tbr-font-mono)",
    fontSize: 10,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  pluginMeta: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 10,
    lineHeight: 1.35,
    marginTop: 2,
  },
  pluginControls: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    flexWrap: "wrap",
    gap: 7,
    justifyContent: {
      default: "flex-end",
      [mobile]: "flex-start",
    },
  },
  pluginVersion: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 10,
    whiteSpace: "nowrap",
  },
  pill: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-accent) / 0.1)",
    borderRadius: "var(--tbr-radius-pill)",
    color: "rgb(var(--tbr-color-accent))",
    display: "inline-flex",
    fontSize: 10,
    fontWeight: 650,
    lineHeight: 1.2,
    minHeight: 18,
    paddingBlock: 2,
    paddingInline: 6,
    whiteSpace: "nowrap",
  },
  pillSuccess: {
    backgroundColor: "rgb(var(--tbr-color-success) / 0.12)",
    color: "rgb(var(--tbr-color-success))",
  },
  pillDanger: {
    backgroundColor: "rgb(var(--tbr-color-danger) / 0.1)",
    color: "rgb(var(--tbr-color-danger))",
  },
  pillMuted: {
    backgroundColor: "rgb(var(--tbr-color-text-muted) / 0.1)",
    color: "rgb(var(--tbr-color-text-muted))",
  },
  mutedText: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 11,
  },
  dangerText: {
    color: "rgb(var(--tbr-color-danger))",
    fontSize: 11,
    fontWeight: 650,
  },
  statusGrid: {
    display: "grid",
    gap: 8,
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      [mobile]: "minmax(0, 1fr)",
    },
    marginTop: 4,
  },
  statusCard: {
    ...interactiveSurface,
    display: "grid",
    gap: 5,
    minWidth: 0,
    padding: 10,
  },
  fieldNote: {
    color: "rgb(var(--tbr-color-text-subtle))",
    flexShrink: 0,
    fontSize: 10,
    lineHeight: 1.3,
    whiteSpace: "nowrap",
  },
  configList: {
    alignContent: "start",
    display: "grid",
    gap: 8,
  },
  configButton: {
    ...interactiveSurface,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "grid",
    fontFamily: "inherit",
    fontSize: 11,
    gap: 2,
    minHeight: 42,
    paddingBlock: 9,
    paddingInline: 10,
    textAlign: "left",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  schemaGrid: {
    display: "grid",
    gap: 8,
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      [mobile]: "minmax(0, 1fr)",
    },
  },
  schemaChip: {
    ...interactiveSurface,
    display: "grid",
    gap: 2,
    minHeight: 42,
    paddingBlock: 9,
    paddingInline: 10,
  },
  pathCode: {
    ...interactiveSurface,
    color: "rgb(var(--tbr-color-text-muted))",
    fontFamily: "var(--tbr-font-mono)",
    fontSize: 10,
    maxWidth: 170,
    overflow: "hidden",
    paddingBlock: 6,
    paddingInline: 8,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  accountPanel: {
    alignContent: "center",
    display: "grid",
    gap: 10,
    marginInline: "auto",
    minHeight: 248,
    width: "min(100%, 322px)",
  },
  authForm: {
    display: "grid",
    gap: 10,
  },
  authFieldsShell: {
    display: "grid",
    gap: 8,
  },
  authField: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: 8,
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    display: "grid",
    fontSize: 11,
    fontWeight: 600,
    gap: 8,
    gridTemplateColumns: "48px minmax(0, 1fr)",
    minHeight: 38,
    paddingInline: 10,
    ":focus-within": {
      backgroundColor: "rgb(var(--tbr-color-surface))",
      borderColor: "rgb(var(--tbr-color-accent))",
      boxShadow: "0 0 0 3px rgb(var(--tbr-color-accent) / 0.12)",
    },
  },
  authInputControl: {
    backgroundColor: "transparent",
    borderColor: "transparent",
    boxShadow: "none",
    height: 32,
    paddingInline: 0,
    ":hover": {
      borderColor: "transparent",
    },
    ":focus": {
      borderColor: "transparent",
      boxShadow: "none",
    },
  },
  authTabsList: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: 8,
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 2,
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    height: 32,
    padding: 3,
    width: "100%",
  },
  authTabsTrigger: {
    borderRadius: 5,
    flex: "1 1 0",
    fontSize: 11,
    fontWeight: 650,
    height: "100%",
    minHeight: 0,
    padding: 0,
  },
  authTabsSelected: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    boxShadow:
      "0 1px 2px rgb(var(--tbr-color-shadow) / 0.08), inset 0 0 0 1px rgb(var(--tbr-color-accent) / 0.46)",
  },
  authActionRow: {
    display: "grid",
    gap: 7,
  },
  authHelperRow: {
    alignItems: "center",
    display: "grid",
    gap: 8,
    gridTemplateColumns: "minmax(0, 1fr) auto",
  },
  authNote: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 10,
    lineHeight: 1.35,
    margin: 0,
  },
  authStatus: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 10,
    lineHeight: 1.3,
    margin: 0,
    textAlign: "center",
  },
  accountStateRow: {
    ...interactiveSurface,
    alignItems: "center",
    display: "flex",
    fontSize: 11,
    gap: 12,
    justifyContent: "space-between",
    minHeight: 42,
    paddingBlock: 9,
    paddingInline: 10,
  },
  accountStateActive: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-success))",
    display: "inline-flex",
    gap: 5,
  },
  authFlowHeading: {
    alignItems: "flex-start",
    color: "rgb(var(--tbr-color-accent))",
    display: "grid",
    gap: 8,
    gridTemplateColumns: "20px minmax(0, 1fr)",
  },
  authFlowHeadingCopy: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 12,
    fontWeight: 600,
  },
  authFlowHint: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 10,
    lineHeight: 1.35,
    marginBlock: 3,
    marginInline: 0,
  },
})
