import * as stylex from "@stylexjs/stylex"
import type { CompiledStyles, InlineStyles, StyleXArray } from "@stylexjs/stylex"

type XStyle = StyleXArray<
  (null | undefined | CompiledStyles) | boolean | Readonly<[CompiledStyles, InlineStyles]>
>

const mobile = "@media (max-width: 560px)"

const interactiveSurface = {
  backgroundColor: "rgb(var(--tbr-color-surface-soft))",
  borderColor: "rgb(var(--tbr-color-line))",
  borderRadius: 6,
  borderStyle: "solid",
  borderWidth: 1,
}

export const styles = stylex.create({
  searchRoot: {
    maxWidth: 720,
    position: "relative",
    width: "100%",
  },
  searchBar: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 2px 8px rgb(var(--tbr-color-shadow) / 0.04)",
    display: "flex",
    gap: 10,
    height: 46,
    paddingInline: 12,
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "background-color, border-color, box-shadow",
    transitionTimingFunction: "var(--tbr-ease)",
    ":hover": {
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
    ":focus-within": {
      borderColor: "rgb(var(--tbr-color-accent))",
      boxShadow: "0 0 0 3px rgb(var(--tbr-color-accent) / 0.12)",
    },
  },
  searchProvider: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    position: "relative",
  },
  searchProviderButton: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-pill)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 11,
    fontWeight: 550,
    gap: 5,
    height: 24,
    paddingInlineEnd: 7,
    paddingInlineStart: 6,
    whiteSpace: "nowrap",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  searchProviderDot: {
    backgroundColor: "rgb(var(--tbr-color-accent))",
    borderRadius: "50%",
    height: 6,
    width: 6,
  },
  searchProviderLabel: {
    maxWidth: 120,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  searchProviderCaret: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 9,
    opacity: 0.58,
  },
  searchProviderDropdown: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 4px 16px rgb(var(--tbr-color-shadow) / 0.18)",
    left: 0,
    minWidth: 160,
    overflow: "hidden",
    position: "absolute",
    top: "calc(100% + 4px)",
    zIndex: 20,
  },
  searchProviderOption: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-text))",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: 12,
    gap: 8,
    paddingBlock: 7,
    paddingInline: 12,
    textAlign: "left",
    width: "100%",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
    },
  },
  selected: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderColor: "rgb(var(--tbr-color-accent))",
    color: "rgb(var(--tbr-color-accent))",
  },
  searchCheck: {
    color: "rgb(var(--tbr-color-accent))",
    fontSize: 10,
    width: 14,
  },
  searchDivider: {
    backgroundColor: "rgb(var(--tbr-color-line))",
    flexShrink: 0,
    height: 18,
    width: 1,
  },
  searchKbd: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "inline-flex",
    flexShrink: 0,
    fontFamily: "var(--tbr-font-mono)",
    fontSize: 10,
    height: 18,
    justifyContent: "center",
    opacity: 0.68,
    paddingInline: 5,
  },
  searchState: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 11,
    marginTop: 5,
    paddingInline: 2,
  },
  searchSuggestions: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 4px 20px rgb(var(--tbr-color-shadow) / 0.1)",
    left: 0,
    maxHeight: 300,
    overflowY: "auto",
    position: "absolute",
    right: 0,
    top: "calc(100% + 4px)",
    zIndex: 20,
  },
  searchGroup: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 10,
    fontWeight: 650,
    paddingBlockEnd: 4,
    paddingBlockStart: 8,
    paddingInline: 12,
  },
  searchItem: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "rgb(var(--tbr-color-text))",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    gap: 10,
    minHeight: 42,
    paddingBlock: 7,
    paddingInline: 10,
    textAlign: "left",
    width: "100%",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
    },
  },
  searchItemActive: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
  },
  searchItemIcon: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "inline-flex",
    flexShrink: 0,
    fontSize: 12,
    justifyContent: "center",
    width: 22,
  },
  searchItemText: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minWidth: 0,
  },
  searchItemName: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 12,
    fontWeight: 650,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  searchItemDescription: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 10,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  panelStack: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  group: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    display: "grid",
    gap: 8,
    padding: 0,
  },
  groupTitle: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text))",
    display: "flex",
    fontSize: 11,
    fontWeight: 650,
    gap: 8,
    justifyContent: "space-between",
    lineHeight: 1.25,
    minHeight: 22,
    paddingInline: 2,
  },
  groupTitleMeta: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 10,
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  fieldRow: {
    ...interactiveSurface,
    display: "grid",
    gap: 6,
    minHeight: 42,
    minWidth: 0,
    paddingBlock: 9,
    paddingInline: 10,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
  },
  rowMeta: {
    color: "rgb(var(--tbr-color-text-muted))",
    flexShrink: 0,
    fontSize: 11,
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  rangeControl: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "grid",
    fontSize: 11,
    fontWeight: 600,
    gap: 8,
    gridTemplateColumns: "minmax(92px, 1fr) 42px",
    minWidth: 170,
    width: {
      default: "auto",
      [mobile]: "100%",
    },
  },
  checkList: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    justifyContent: {
      default: "flex-end",
      [mobile]: "flex-start",
    },
    minWidth: 220,
    width: {
      default: "auto",
      [mobile]: "100%",
    },
  },
  checkChip: {
    ...interactiveSurface,
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "inline-flex",
    height: 28,
    paddingInline: 8,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent-soft))",
      borderColor: "rgb(var(--tbr-color-accent))",
      color: "rgb(var(--tbr-color-text))",
    },
  },
  swatchRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    justifyContent: {
      default: "flex-end",
      [mobile]: "flex-start",
    },
  },
  swatch: {
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    cursor: "pointer",
    height: 28,
    padding: 0,
    width: 28,
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  stepper: {
    ...interactiveSurface,
    alignItems: "center",
    display: "inline-flex",
    height: 30,
    overflow: "hidden",
  },
  keybind: {
    ...interactiveSurface,
    alignItems: "center",
    display: "inline-flex",
    gap: 5,
    height: 30,
    paddingInline: 8,
  },
  inlineActions: {
    alignItems: "center",
    display: "inline-flex",
    gap: 7,
    justifyContent: {
      default: "flex-end",
      [mobile]: "flex-start",
    },
    minWidth: 0,
    width: {
      default: "auto",
      [mobile]: "100%",
    },
  },
  wideInlineActions: {
    width: {
      default: 244,
      [mobile]: "100%",
    },
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  listItem: {
    ...interactiveSurface,
    alignItems: "center",
    display: "grid",
    gap: 10,
    gridTemplateColumns: {
      default: "minmax(0, 1fr) auto",
      [mobile]: "minmax(0, 1fr)",
    },
    minHeight: 42,
    paddingBlock: 9,
    paddingInline: 10,
  },
  listName: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 12,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  listNameActive: {
    color: "rgb(var(--tbr-color-text))",
    fontWeight: 650,
  },
  successText: {
    color: "rgb(var(--tbr-color-success))",
    fontSize: 12,
  },
  warningList: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 12,
    margin: 0,
    paddingLeft: 18,
  },
  providerList: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  providerRow: {
    ...interactiveSurface,
    alignItems: "center",
    display: "grid",
    gap: 10,
    gridTemplateColumns: {
      default: "minmax(0, 1fr) auto",
      [mobile]: "minmax(0, 1fr)",
    },
    minHeight: 42,
    paddingBlock: 9,
    paddingInline: 10,
    width: "100%",
  },
  disabled: {
    opacity: 0.58,
  },
  providerMain: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "inherit",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    gap: 10,
    minWidth: 0,
    padding: 0,
    textAlign: "left",
    width: "100%",
    ":disabled": {
      cursor: "not-allowed",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  providerKind: {
    color: "rgb(var(--tbr-color-text-muted))",
    flexShrink: 0,
    fontSize: 11,
    fontWeight: 650,
  },
  providerText: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
  },
  providerTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 12,
    fontWeight: 650,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  providerAlias: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 11,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  providerState: {
    color: "rgb(var(--tbr-color-accent))",
    fontSize: 11,
    fontWeight: 600,
    minWidth: 42,
    textAlign: "right",
  },
  pluginHelp: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 11,
    lineHeight: 1.35,
    margin: 0,
  },
  pluginCard: {
    ...interactiveSurface,
    alignItems: "center",
    display: "grid",
    gap: 10,
    gridTemplateColumns: {
      default: "minmax(0, 1fr) auto",
      [mobile]: "minmax(0, 1fr)",
    },
    minHeight: 42,
    minWidth: 0,
    paddingBlock: 9,
    paddingInline: 10,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
  },
  pluginMain: {
    minWidth: 0,
  },
  pluginName: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 12,
    fontWeight: 650,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  pluginId: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontFamily: "var(--tbr-font-mono)",
    fontSize: 10,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  pluginMeta: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 10,
    lineHeight: 1.35,
    marginTop: 2,
  },
  pluginControls: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    flexWrap: "wrap",
    gap: 7,
    justifyContent: {
      default: "flex-end",
      [mobile]: "flex-start",
    },
  },
  pluginVersion: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 10,
    whiteSpace: "nowrap",
  },
  pill: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-accent) / 0.1)",
    borderRadius: "var(--tbr-radius-pill)",
    color: "rgb(var(--tbr-color-accent))",
    display: "inline-flex",
    fontSize: 10,
    fontWeight: 650,
    lineHeight: 1.2,
    minHeight: 18,
    paddingBlock: 2,
    paddingInline: 6,
    whiteSpace: "nowrap",
  },
  pillSuccess: {
    backgroundColor: "rgb(var(--tbr-color-success) / 0.12)",
    color: "rgb(var(--tbr-color-success))",
  },
  pillDanger: {
    backgroundColor: "rgb(var(--tbr-color-danger) / 0.1)",
    color: "rgb(var(--tbr-color-danger))",
  },
  pillMuted: {
    backgroundColor: "rgb(var(--tbr-color-text-muted) / 0.1)",
    color: "rgb(var(--tbr-color-text-muted))",
  },
  mutedText: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 11,
  },
  dangerText: {
    color: "rgb(var(--tbr-color-danger))",
    fontSize: 11,
    fontWeight: 650,
  },
  statusGrid: {
    display: "grid",
    gap: 8,
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      [mobile]: "minmax(0, 1fr)",
    },
    marginTop: 4,
  },
  statusCard: {
    ...interactiveSurface,
    display: "grid",
    gap: 5,
    minWidth: 0,
    padding: 10,
  },
  fieldNote: {
    color: "rgb(var(--tbr-color-text-subtle))",
    flexShrink: 0,
    fontSize: 10,
    lineHeight: 1.3,
    whiteSpace: "nowrap",
  },
  configList: {
    alignContent: "start",
    display: "grid",
    gap: 8,
  },
  configButton: {
    ...interactiveSurface,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "grid",
    fontFamily: "inherit",
    fontSize: 11,
    gap: 2,
    minHeight: 42,
    paddingBlock: 9,
    paddingInline: 10,
    textAlign: "left",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  schemaGrid: {
    display: "grid",
    gap: 8,
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      [mobile]: "minmax(0, 1fr)",
    },
  },
  schemaChip: {
    ...interactiveSurface,
    display: "grid",
    gap: 2,
    minHeight: 42,
    paddingBlock: 9,
    paddingInline: 10,
  },
  pathCode: {
    ...interactiveSurface,
    color: "rgb(var(--tbr-color-text-muted))",
    fontFamily: "var(--tbr-font-mono)",
    fontSize: 10,
    maxWidth: 170,
    overflow: "hidden",
    paddingBlock: 6,
    paddingInline: 8,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  accountPanel: {
    display: "grid",
    gap: 10,
    marginInline: "auto",
    width: "min(100%, 322px)",
  },
  authForm: {
    display: "grid",
    gap: 10,
  },
  authField: {
    ...interactiveSurface,
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "grid",
    fontSize: 11,
    fontWeight: 600,
    gap: 8,
    gridTemplateColumns: "48px minmax(0, 1fr)",
    minHeight: 38,
    paddingInline: 10,
    ":focus-within": {
      backgroundColor: "rgb(var(--tbr-color-surface))",
      borderColor: "rgb(var(--tbr-color-accent))",
      boxShadow: "0 0 0 3px rgb(var(--tbr-color-accent) / 0.18)",
    },
  },
  accountActions: {
    display: "grid",
    gap: 6,
    gridTemplateColumns: "72px minmax(0, 1fr)",
  },
  authStatus: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 10,
    lineHeight: 1.3,
    textAlign: "center",
  },
  profileCard: {
    ...interactiveSurface,
    display: "grid",
    gap: 12,
    paddingBlock: 14,
    paddingInline: 12,
  },
  profileInfo: {
    alignItems: "center",
    display: "grid",
    gap: 12,
    gridTemplateColumns: "40px minmax(0, 1fr)",
  },
  avatar: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-accent))",
    borderRadius: "50%",
    display: "flex",
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  avatarInitial: {
    color: "rgb(var(--tbr-color-inverse))",
    fontSize: 16,
    fontWeight: 600,
  },
  profileDetails: {
    display: "grid",
    gap: 4,
    minWidth: 0,
  },
  profileEmail: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 13,
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  profileStatus: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    fontSize: 11,
    gap: 6,
  },
  statusDot: {
    backgroundColor: "rgb(var(--tbr-color-success))",
    borderRadius: "50%",
    height: 6,
    width: 6,
  },
})

export function className(...values: XStyle[]) {
  return stylex.attrs(...values).class
}
