import * as stylex from "@stylexjs/stylex"

export const layoutStyles = stylex.create({
  expandRoot: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    display: "flex",
    flex: 1,
    flexDirection: "column",
    height: "100%",
    minHeight: "min(468px, calc(100vh - 116px))",
    minWidth: 0,
  },
  expandHeader: {
    alignItems: "center",
    borderBottomColor: "rgb(var(--tbr-color-line))",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexShrink: 0,
    gap: 8,
    paddingBlock: 8,
    paddingInline: 12,
    "@media (min-width: 720px)": {
      display: "none",
    },
  },
  historyToggle: {
    flexShrink: 0,
  },
  activeTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 13,
    fontWeight: 650,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  expandBody: {
    display: "flex",
    flex: 1,
    flexDirection: "row",
    minHeight: 0,
  },
  side: {
    backgroundColor: "rgb(var(--tbr-color-page))",
    borderRightColor: "rgb(var(--tbr-color-line))",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    overflowY: "auto",
    width: 216,
    "@media (max-width: 720px)": {
      display: "none",
    },
  },
  main: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minWidth: 0,
  },
  empty: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minHeight: 0,
    backgroundColor: "rgb(var(--tbr-color-page-muted))",
  },
  emptyWelcome: {
    alignItems: "center",
    display: "flex",
    flex: 1,
    minHeight: 0,
    justifyContent: "center",
    paddingBlock: 28,
    paddingInline: 24,
  },
  emptyWelcomeContent: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    gap: 16,
    maxWidth: 760,
    textAlign: "center",
    width: "100%",
  },
  emptyTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: "clamp(20px, 3vw, 28px)",
    fontWeight: 650,
    letterSpacing: "-0.02em",
    lineHeight: 1.25,
  },
  emptyComposer: {
    width: "100%",
  },
  emptyWelcomeIcon: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-accent))",
    display: "flex",
    height: 40,
    justifyContent: "center",
    marginBottom: 8,
    width: 40,
  },
  statusBar: {
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    gap: 8,
    paddingBlock: 10,
    paddingInline: 16,
  },
  statusActions: {
    alignItems: "center",
    display: "flex",
    gap: 8,
  },
})
