import type { ComponentDocsCategory } from "./types"

export const componentDocsCategories: ComponentDocsCategory[] = [
  {
    title: "输入控件",
    items: [
      { id: "button", name: "Button" },
      { id: "iconbutton", name: "IconButton" },
      { id: "input", name: "Input" },
      { id: "textarea", name: "Textarea" },
      { id: "select", name: "Select" },
      { id: "combobox", name: "Combobox" },
      { id: "link", name: "Link" },
      { id: "kbd", name: "Kbd" },
      { id: "taginput", name: "TagInput" },
      { id: "breadcrumb", name: "Breadcrumb" },
    ],
  },
  {
    title: "选择控件",
    items: [
      { id: "checkbox", name: "Checkbox" },
      { id: "switch", name: "Switch" },
      { id: "radio", name: "RadioGroup" },
      { id: "segmented", name: "SegmentedControl" },
      { id: "togglegroup", name: "ToggleGroup" },
      { id: "tabs", name: "Tabs" },
    ],
  },
  {
    title: "浮层与菜单",
    items: [
      { id: "dropdown", name: "DropdownMenu" },
      { id: "contextmenu", name: "ContextMenu" },
      { id: "dialog", name: "Dialog" },
      { id: "drawer", name: "Drawer" },
      { id: "popover", name: "Popover" },
      { id: "hovercard", name: "HoverCard" },
      { id: "command", name: "CommandPalette" },
      { id: "tooltip", name: "Tooltip" },
    ],
  },
  {
    title: "反馈与通知",
    items: [
      { id: "toast", name: "Toast" },
      { id: "banner", name: "Banner" },
      { id: "alert", name: "Alert" },
      { id: "field", name: "Field" },
      { id: "badge", name: "Badge" },
      { id: "inlineerror", name: "InlineError" },
      { id: "spinner", name: "Spinner" },
      { id: "skeleton", name: "Skeleton" },
      { id: "progress", name: "Progress" },
      { id: "scrollarea", name: "ScrollArea" },
      { id: "divider", name: "Divider" },
    ],
  },
  {
    title: "标签与结构",
    items: [
      { id: "chip", name: "Chip" },
      { id: "avatar", name: "Avatar" },
      { id: "accordion", name: "Accordion" },
      { id: "collapsible", name: "Collapsible" },
      { id: "slider", name: "Slider" },
      { id: "pagination", name: "Pagination" },
      { id: "table", name: "Table" },
      { id: "treeview", name: "TreeView" },
      { id: "menubar", name: "Menubar" },
      { id: "steps", name: "Steps" },
      { id: "timeline", name: "Timeline" },
      { id: "emptystate", name: "EmptyState" },
      { id: "listrow", name: "ListRow" },
      { id: "cardsection", name: "CardSection" },
      { id: "copybutton", name: "CopyButton" },
      { id: "truncate", name: "Truncate" },
      { id: "visuallyhidden", name: "VisuallyHidden" },
    ],
  },
  {
    title: "组合模式",
    items: [{ id: "patterns", name: "组合模式" }],
  },
]
