import type { ComponentDocItem, ComponentDocsCategory } from "./types"

export const componentDocsCategories: ComponentDocsCategory[] = [
  {
    title: "输入控件",
    items: [
      { id: "button", name: "Button" },
      { id: "iconbutton", name: "IconButton" },
      { id: "input", name: "Input" },
      { id: "textarea", name: "Textarea" },
      { id: "select", name: "Select" },
      { id: "combobox", name: "Combobox" },
      { id: "link", name: "Link" },
      { id: "kbd", name: "Kbd" },
      { id: "taginput", name: "TagInput" },
      { id: "breadcrumb", name: "Breadcrumb" },
    ],
  },
  {
    title: "选择控件",
    items: [
      { id: "checkbox", name: "Checkbox" },
      { id: "switch", name: "Switch" },
      { id: "radio", name: "RadioGroup" },
      { id: "segmented", name: "SegmentedControl" },
      { id: "togglegroup", name: "ToggleGroup" },
      { id: "tabs", name: "Tabs" },
    ],
  },
  {
    title: "浮层与菜单",
    items: [
      { id: "dropdown", name: "DropdownMenu" },
      { id: "contextmenu", name: "ContextMenu" },
      { id: "dialog", name: "Dialog" },
      { id: "drawer", name: "Drawer" },
      { id: "popover", name: "Popover" },
      { id: "hovercard", name: "HoverCard" },
      { id: "command", name: "CommandPalette" },
      { id: "tooltip", name: "Tooltip" },
    ],
  },
  {
    title: "反馈与通知",
    items: [
      { id: "toast", name: "Toast" },
      { id: "banner", name: "Banner" },
      { id: "alert", name: "Alert" },
      { id: "field", name: "Field" },
      { id: "badge", name: "Badge" },
      { id: "inlineerror", name: "InlineError" },
      { id: "spinner", name: "Spinner" },
      { id: "skeleton", name: "Skeleton" },
      { id: "progress", name: "Progress" },
      { id: "scrollarea", name: "ScrollArea" },
      { id: "divider", name: "Divider" },
    ],
  },
  {
    title: "标签与结构",
    items: [
      { id: "chip", name: "Chip" },
      { id: "avatar", name: "Avatar" },
      { id: "accordion", name: "Accordion" },
      { id: "collapsible", name: "Collapsible" },
      { id: "slider", name: "Slider" },
      { id: "pagination", name: "Pagination" },
      { id: "table", name: "Table" },
      { id: "treeview", name: "TreeView" },
      { id: "menubar", name: "Menubar" },
      { id: "steps", name: "Steps" },
      { id: "timeline", name: "Timeline" },
      { id: "emptystate", name: "EmptyState" },
      { id: "listrow", name: "ListRow" },
      { id: "cardsection", name: "CardSection" },
      { id: "copybutton", name: "CopyButton" },
      { id: "truncate", name: "Truncate" },
      { id: "visuallyhidden", name: "VisuallyHidden" },
    ],
  },
  {
    title: "组合模式",
    items: [{ id: "patterns", name: "组合模式" }],
  },
]

export const componentDocItems: ComponentDocItem[] = [
  {
    id: "button",
    name: "Button",
    title: "Button 按钮",
    purpose: "用于明确操作触发。每个可视区域最多一个 primary，危险低强度操作使用 danger-subtle。",
    usage:
      "设置保存、表单提交、普通次级操作、危险动作确认。支持尺寸、变体、loading/disabled 和全宽。",
    code: `<Button variant="primary">保存</Button>
<Button variant="danger-subtle">移除</Button>`,
  },
  {
    id: "iconbutton",
    name: "IconButton",
    title: "IconButton 图标按钮",
    purpose: "用于仅图标动作，必须提供 aria-label。",
    usage: "适合编辑、删除、更多等紧凑工具按钮。图标来自产品图标体系；这里用文本符号保持示例轻量。",
    code: `<IconButton aria-label="添加">+</IconButton>`,
  },
  {
    id: "input",
    name: "Input",
    title: "Input 输入框",
    purpose: "单行文本输入。必须有 label 或 aria-label，placeholder 不替代 label。",
    usage: "搜索、URL、邮箱、标题等短文本场景。invalid 状态配合 Field 或 InlineError。",
    code: `<Input value={value()} onInput={setValue} aria-label="工作区名称" />`,
  },
  {
    id: "textarea",
    name: "Textarea",
    title: "Textarea 文本域",
    purpose: "多行文本输入，支持垂直 resize。",
    usage: "便签、描述、评论、插件配置说明等长文本。内容过多时控件内部滚动，不撑破卡片。",
    code: `<Textarea value={note()} onInput={setNote} rows={4} aria-label="便签" />`,
  },
  {
    id: "select",
    name: "Select",
    title: "Select 下拉选择",
    purpose: "5 个以上选项或需要下拉承载的单选场景。",
    usage: "默认搜索源、主题、背景来源等设置项。2-4 个短选项优先用 SegmentedControl。",
    code: `<Select value="google" options={options} onChange={setValue} aria-label="搜索源" />`,
  },
  {
    id: "combobox",
    name: "Combobox",
    title: "Combobox 搜索选择",
    purpose: "用于搜索选择或大量选项过滤。",
    usage: "插件、命令、搜索 provider 等选项较多且需要输入筛选的场景。",
    code: `<Combobox value={query()} options={options} onInput={setQuery} onSelect={setValue} />`,
  },
  {
    id: "link",
    name: "Link",
    title: "Link 链接",
    purpose: "文本链接，用于导航和外部资料。",
    usage: "外部链接在插件中仍应经过权限桥；UI 组件只负责视觉与语义。",
    code: `<Link href="/docs">内部链接</Link>`,
  },
  {
    id: "kbd",
    name: "Kbd",
    title: "Kbd 快捷键",
    purpose: "展示快捷键、插件 ID 或命令提示中的按键。",
    usage: "命令搜索、快捷键面板、工具提示说明。",
    code: `<Kbd>Ctrl</Kbd><Kbd>K</Kbd>`,
  },
  {
    id: "taginput",
    name: "TagInput",
    title: "TagInput 标签输入",
    purpose: "输入驱动的标签创建器，回车或逗号创建标签。",
    usage: "插件分类、搜索过滤、链接分组等需要用户持续添加标签的场景。",
    code: `<TagInput value={tags()} onChange={setTags} aria-label="标签" />`,
  },
  {
    id: "breadcrumb",
    name: "Breadcrumb",
    title: "Breadcrumb 面包屑",
    purpose: "展示当前位置路径。",
    usage: "设置深层页面、文档章节、插件配置路径。",
    code: `<Breadcrumb items={[{ label: "工作台" }, { label: "设置", current: true }]} />`,
  },
  {
    id: "checkbox",
    name: "Checkbox",
    title: "Checkbox 勾选框",
    purpose: "完成态、多选状态。待办完成必须用 Checkbox。",
    usage: "待办列表、多选过滤、显式提交的偏好项。",
    code: `<Checkbox checked={checked()} onChange={setChecked} label="同步完成" />`,
  },
  {
    id: "switch",
    name: "Switch",
    title: "Switch 开关",
    purpose: "即时生效的二元启用/禁用设置。",
    usage: "插件启用、搜索源启用、功能开关；不用于一次性动作。",
    code: `<Switch checked={enabled()} onChange={setEnabled} label="启用插件" />`,
  },
  {
    id: "radio",
    name: "RadioGroup",
    title: "RadioGroup 单选组",
    purpose: "3-5 个互斥选项，适合带说明的选择。",
    usage: "主题模式、布局策略、互斥配置项。",
    code: `<RadioGroup value={theme()} options={options} onChange={setTheme} />`,
  },
  {
    id: "segmented",
    name: "SegmentedControl",
    title: "SegmentedControl 分段",
    purpose: "2-4 个纯文本短选项互斥切换。",
    usage: "卡片尺寸、密度、简单模式切换。",
    code: `<SegmentedControl value={size()} options={sizes} onChange={setSize} aria-label="尺寸" />`,
  },
  {
    id: "togglegroup",
    name: "ToggleGroup",
    title: "ToggleGroup 多选组",
    purpose: "多个独立按钮样式的多选。",
    usage: "周期、标签过滤、多个可并存的显示开关。",
    code: `<ToggleGroup value={days()} options={days} onChange={setDays} aria-label="工作日" />`,
  },
  {
    id: "tabs",
    name: "Tabs",
    title: "Tabs 标签页",
    purpose: "切换同一容器内的内容视图。",
    usage: "设置分区、插件详情分面、同一上下文内的视图切换。",
    code: `<Tabs value={tab()} tabs={tabs} onChange={setTab} aria-label="设置分区" />`,
  },
  {
    id: "dropdown",
    name: "DropdownMenu",
    title: "DropdownMenu 下拉菜单",
    purpose: "承载尺寸、展开、移除等动作。",
    usage: "按钮触发的动作菜单。危险动作需要明确样式。",
    code: `<DropdownMenu open={open()} items={items}>...</DropdownMenu>`,
  },
  {
    id: "contextmenu",
    name: "ContextMenu",
    title: "ContextMenu 右键菜单",
    purpose: "呈现上下文动作列表。",
    usage: "卡片右键菜单、列表行上下文动作。宿主负责真实右键触发，组件负责菜单内容视觉。",
    code: `<ContextMenu items={items} onSelect={handleSelect} />`,
  },
  {
    id: "dialog",
    name: "Dialog",
    title: "Dialog 对话框",
    purpose: "模态确认或通知。危险确认使用 destructive 样式。",
    usage: "删除确认、权限说明、不可继续前的必要确认。",
    code: `<Dialog open={open()} title="确认移除" destructive footer={...} />`,
  },
  {
    id: "drawer",
    name: "Drawer",
    title: "Drawer 抽屉",
    purpose: "保持上下文的详情或设置面板。",
    usage: "插件详情、卡片设置、需要更多空间但不离开当前页面的场景。",
    code: `<Drawer open={open()} title="插件详情">...</Drawer>`,
  },
  {
    id: "popover",
    name: "Popover",
    title: "Popover 弹出层",
    purpose: "短表单、筛选器或局部详情。",
    usage: "不会打断主流程的轻量上下文内容；需要确认时改用 Dialog。",
    code: `<Popover open={open()} title="背景">内容</Popover>`,
  },
  {
    id: "hovercard",
    name: "HoverCard",
    title: "HoverCard 悬停卡",
    purpose: "hover/focus 后展示较完整的只读预览。",
    usage: "用户、插件、链接预览。不可承载复杂操作。",
    code: `<HoverCard trigger="official.widget.todo" title="Todo" description="待办卡片" />`,
  },
  {
    id: "command",
    name: "CommandPalette",
    title: "CommandPalette 命令面板",
    purpose: "全局命令、搜索、卡片和 provider 切换入口。",
    usage: "支持实时建议、分组结果、键盘导航与 Enter 执行。",
    code: `<CommandPalette open groups={groups} query={query()} onQueryChange={setQuery} />`,
  },
  {
    id: "tooltip",
    name: "Tooltip",
    title: "Tooltip 提示",
    purpose: "hover/focus 简短说明。纯文本，不可交互。",
    usage: "解释图标按钮、状态缩写、紧凑控件。",
    code: `<Tooltip content="设置"><IconButton aria-label="设置">...</IconButton></Tooltip>`,
  },
  {
    id: "toast",
    name: "Toast",
    title: "Toast 轻通知",
    purpose: "非阻塞操作反馈，自动消失，最多一个操作。",
    usage: "保存成功、删除确认、低优先级提示。需要确认的错误使用 Dialog 或 InlineError。",
    code: `<Toast variant="success" title="设置已保存" />`,
  },
  {
    id: "banner",
    name: "Banner",
    title: "Banner 通知横幅",
    purpose: "页面顶部的非模态通知条。",
    usage: "系统公告、版本提示、存储不足等需要用户关注但不中断流程的提示。",
    code: `<Banner variant="info" title="新版本可用" description="..." />`,
  },
  {
    id: "alert",
    name: "Alert",
    title: "Alert 提示框",
    purpose: "内容流中的强调提示。",
    usage: "卡片内说明、表单提示、局部重要状态。与 Banner 的区别是 Alert 是内联的。",
    code: `<Alert variant="warning" title="注意" description="仅影响当前工作区" />`,
  },
  {
    id: "field",
    name: "Field",
    title: "Field 表单字段",
    purpose: "label + description + input + error 的组合单元。",
    usage: "保证表单控件有真实 label，并集中展示说明和错误。",
    code: `<Field label="显示名称"><Input id="name" ... /></Field>`,
  },
  {
    id: "badge",
    name: "Badge",
    title: "Badge 标签",
    purpose: "状态指示，支持文字、圆点、计数。",
    usage: "插件状态、权限摘要、版本状态、计数提示。",
    code: `<Badge variant="success">运行中</Badge>`,
  },
  {
    id: "inlineerror",
    name: "InlineError",
    title: "InlineError 行内错误",
    purpose: "局部错误展示，可包含重试或授权动作。",
    usage: "插件视图、字段、搜索结果等局部失败。",
    code: `<InlineError>加载天气失败 <Button size="sm">重试</Button></InlineError>`,
  },
  {
    id: "spinner",
    name: "Spinner",
    title: "Spinner 加载指示",
    purpose: "不定长旋转加载。",
    usage: "短暂等待状态。加载时间较长或需要占位时使用 Skeleton。",
    code: `<Spinner size="sm" aria-label="加载中" />`,
  },
  {
    id: "skeleton",
    name: "Skeleton",
    title: "Skeleton 骨架屏",
    purpose: "形状匹配实际内容，避免加载完成后的布局跳动。",
    usage: "卡片、列表、头像等较长加载占位。",
    code: `<SkeletonText lines={3} />`,
  },
  {
    id: "progress",
    name: "Progress",
    title: "Progress 进度",
    purpose: "确定进度条。",
    usage: "导入、同步、批量任务进度。未知时长可用 Spinner 或 Skeleton。",
    code: `<Progress value={60} aria-label="导入进度" />`,
  },
  {
    id: "scrollarea",
    name: "ScrollArea",
    title: "ScrollArea 滚动区域",
    purpose: "限制内容高度并在内部滚动。",
    usage: "卡片内日志、长列表、设置项说明，避免撑破宿主卡片。",
    code: `<ScrollArea style={{ "max-height": "96px" }}>...</ScrollArea>`,
  },
  {
    id: "divider",
    name: "Divider",
    title: "Divider 分隔线",
    purpose: "弱分隔内容组。",
    usage: "菜单、卡片 section、文档内容分隔。",
    code: `<Divider />`,
  },
  {
    id: "chip",
    name: "Chip",
    title: "Chip 标签片",
    purpose: "静态标签、过滤条件、可移除标签。",
    usage: "与 TagInput 区分：Chip 是已创建标签的展示，TagInput 是输入创建器。",
    code: `<Chip removable onRemove={handleRemove}>设计</Chip>`,
  },
  {
    id: "avatar",
    name: "Avatar",
    title: "Avatar 头像",
    purpose: "用户、插件或来源的紧凑视觉标识。",
    usage: "插件作者、团队成员、账户信息。",
    code: `<Avatar fallback="Tabora" />`,
  },
  {
    id: "accordion",
    name: "Accordion",
    title: "Accordion 手风琴",
    purpose: "一组可展开/折叠的问题或设置块。",
    usage: "FAQ、插件配置分组、说明文档。",
    code: `<Accordion items={[{ id: "a", title: "Manifest", content: "..." }]} />`,
  },
  {
    id: "collapsible",
    name: "Collapsible",
    title: "Collapsible 折叠区",
    purpose: "单个可展开内容块。",
    usage: "高级设置、调试信息、说明展开。",
    code: `<Collapsible title="高级">内容</Collapsible>`,
  },
  {
    id: "slider",
    name: "Slider",
    title: "Slider 滑块",
    purpose: "连续或分步数值设置。",
    usage: "透明度、字号、密度、动画强度等数值。",
    code: `<Slider value={value()} onChange={setValue} aria-label="透明度" />`,
  },
  {
    id: "pagination",
    name: "Pagination",
    title: "Pagination 分页",
    purpose: "分页浏览长列表。",
    usage: "插件列表、日志、数据表格。",
    code: `<Pagination page={page()} total={5} onChange={setPage} />`,
  },
  {
    id: "table",
    name: "Table",
    title: "Table 表格",
    purpose: "密集、可扫描的信息组织。",
    usage: "插件管理、权限矩阵、状态列表。移动端应允许横向内部滚动而不是页面横向滚动。",
    code: `<Table columns={columns} rows={plugins} rowKey={(row) => row.id} />`,
  },
  {
    id: "treeview",
    name: "TreeView",
    title: "TreeView 树",
    purpose: "展示层级数据。",
    usage: "文件、插件贡献点、文档结构。",
    code: `<TreeView items={items} expandedIds={expanded()} onExpandedChange={setExpanded} />`,
  },
  {
    id: "menubar",
    name: "Menubar",
    title: "Menubar 菜单栏",
    purpose: "紧凑导航或同级命令切换。",
    usage: "设置导航、文档分区、工具菜单。",
    code: `<Menubar value={value()} items={items} onChange={setValue} />`,
  },
  {
    id: "steps",
    name: "Steps",
    title: "Steps 步骤",
    purpose: "展示流程阶段。",
    usage: "安装、导入、插件启用流程。",
    code: `<Steps current={1} steps={[{ title: "安装" }, { title: "启用" }]} />`,
  },
  {
    id: "timeline",
    name: "Timeline",
    title: "Timeline 时间线",
    purpose: "按时间或阶段展示事件。",
    usage: "插件日志、发布记录、导入过程。",
    code: `<Timeline items={[{ title: "创建插件" }]} />`,
  },
  {
    id: "emptystate",
    name: "EmptyState",
    title: "EmptyState 空状态",
    purpose: "用于空数据或无匹配结果，提供下一步动作。",
    usage: "无搜索结果、空列表、未添加插件。",
    code: `<EmptyState title="暂无卡片" action={<Button>添加</Button>} />`,
  },
  {
    id: "listrow",
    name: "ListRow",
    title: "ListRow 列表行",
    purpose: "密集、可扫描的信息行。",
    usage: "设置项、插件列表、搜索结果。",
    code: `<ListRow primary="Todo" secondary="待办卡片" trailing={<Switch ... />} />`,
  },
  {
    id: "cardsection",
    name: "CardSection",
    title: "CardSection 卡片分区",
    purpose: "插件内容区的分组结构。",
    usage: "卡片内标题、设置分组、列表分区。不是宿主 WidgetCard。",
    code: `<CardSection title="搜索">内容</CardSection>`,
  },
  {
    id: "copybutton",
    name: "CopyButton",
    title: "CopyButton 复制按钮",
    purpose: "复制文本到剪贴板并给出短反馈。",
    usage: "复制插件 ID、命令、代码片段。",
    code: `<CopyButton value="official.widget.todo" />`,
  },
  {
    id: "truncate",
    name: "Truncate",
    title: "Truncate 截断",
    purpose: "单行或多行文本截断。",
    usage: "列表标题、卡片描述、链接摘要，保证布局稳定。",
    code: `<Truncate lines={2}>很长的文本...</Truncate>`,
  },
  {
    id: "visuallyhidden",
    name: "VisuallyHidden",
    title: "VisuallyHidden 视觉隐藏",
    purpose: "给辅助技术保留文本，同时视觉上隐藏。",
    usage: "图标按钮补充文字、状态说明、隐藏 label。",
    code: `<VisuallyHidden>只读给屏幕阅读器</VisuallyHidden>`,
  },
  {
    id: "patterns",
    name: "组合模式",
    title: "组合模式",
    purpose: "把基础组件组合成 Tabora 常见场景，方便和规范页里的组合示范对比。",
    usage: "插件设置、搜索配置、状态提示等组合示例，验证基础组件在真实工作台语境中的协作方式。",
    code: `<CardSection title="插件设置">
  <ListRow primary="启用插件" trailing={<Switch />} />
</CardSection>`,
  },
]

export function getComponentDoc(id: string) {
  return componentDocItems.find((item) => item.id === id)
}
