import * as stylex from "@stylexjs/stylex"
import type { CompiledStyles, InlineStyles, StyleXArray } from "@stylexjs/stylex"

type XStyle = StyleXArray<
  (null | undefined | CompiledStyles) | boolean | Readonly<[CompiledStyles, InlineStyles]>
>

export const styles = stylex.create({
  layout: {
    backgroundColor: "rgb(var(--tbr-color-page))",
    color: "rgb(var(--tbr-color-text))",
    display: "grid",
    gridTemplateColumns: "56px minmax(0, 1fr)",
    minHeight: "100vh",
    overflowX: "hidden",
  },
  rail: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderRightColor: "rgb(var(--tbr-color-line))",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    boxShadow: "1px 0 0 rgb(var(--tbr-color-shadow) / 0.02)",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    height: "100vh",
    justifyContent: "flex-start",
    paddingBlock: 14,
    paddingInline: 8,
    position: "sticky",
    top: 0,
    zIndex: "var(--tbr-z-sticky, 100)",
  },
  railLogo: {
    color: "rgb(var(--tbr-color-accent))",
    display: "block",
    height: 28,
    marginBottom: 8,
    width: 28,
  },
  railGroups: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  railGroup: {
    position: "relative",
  },
  railButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: 10,
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: 13,
    height: 38,
    justifyContent: "center",
    position: "relative",
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "background-color, border-color, color, box-shadow",
    transitionTimingFunction: "var(--tbr-ease)",
    width: 38,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  railButtonActive: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderColor: "rgb(var(--tbr-color-accent))",
    boxShadow: "inset 0 1px 3px rgb(var(--tbr-color-shadow) / 0.1)",
    color: "rgb(var(--tbr-color-accent))",
  },
  groupIcon: {
    fontSize: 13,
    fontWeight: 650,
    lineHeight: 1,
  },
  groupShortcut: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-pill)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    display: "block",
    fontFamily: "var(--tbr-font-mono)",
    fontSize: 9,
    height: 14,
    lineHeight: "12px",
    minWidth: 14,
    paddingInline: 3,
    pointerEvents: "none",
    position: "absolute",
    right: -4,
    top: -4,
  },
  groupTip: {
    backgroundColor: "rgb(var(--tbr-color-text))",
    borderRadius: 5,
    color: "rgb(var(--tbr-color-page))",
    display: "block",
    fontSize: 11,
    left: 46,
    opacity: 0,
    paddingBlock: 4,
    paddingInline: 8,
    pointerEvents: "none",
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    whiteSpace: "nowrap",
    zIndex: 60,
  },
  placeholderWrap: {
    position: "relative",
  },
  placeholder: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderColor: "rgb(var(--tbr-color-accent))",
    color: "rgb(var(--tbr-color-accent))",
  },
  inlinePop: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 8px 24px rgb(var(--tbr-color-shadow) / 0.22)",
    display: "flex",
    gap: 8,
    justifyContent: "flex-start",
    left: 46,
    padding: 10,
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    width: "max-content",
    zIndex: 80,
  },
  inlineInput: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text))",
    fontFamily: "inherit",
    fontSize: 12,
    height: 30,
    outline: "none",
    paddingInline: 8,
    width: 150,
    ":focus": {
      borderColor: "rgb(var(--tbr-color-accent))",
      boxShadow: "0 0 0 3px rgb(var(--tbr-color-accent) / 0.08)",
    },
  },
  inlineHint: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "inline-flex",
    fontSize: 10,
    fontWeight: 500,
    gap: 4,
    whiteSpace: "nowrap",
  },
  inlineKbd: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: 4,
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    fontFamily: "inherit",
    fontSize: 9,
    paddingBlock: 1,
    paddingInline: 4,
  },
  divider: {
    backgroundColor: "rgb(var(--tbr-color-line))",
    height: 1,
    marginBlock: 4,
    marginInline: 0,
    width: 24,
  },
  spacer: {
    display: "block",
    flex: 1,
  },
  layoutLabel: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minWidth: 0,
  },
  layoutName: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 12,
    fontWeight: 650,
    lineHeight: 1.2,
  },
  layoutDescription: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 10,
    lineHeight: 1.2,
    marginTop: 1,
  },
  groupMenu: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 12px 32px rgb(var(--tbr-color-shadow) / 0.22)",
    padding: 6,
    position: "fixed",
    width: 212,
    zIndex: "var(--tbr-z-dropdown, 200)",
  },
  menuItem: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-text))",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: 12,
    justifyContent: "space-between",
    minHeight: 32,
    paddingBlock: 7,
    paddingInline: 9,
    textAlign: "left",
    width: "100%",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
    },
    ":disabled": {
      backgroundColor: "transparent",
      color: "rgb(var(--tbr-color-text-subtle))",
      cursor: "default",
      opacity: 0.48,
    },
  },
  menuItemDanger: {
    color: "rgb(var(--tbr-color-danger))",
  },
  menuKbd: {
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: 4,
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    fontFamily: "inherit",
    fontSize: 10,
    paddingBlock: 1,
    paddingInline: 5,
  },
  menuSeparator: {
    backgroundColor: "rgb(var(--tbr-color-line))",
    height: 1,
    marginBlock: 5,
    marginInline: 4,
  },
  menuLabel: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 10,
    fontWeight: 650,
    paddingBlockEnd: 5,
    paddingBlockStart: 3,
    paddingInline: 8,
    textTransform: "uppercase",
  },
  menuIcons: {
    display: "grid",
    gap: 4,
    gridTemplateColumns: "repeat(7, 1fr)",
    paddingBlockEnd: 3,
    paddingInline: 4,
  },
  menuIcon: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 12,
    height: 24,
    justifyContent: "center",
    width: 24,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent-soft))",
      borderColor: "rgb(var(--tbr-color-accent))",
      color: "rgb(var(--tbr-color-accent))",
    },
  },
  menuIconActive: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderColor: "rgb(var(--tbr-color-accent))",
    color: "rgb(var(--tbr-color-accent))",
  },
  dashboardContent: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    marginInline: "auto",
    maxWidth: 1440,
    minWidth: 0,
    paddingBlockEnd: 24,
    paddingBlockStart: 24,
    paddingInline: 32,
    width: "100%",
  },
  greeting: {
    alignItems: "center",
    display: "flex",
    flexWrap: "nowrap",
    fontSize: 13,
    fontWeight: 600,
    gap: 12,
    justifyContent: "space-between",
  },
  greetingTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontWeight: 600,
  },
  muted: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontWeight: 400,
  },
  greetingActions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "nowrap",
    gap: 6,
    justifyContent: "flex-end",
    opacity: 0.74,
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "opacity",
    transitionTimingFunction: "var(--tbr-ease)",
    ":hover": {
      opacity: 1,
    },
    ":focus-within": {
      opacity: 1,
    },
  },
  toolbarButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 11,
    fontWeight: 500,
    gap: 4,
    height: 28,
    justifyContent: "center",
    paddingInline: 10,
    whiteSpace: "nowrap",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  searchStage: {
    display: "flex",
    justifyContent: "center",
    marginBlockEnd: 4,
    marginBlockStart: 2,
    position: "relative",
    width: "100%",
  },
  searchInner: {
    maxWidth: 720,
    width: "min(100%, 720px)",
  },
  grid: {
    minWidth: 0,
  },
  gridContainer: {
    alignItems: "stretch",
    display: "grid",
    gap: 12,
    gridAutoFlow: "dense",
    gridAutoRows: "var(--dashboard-grid-cell, 96px)",
    gridTemplateColumns: "repeat(10, minmax(0, 1fr))",
  },
  emptyGroup: {
    alignItems: "center",
    appearance: "none",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    fontFamily: "inherit",
    fontSize: 14,
    gap: 8,
    gridColumn: "1 / -1",
    paddingBlock: 32,
    paddingInline: 24,
    textAlign: "center",
    ":hover": {
      opacity: 0.85,
    },
  },
  emptyIcon: {
    color: "rgb(var(--tbr-color-text-subtle))",
    marginBottom: 4,
    opacity: 0.5,
  },
  emptyText: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 14,
    fontWeight: 600,
  },
  emptyHint: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 13,
  },
  emptyAction: {
    color: "rgb(var(--tbr-color-accent))",
    fontWeight: 600,
  },
  // Mobile breakpoint styles
  mobileLayout: {
    display: "block",
    overflow: "hidden",
    "@media (max-width: 768px)": {
      display: "block",
    },
  },
  mobileScrollContainer: {
    display: "flex",
    height: "100vh",
    overflowX: "auto",
    overflowY: "hidden",
    scrollBehavior: "smooth",
    scrollSnapType: "x mandatory",
    WebkitOverflowScrolling: "touch",
  },
  mobilePage: {
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    height: "100vh",
    scrollSnapAlign: "start",
    width: "100vw",
  },
  mobileContent: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: 16,
    minHeight: 0,
    overflowY: "auto",
    paddingBlockEnd: 66,
    paddingBlockStart: 16,
    paddingInline: 16,
    width: "100%",
  },
  mobileGreeting: {
    display: "flex",
    flexDirection: "column",
    fontSize: 13,
    fontWeight: 600,
    gap: 6,
  },
  mobileGreetingActions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    justifyContent: "flex-start",
    opacity: 0.74,
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "opacity",
    transitionTimingFunction: "var(--tbr-ease)",
    ":focus-within": {
      opacity: 1,
    },
  },
  mobileGridContainer: {
    alignItems: "stretch",
    display: "grid",
    gap: 12,
    gridAutoFlow: "dense",
    gridAutoRows: "var(--mobile-grid-cell, 80px)",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
  },
  mobileBar: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderTopColor: "rgb(var(--tbr-color-line))",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    bottom: 0,
    display: "flex",
    flexDirection: "row",
    gap: 6,
    height: 50,
    justifyContent: "space-around",
    left: 0,
    paddingBlock: 6,
    paddingInline: 12,
    position: "fixed",
    right: 0,
    zIndex: "var(--tbr-z-sticky, 100)",
  },
  mobileBarButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: 10,
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: 13,
    height: 38,
    justifyContent: "center",
    position: "relative",
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "background-color, border-color, color, box-shadow",
    transitionTimingFunction: "var(--tbr-ease)",
    width: 38,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      color: "rgb(var(--tbr-color-text))",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  mobileBarButtonActive: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderColor: "rgb(var(--tbr-color-accent))",
    boxShadow: "inset 0 1px 3px rgb(var(--tbr-color-shadow) / 0.1)",
    color: "rgb(var(--tbr-color-accent))",
  },
  pageIndicator: {
    alignItems: "center",
    bottom: 56,
    display: "flex",
    gap: 8,
    justifyContent: "center",
    left: 0,
    paddingBlock: 8,
    position: "fixed",
    right: 0,
    zIndex: "var(--tbr-z-sticky, 100)",
  },
  pageIndicatorDot: {
    backgroundColor: "rgb(var(--tbr-color-text-subtle))",
    borderRadius: "50%",
    height: 6,
    opacity: 0.3,
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "opacity, background-color, transform",
    transitionTimingFunction: "var(--tbr-ease)",
    width: 6,
  },
  pageIndicatorDotActive: {
    backgroundColor: "rgb(var(--tbr-color-accent))",
    opacity: 1,
    transform: "scale(1.2)",
  },
  focusShell: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    minHeight: "100vh",
    paddingBlockEnd: 0,
    paddingBlockStart: 0,
    paddingInline: 0,
  },
  focusContent: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    maxWidth: 800,
    paddingBlock: 24,
    paddingInline: 32,
    width: "100%",
  },
  focusTopbar: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "flex",
    fontSize: 11,
    gap: 16,
    justifyContent: "space-between",
  },
  focusGreeting: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    flexWrap: "nowrap",
    fontSize: 13,
    fontWeight: 600,
    gap: 10,
    minWidth: 0,
  },
  focusMuted: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 11,
    fontWeight: 400,
  },
  focusActions: {
    alignItems: "center",
    display: "inline-flex",
    gap: 8,
  },
  focusControl: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    fontFamily: "inherit",
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "background-color, border-color, color",
    transitionTimingFunction: "var(--tbr-ease)",
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  focusIconButton: {
    alignItems: "center",
    borderRadius: "var(--tbr-radius-pill)",
    display: "inline-flex",
    height: 27,
    justifyContent: "center",
    width: 27,
    ":hover": {
      borderColor: "rgb(var(--tbr-color-accent))",
      color: "rgb(var(--tbr-color-text))",
    },
  },
  focusCommand: {
    alignItems: "center",
    borderRadius: "var(--tbr-radius-pill)",
    display: "inline-flex",
    fontSize: 11,
    fontWeight: 500,
    gap: 7,
    height: 28,
    justifyContent: "center",
    minWidth: "auto",
    paddingBlock: 4,
    paddingInline: 10,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent-soft))",
      borderColor: "rgb(var(--tbr-color-accent))",
      color: "rgb(var(--tbr-color-accent))",
    },
  },
  focusKbd: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: "var(--tbr-radius-pill)",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 10,
    fontWeight: 650,
    height: 18,
    justifyContent: "center",
    minWidth: 31,
  },
  hero: {
    aspectRatio: "4 / 2",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-accent))",
    borderRadius: 8,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 8px 28px rgb(var(--tbr-color-accent) / 0.12)",
    display: "flex",
    flexDirection: "column",
    minHeight: 320,
    overflow: "hidden",
  },
  focusCardHead: {
    alignItems: "center",
    backgroundColor:
      "color-mix(in srgb, rgb(var(--tbr-color-surface-soft)) 72%, rgb(var(--tbr-color-surface)))",
    borderBottomColor: "rgb(var(--tbr-color-line))",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    gap: 10,
    height: 40,
    justifyContent: "space-between",
    minHeight: 40,
    paddingInline: 14,
  },
  satelliteHead: {
    height: 32,
    minHeight: 32,
    paddingInline: 11,
  },
  focusCardTitle: {
    color: "rgb(var(--tbr-color-text-muted))",
    fontSize: 11,
    fontWeight: 650,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  focusCardSize: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderRadius: "var(--tbr-radius-pill)",
    color: "rgb(var(--tbr-color-accent))",
    flex: "0 0 auto",
    fontSize: 8,
    fontWeight: 700,
    paddingBlock: 2,
    paddingInline: 6,
    textTransform: "uppercase",
  },
  focusPlugin: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  focusPluginHero: {
    flex: 1,
  },
  focusPluginSatellite: {
    aspectRatio: "2 / 1",
  },
  focusPager: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "flex",
    fontSize: 10,
    gap: 6,
    justifyContent: "flex-end",
    minHeight: 24,
  },
  focusPageButton: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-text-muted))",
    height: 24,
    width: 24,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent-soft))",
      borderColor: "rgb(var(--tbr-color-accent))",
      color: "rgb(var(--tbr-color-accent))",
    },
  },
  focusPageLabel: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 10,
    fontVariantNumeric: "tabular-nums",
    minWidth: 34,
    textAlign: "center",
  },
  focusEmpty: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "dashed",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 13,
    minHeight: 320,
    paddingBlock: 72,
    paddingInline: 20,
    width: "100%",
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  satellites: {
    display: "grid",
    gap: 10,
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
  },
  satellite: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: 8,
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    fontFamily: "inherit",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    position: "relative",
    transitionDuration: "var(--tbr-dur-normal)",
    transitionProperty: "background-color, border-color, box-shadow, transform",
    transitionTimingFunction: "var(--tbr-ease)",
    ":hover": {
      borderColor: "rgb(var(--tbr-color-line-strong))",
      boxShadow: "0 4px 12px rgb(var(--tbr-color-shadow) / 0.08)",
      transform: "translateY(-2px)",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 2,
    },
  },
  satelliteMeta: {
    color: "rgb(var(--tbr-color-text-muted))",
    flex: "0 0 auto",
    fontSize: 10,
    lineHeight: 1.2,
  },
})

export function className(...values: XStyle[]) {
  return stylex.attrs(...values).class
}
