import * as stylex from "@stylexjs/stylex"

import { color, font, radius, space } from "@tabora/theme/tokens.stylex"

export const styles = stylex.create({
  emptyCopy: { color: color.textMuted, fontSize: 13, margin: 0, padding: space.s5 },
  tabBar: {
    borderBottomColor: color.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    gap: space.s5,
  },
  tab: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: color.textMuted,
    cursor: "pointer",
    fontFamily: font.sans,
    fontSize: 13,
    paddingBlock: space.s3,
    paddingInline: 0,
  },
  tabActive: {
    borderBottomColor: color.accent,
    borderBottomStyle: "solid",
    borderBottomWidth: 2,
    color: color.text,
    fontWeight: font.semibold,
  },
  toolbar: {
    alignItems: "center",
    display: "flex",
    gap: space.s4,
    justifyContent: "space-between",
  },
  toolbarCopy: { color: color.textMuted, fontSize: 12 },
  resourceList: {
    borderColor: color.line,
    borderRadius: radius.card,
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  resourceRow: {
    alignItems: "center",
    backgroundColor: color.surface,
    borderBottomColor: color.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: space.s4,
    gridTemplateColumns: "minmax(0, 1fr) auto auto",
    padding: space.s4,
    ":last-child": { borderBottomWidth: 0 },
    "@media (max-width: 760px)": {
      alignItems: "flex-start",
      gridTemplateColumns: "minmax(0, 1fr) auto",
    },
  },
  resourceMain: { display: "flex", flexDirection: "column", gap: space.s1, minWidth: 0 },
  resourceName: { color: color.text, fontSize: 14, fontWeight: font.semibold },
  resourceMeta: {
    color: color.textMuted,
    fontFamily: font.mono,
    fontSize: 12,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowActions: {
    display: "flex",
    gap: space.s2,
    justifyContent: "flex-end",
    "@media (max-width: 760px)": { gridColumn: "1 / -1", justifyContent: "flex-start" },
  },
  editorBody: { display: "flex", flexDirection: "column", gap: space.s5 },
  setupStep: {
    borderBottomColor: color.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexDirection: "column",
    gap: space.s3,
    paddingBottom: space.s5,
  },
  stepHeader: { alignItems: "center", display: "flex", gap: space.s3 },
  stepNumber: {
    alignItems: "center",
    backgroundColor: color.accentSoft,
    borderRadius: radius.pill,
    color: color.accent,
    display: "flex",
    fontSize: 12,
    fontWeight: font.semibold,
    height: 20,
    justifyContent: "center",
    width: 20,
  },
  stepTitle: { fontSize: 14, fontWeight: font.semibold },
  helper: { color: color.textMuted, fontSize: 12, lineHeight: 1.45, margin: 0 },
  modelIdControl: {
    alignItems: "center",
    display: "grid",
    gap: space.s3,
    gridTemplateColumns: "minmax(0, 1fr) auto",
  },
  modelIdSelect: { minWidth: 0, width: "100%" },
  idPreview: {
    alignItems: "center",
    backgroundColor: color.surfaceSoft,
    borderColor: color.line,
    borderRadius: radius.control,
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flexWrap: "wrap",
    gap: space.s2,
    paddingBlock: space.s3,
    paddingInline: space.s3,
  },
  idLabel: { color: color.textMuted, fontSize: 12 },
  idValue: { color: color.text, fontFamily: font.mono, fontSize: 12 },
  testRow: { alignItems: "center", display: "flex", flexWrap: "wrap", gap: space.s3 },
  testHint: { color: color.textMuted, fontSize: 12 },
  footer: {
    alignItems: "center",
    display: "flex",
    gap: space.s3,
    justifyContent: "flex-end",
    width: "100%",
  },
})
