import * as stylex from "@stylexjs/stylex"
import { color, font, motion, radius, shadow, space, zIndex } from "@tabora/theme/tokens.stylex"

const fadeIn = stylex.keyframes({
  from: { opacity: 0 },
  to: { opacity: 1 },
})

const scaleIn = stylex.keyframes({
  from: { transform: "scale(0.97) translateY(10px)" },
  to: { transform: "scale(1) translateY(0)" },
})

export const styles = stylex.create({
  overlay: {
    alignItems: "center",
    animationDuration: motion.normal,
    animationName: fadeIn,
    animationTimingFunction: motion.ease,
    backdropFilter: "blur(2px)",
    backgroundColor: "rgb(var(--tbr-color-scrim) / 0.18)",
    display: "flex",
    inset: 0,
    justifyContent: "center",
    position: "fixed",
    zIndex: zIndex.modal,
    "@media (prefers-reduced-motion: reduce)": {
      animationDuration: "1ms",
    },
  },
  mobilePage: {
    backgroundColor: color.page,
    color: color.text,
    display: "flex",
    flexDirection: "column",
    minHeight: "100dvh",
    overflow: "hidden",
    width: "100%",
  },
  content: {
    animationDuration: motion.normal,
    animationName: scaleIn,
    animationTimingFunction: motion.ease,
    backgroundColor: color.surface,
    borderColor: color.lineStrong,
    borderRadius: radius.panel,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: shadow.floating,
    display: "flex",
    flexDirection: "column",
    height: "min(440px, calc(100vh - 64px))",
    overflow: "hidden",
    width: "min(760px, calc(100vw - 48px))",
    "@media (min-width: 1024px)": {
      height: "min(600px, calc(100vh - 64px))",
      width: "min(920px, calc(100vw - 48px))",
    },
    "@media (max-width: 768px)": {
      width: "calc(100vw - 32px)",
    },
    "@media (prefers-reduced-motion: reduce)": {
      animationDuration: "1ms",
    },
  },
  mobilePageWindow: {
    backgroundColor: color.surface,
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minHeight: 0,
    width: "100%",
  },
  header: {
    alignItems: "center",
    backgroundColor: color.surfaceSoft,
    borderBottomColor: color.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flex: "0 0 auto",
    gap: 10,
    justifyContent: "space-between",
    paddingBlock: 10,
    paddingInline: 12,
  },
  title: {
    alignItems: "center",
    display: "flex",
    gap: 9,
    minWidth: 0,
  },
  titleIcon: {
    alignItems: "center",
    backgroundColor: color.surface,
    borderColor: color.line,
    borderRadius: radius.control,
    borderStyle: "solid",
    borderWidth: 1,
    color: color.accent,
    display: "flex",
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  titleCopy: {
    display: "grid",
    gap: 2,
    minWidth: 0,
  },
  titleStrong: {
    fontSize: 13,
    lineHeight: 1.2,
  },
  titleMeta: {
    color: color.textMuted,
    fontSize: 11,
    lineHeight: 1.25,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  close: {
    alignItems: "center",
    backgroundColor: color.surface,
    borderColor: color.line,
    borderRadius: radius.control,
    borderStyle: "solid",
    borderWidth: 1,
    color: color.textMuted,
    cursor: "pointer",
    display: "flex",
    flexShrink: 0,
    height: 28,
    justifyContent: "center",
    transitionDuration: motion.fast,
    transitionProperty: "background-color, border-color, color",
    transitionTimingFunction: motion.ease,
    width: 28,
    ":hover": {
      backgroundColor: color.surfaceHover,
      borderColor: color.lineStrong,
      color: color.text,
    },
    ":focus-visible": {
      outlineColor: color.focus,
      outlineOffset: 2,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  body: {
    backgroundColor: color.surface,
    display: "grid",
    flex: 1,
    gap: 10,
    gridTemplateColumns: "154px minmax(0, 1fr)",
    minHeight: 0,
    padding: 10,
    "@media (max-width: 480px)": {
      gridTemplateColumns: "1fr",
      gridTemplateRows: "auto minmax(0, 1fr)",
    },
  },
  bodyMobile: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
    padding: 0,
  },
  nav: {
    backgroundColor: color.surfaceSoft,
    borderColor: color.line,
    borderRadius: radius.panel,
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flexDirection: "column",
    gap: 3,
    margin: 0,
    minHeight: 0,
    overflow: "auto",
    padding: 8,
    "@media (max-width: 480px)": {
      borderRadius: 0,
      borderWidth: 0,
      borderBottomStyle: "solid",
      borderBottomWidth: 1,
      margin: 0,
      maxHeight: 170,
    },
  },
  kicker: {
    color: color.textSubtle,
    fontSize: 10,
    fontWeight: font.bold,
    letterSpacing: "0.05em",
    paddingBottom: 4,
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 6,
    textTransform: "uppercase",
  },
  navButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: 7,
    borderStyle: "solid",
    borderWidth: 1,
    color: color.textMuted,
    cursor: "pointer",
    display: "flex",
    fontSize: 11,
    fontWeight: 600,
    gap: 8,
    height: 28,
    justifyContent: "space-between",
    // Button 基础样式是 lineHeight: 1，行盒被压到 11px；中日韩字形在零 half-leading 下
    // 光学中心会偏下，flex 居中的是行盒不是字形。设计稿的 .nav-button 未声明 line-height，
    // 继承 normal，这里跟随。
    lineHeight: "normal",
    paddingBlock: 0,
    paddingInline: 8,
    textAlign: "left",
    transitionDuration: motion.fast,
    transitionProperty: "background-color, border-color, color",
    transitionTimingFunction: motion.ease,
    ":hover": {
      backgroundColor: color.surfaceHover,
      color: color.text,
    },
    ":focus-visible": {
      outlineColor: color.focus,
      outlineOffset: 2,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  navButtonActive: {
    backgroundColor: color.accentSoft,
    borderColor: "color-mix(in srgb, rgb(var(--tbr-color-accent)) 28%, rgb(var(--tbr-color-line)))",
    color: color.accent,
    ":hover": {
      backgroundColor: color.accentSoft,
      borderColor:
        "color-mix(in srgb, rgb(var(--tbr-color-accent)) 28%, rgb(var(--tbr-color-line)))",
      color: color.accent,
    },
    ":active": {
      backgroundColor: color.accentSoft,
    },
  },
  navCount: {
    color: color.textSubtle,
    fontSize: 10,
    fontWeight: font.semibold,
  },
  main: {
    backgroundColor: color.surface,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    minHeight: 0,
    overflow: "auto",
    paddingBottom: 12,
    paddingLeft: 16,
    paddingRight: 14,
    paddingTop: 12,
  },
  mainAccount: {
    justifyContent: "center",
  },
  mainMobile: {
    borderRadius: 0,
    borderStyle: "none",
    borderWidth: 0,
    gap: 16,
    overflow: "auto",
    padding: 16,
    paddingBottom: 20,
  },
  panelHeader: {
    alignItems: "center",
    display: "flex",
    flex: "0 0 auto",
    gap: 10,
    justifyContent: "space-between",
    minHeight: 38,
    paddingBottom: 2,
  },
  panelHeaderMobile: {
    alignItems: "flex-start",
    minHeight: 44,
  },
  panelHeaderTitle: {
    display: "block",
    fontSize: 13,
    lineHeight: 1.2,
    marginBottom: 3,
  },
  panelHeaderDescription: {
    color: color.textSubtle,
    display: "block",
    fontSize: 11,
    lineHeight: 1.35,
    maxWidth: 310,
  },
  panelView: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    minHeight: 0,
  },
  stack: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    minHeight: 0,
  },
  empty: {
    color: color.textMuted,
    fontSize: 13,
    paddingBlock: 24,
    paddingInline: 20,
    textAlign: "center",
  },
  missing: {
    color: color.danger,
    fontSize: 13,
    padding: 12,
  },
  footer: {
    alignItems: "center",
    backgroundColor: color.surface,
    borderTopColor: color.line,
    borderTopStyle: "solid",
    borderTopWidth: 1,
    color: color.textMuted,
    display: "flex",
    flex: "0 0 auto",
    fontSize: 10,
    gap: 10,
    justifyContent: "space-between",
    paddingBlock: 10,
    paddingInline: 12,
  },
  status: {
    alignItems: "center",
    color: color.textSubtle,
    display: "inline-flex",
    gap: 7,
    minWidth: 0,
  },
  statusDot: {
    backgroundColor: color.lineStrong,
    borderRadius: radius.pill,
    height: 6,
    width: 6,
  },
  footerActions: {
    alignItems: "center",
    display: "flex",
    gap: space.s2,
  },
})
