import * as stylex from "@stylexjs/stylex"

export const styles = stylex.create({
  card: {
    borderRadius: "inherit",
    display: "grid",
    height: "100%",
    minHeight: 0,
    overflow: "hidden",
  },
  // 版式承重的可点区域用原生 button + 本文件样式：@tabora/ui 的 Button
  // 以 paddingInline/paddingBlock 长写锁定尺寸，卡片这边的 padding 简写覆盖不到。
  hit: {
    appearance: "none",
    backgroundColor: "transparent",
    // 设计稿全局是 border-box；这里不跟上的话每个带边框的盒子都会宽出 2px
    boxSizing: "border-box",
    borderStyle: "none",
    borderWidth: 0,
    color: "inherit",
    cursor: "pointer",
    fontFamily: "inherit",
    margin: 0,
    minHeight: 0,
    minWidth: 0,
    padding: 0,
    textAlign: "left",
  },
  emptyAction: { color: "rgb(var(--tbr-color-text-subtle))", fontSize: 11, height: "100%" },
  // S：迷你星座，主入口居中，其余节点按设计稿的百分比散落，三根连线在底层。
  // cqw 按查询容器内容盒算，故此处不留 padding，标题与节点各自带偏移。
  small: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderRadius: "inherit",
    containerType: "inline-size",
    overflow: "hidden",
    position: "relative",
  },
  smallTitle: {
    fontSize: "clamp(6px, 7cqw, 10px)",
    fontWeight: 750,
    left: "9%",
    position: "absolute",
    top: "8%",
  },
  smallNode: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 6px 18px rgb(var(--tbr-color-shadow) / 0.06)",
    display: "flex",
    fontSize: "clamp(5px, 6cqw, 8px)",
    fontWeight: 700,
    justifyContent: "center",
    position: "absolute",
    textAlign: "center",
  },
  smallPrimary: {
    backgroundColor: "rgb(var(--tbr-color-text))",
    borderColor: "rgb(var(--tbr-color-text))",
    color: "rgb(var(--tbr-color-inverse))",
    height: "34%",
    left: "34%",
    top: "35%",
    width: "34%",
  },
  smallOne: { height: "22%", left: "10%", top: "39%", width: "22%" },
  smallTwo: { height: "20%", right: "9%", top: "27%", width: "20%" },
  smallThree: { bottom: "8%", height: "24%", left: "20%", width: "24%" },
  smallFour: { bottom: "12%", height: "19%", right: "12%", width: "19%" },
  smallAdd: { color: "rgb(var(--tbr-color-accent))" },
  smallLine: {
    backgroundColor: "rgb(var(--tbr-color-line))",
    height: 1,
    position: "absolute",
    transformOrigin: "left center",
  },
  smallLineA: { left: "27%", top: "50%", transform: "rotate(-8deg)", width: "30%" },
  smallLineB: { left: "58%", top: "45%", transform: "rotate(-22deg)", width: "29%" },
  smallLineC: { left: "41%", top: "66%", transform: "rotate(47deg)", width: "32%" },
  // M：左侧主入口 + 右侧 2×2 节点轨，卡片体自带 9px 内缩与左上角强调色光斑
  medium: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    backgroundImage:
      "radial-gradient(circle at 22% 18%, color-mix(in srgb, rgb(var(--tbr-color-accent)) 14%, transparent), transparent 42%)",
    display: "grid",
    gap: 7,
    gridTemplateColumns: "minmax(0, 1fr) 62px",
    minHeight: 0,
    minWidth: 0,
    padding: 9,
  },
  primaryLink: {
    backgroundColor:
      "color-mix(in srgb, rgb(var(--tbr-color-accent)) 7%, rgb(var(--tbr-color-surface)))",
    borderColor: "color-mix(in srgb, rgb(var(--tbr-color-accent)) 24%, rgb(var(--tbr-color-line)))",
    borderRadius: 7,
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text))",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    paddingBlock: 8,
    paddingInline: 9,
    position: "relative",
  },
  // 设计稿右上角用 ::after 放固定的 ↗，不随主入口标题一起换行
  primaryArrow: {
    color: "rgb(var(--tbr-color-accent))",
    fontSize: 11,
    lineHeight: 1,
    position: "absolute",
    right: 8,
    top: 7,
  },
  primaryMark: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-text))",
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-inverse))",
    display: "flex",
    fontSize: 9,
    fontWeight: 750,
    height: 22,
    justifyContent: "center",
    width: 22,
  },
  // 标题与 OPEN 同行基线对齐，标题过长时省略号
  primaryCopy: {
    alignItems: "baseline",
    display: "flex",
    gap: 5,
    justifyContent: "space-between",
    minWidth: 0,
  },
  primaryTitle: {
    fontSize: 11,
    fontWeight: 700,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  primaryHint: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 8,
    letterSpacing: "0.06em",
  },
  mediumRail: {
    display: "grid",
    gap: 5,
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gridTemplateRows: "repeat(2, minmax(0, 1fr))",
  },
  railLink: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    fontSize: 8,
    fontWeight: 700,
    justifyContent: "center",
    textAlign: "center",
    ":hover": {
      borderColor: "rgb(var(--tbr-color-line-strong))",
      color: "rgb(var(--tbr-color-text))",
    },
  },
  addLink: { borderStyle: "dashed", color: "rgb(var(--tbr-color-accent))", fontSize: 14 },
  // L：星座图。背景由强调色圆环 + 一纵一横两根细线叠在表面色上组成
  large: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    backgroundImage: [
      "radial-gradient(circle at 50% 54%, color-mix(in srgb, rgb(var(--tbr-color-accent)) 12%, transparent) 0 19%, transparent 20%)",
      "linear-gradient(rgb(var(--tbr-color-line)), rgb(var(--tbr-color-line)))",
      "linear-gradient(90deg, rgb(var(--tbr-color-line)), rgb(var(--tbr-color-line)))",
    ].join(","),
    backgroundPosition: "0 0, 50% 54%, 50% 54%",
    backgroundRepeat: "no-repeat",
    backgroundSize: "auto, 1px 58%, 58% 1px",
    position: "relative",
  },
  kicker: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 8,
    fontWeight: 650,
    letterSpacing: "0.11em",
    textTransform: "uppercase",
  },
  largeKicker: {
    left: 13,
    position: "absolute",
    top: 12,
    zIndex: 2,
  },
  // 设计稿这里是 grid + place-items:center，字样与标题各占一行隐式轨道，
  // 不能改成 flex column 居中：那样两行会挤在中线附近，和设计稿差 10px 以上。
  constellationCore: {
    backgroundColor:
      "color-mix(in srgb, rgb(var(--tbr-color-accent)) 8%, rgb(var(--tbr-color-surface)))",
    borderColor: "color-mix(in srgb, rgb(var(--tbr-color-accent)) 34%, rgb(var(--tbr-color-line)))",
    borderRadius: 18,
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text))",
    display: "grid",
    height: 58,
    left: "50%",
    placeItems: "center",
    position: "absolute",
    textAlign: "center",
    top: "54%",
    transform: "translate(-50%, -50%)",
    transitionDuration: "140ms",
    transitionProperty: "transform, border-color",
    width: 58,
    ":hover": {
      borderColor: "rgb(var(--tbr-color-accent))",
      transform: "translate(-50%, -50%) scale(1.04)",
      zIndex: 3,
    },
  },
  coreMark: { fontSize: 15, fontWeight: 700 },
  coreTitle: { color: "rgb(var(--tbr-color-text-muted))", fontSize: 8 },
  constellationNode: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    fontSize: 9,
    fontWeight: 700,
    height: 34,
    justifyContent: "center",
    position: "absolute",
    textAlign: "center",
    transform: "translate(-50%, -50%)",
    transitionDuration: "140ms",
    transitionProperty: "transform, border-color",
    width: 34,
    ":hover": {
      borderColor: "rgb(var(--tbr-color-accent))",
      transform: "translate(-50%, -50%) scale(1.06)",
      zIndex: 3,
    },
  },
  constellationOne: { left: "24%", top: "31%" },
  constellationTwo: { left: "76%", top: "30%" },
  constellationThree: { left: "25%", top: "77%" },
  constellationFour: { left: "75%", top: "78%" },
  constellationFive: { left: "88%", top: "54%" },
  constellationAdd: {
    borderStyle: "dashed",
    color: "rgb(var(--tbr-color-accent))",
    fontSize: 15,
  },
  // XL：左侧主工作区舞台 + 右侧 2×2 入口板，两栏之间是 1px 分隔线
  extraLarge: {
    backgroundColor: "rgb(var(--tbr-color-surface))",
    display: "grid",
    gridTemplateColumns: "minmax(128px, 0.9fr) minmax(0, 1.5fr)",
    minHeight: 0,
    minWidth: 0,
  },
  stage: {
    backgroundImage:
      "linear-gradient(145deg, color-mix(in srgb, rgb(var(--tbr-color-accent)) 10%, rgb(var(--tbr-color-surface))), rgb(var(--tbr-color-surface)) 62%)",
    borderRightColor: "rgb(var(--tbr-color-line))",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    color: "rgb(var(--tbr-color-text))",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    minWidth: 0,
    padding: 14,
    position: "relative",
  },
  // 设计稿右下角的装饰圆环，纯装饰不参与排版
  stageRing: {
    borderColor: "color-mix(in srgb, rgb(var(--tbr-color-accent)) 24%, rgb(var(--tbr-color-line)))",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: 1,
    bottom: 13,
    boxShadow: "0 0 0 8px color-mix(in srgb, rgb(var(--tbr-color-accent)) 5%, transparent)",
    height: 32,
    position: "absolute",
    right: 13,
    width: 32,
  },
  stagePrimary: {
    alignItems: "center",
    display: "flex",
    gap: 9,
    minWidth: 0,
    position: "relative",
    zIndex: 1,
  },
  stageMark: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-text))",
    borderRadius: 10,
    color: "rgb(var(--tbr-color-inverse))",
    display: "flex",
    flexShrink: 0,
    fontSize: 11,
    fontWeight: 750,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  stageCopy: { display: "flex", flexDirection: "column", minWidth: 0 },
  stageTitle: {
    fontSize: 13,
    fontWeight: 700,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  stageHint: { color: "rgb(var(--tbr-color-text-muted))", fontSize: 9 },
  board: {
    display: "grid",
    gap: 7,
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gridTemplateRows: "auto repeat(2, minmax(0, 1fr))",
    minWidth: 0,
    padding: 12,
  },
  boardHead: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    fontSize: 9,
    gridColumn: "1 / -1",
    justifyContent: "space-between",
  },
  boardCount: { color: "rgb(var(--tbr-color-text-subtle))", fontSize: 8 },
  tile: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: 7,
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    display: "grid",
    fontSize: 10,
    gap: 7,
    gridTemplateColumns: "25px minmax(0, 1fr) auto",
    minWidth: 0,
    paddingBlock: 6,
    paddingInline: 8,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
  },
  tileMark: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: 7,
    borderStyle: "solid",
    borderWidth: 1,
    boxSizing: "border-box",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    fontSize: 8,
    fontWeight: 750,
    height: 25,
    justifyContent: "center",
    width: 25,
  },
  tileCopy: { display: "flex", flexDirection: "column", minWidth: 0 },
  tileTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 10,
    fontWeight: 700,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tileHint: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 8,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tileArrow: { color: "rgb(var(--tbr-color-accent))", fontSize: 10 },
  addTile: { borderStyle: "dashed", color: "rgb(var(--tbr-color-accent))" },
  search: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "flex",
    gap: 7,
    height: 30,
    paddingInline: 9,
    ":focus-within": {
      borderColor: "rgb(var(--tbr-color-accent))",
    },
  },
  searchInput: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "rgb(var(--tbr-color-text))",
    flex: 1,
    fontFamily: "inherit",
    fontSize: 11,
    lineHeight: 1,
    minWidth: 0,
    outline: "none",
    padding: 0,
    "::placeholder": {
      color: "rgb(var(--tbr-color-text-subtle))",
    },
  },
  grid: {
    display: "grid",
    gap: 6,
    gridTemplateColumns: "repeat(auto-fill, minmax(72px, 1fr))",
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  gridSmall: {
    gridTemplateColumns: "repeat(auto-fill, minmax(56px, 1fr))",
  },
  item: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    minHeight: 44,
    position: "relative",
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "background-color, border-color",
    transitionTimingFunction: "var(--tbr-ease)",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
  },
  itemSmall: {
    minHeight: 36,
  },
  itemAdd: {
    borderStyle: "dashed",
    color: "rgb(var(--tbr-color-text-subtle))",
  },
  link: {
    alignContent: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "inherit",
    cursor: "pointer",
    display: "grid",
    fontFamily: "inherit",
    gap: 4,
    height: "100%",
    justifyItems: "center",
    paddingBlock: 6,
    paddingInline: 4,
    width: "100%",
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 1,
    },
  },
  mark: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderRadius: "var(--tbr-radius-2)",
    color: "rgb(var(--tbr-color-accent))",
    display: "grid",
    fontSize: 9,
    fontWeight: 700,
    height: 20,
    lineHeight: 1,
    placeItems: "center",
    width: 20,
  },
  addMark: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 16,
    lineHeight: 1,
  },
  label: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 10,
    fontWeight: 600,
    lineHeight: 1.1,
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  labelHidden: {
    display: "none",
  },
  empty: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 12,
    gridColumn: "1 / -1",
    padding: 12,
    textAlign: "center",
  },
  expand: {
    alignItems: "start",
    display: "grid",
    gap: 14,
    gridTemplateColumns: {
      default: "minmax(0, 1fr) 220px",
      "@media (max-width: 640px)": "1fr",
    },
    height: "100%",
    minHeight: 0,
    paddingBlock: 14,
    paddingInline: 16,
  },
  main: {
    alignContent: "start",
    display: "grid",
    gap: 12,
    minWidth: 0,
  },
  side: {
    alignContent: "start",
    display: {
      default: "grid",
      "@media (max-width: 640px)": "none",
    },
    gap: 10,
    minWidth: 0,
  },
  footer: {
    alignItems: "center",
    display: "flex",
    gap: 12,
    justifyContent: "space-between",
    width: "100%",
  },
  footerInfo: {
    flex: 1,
    minWidth: 0,
  },
  footerHint: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 11,
    lineHeight: 1.3,
  },
  footerActions: {
    display: "flex",
    flex: "0 0 auto",
    gap: 8,
  },
  panel: {
    alignContent: "start",
    display: "grid",
    gap: 10,
  },
  sectionHead: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    fontSize: 11,
    gap: 10,
    justifyContent: "space-between",
    lineHeight: 1.2,
  },
  sectionTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 12,
    fontWeight: 650,
  },
  list: {
    display: "grid",
    gap: 6,
  },
  rowWrap: {
    position: "relative",
  },
  row: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "inherit",
    cursor: "pointer",
    display: "grid",
    fontFamily: "inherit",
    gap: 8,
    gridTemplateColumns: "28px minmax(0, 1fr)",
    minHeight: 42,
    paddingBlock: 6,
    paddingInline: 8,
    paddingRight: 72,
    textAlign: "left",
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "background-color, border-color",
    transitionTimingFunction: "var(--tbr-ease)",
    width: "100%",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 1,
    },
  },
  rowAdd: {
    borderStyle: "dashed",
  },
  rowMark: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-accent))",
    display: "grid",
    fontSize: 10,
    fontWeight: 700,
    height: 24,
    placeItems: "center",
    width: 24,
  },
  copy: {
    display: "grid",
    gap: 2,
    minWidth: 0,
  },
  primary: {
    fontSize: 12,
    fontWeight: 650,
    lineHeight: 1.2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  secondary: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 10,
    lineHeight: 1.2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowAction: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    height: 24,
    justifyContent: "center",
    width: 24,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent) / 0.08)",
      borderColor: "rgb(var(--tbr-color-accent) / 0.3)",
      color: "rgb(var(--tbr-color-accent))",
    },
  },
  rowActions: {
    alignItems: "center",
    display: "flex",
    gap: 4,
    position: "absolute",
    right: 8,
    top: "50%",
    transform: "translateY(-50%)",
    opacity: 0,
    pointerEvents: "none",
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "opacity",
    transitionTimingFunction: "var(--tbr-ease)",
    zIndex: 1,
  },
  rowActionsVisible: {
    opacity: 1,
    pointerEvents: "auto",
  },
  deleteAction: {
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-danger) / 0.08)",
      borderColor: "rgb(var(--tbr-color-danger) / 0.3)",
      color: "rgb(var(--tbr-color-danger))",
    },
  },
  groupList: {
    display: "grid",
    gap: 8,
  },
  groupRow: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 8,
    gridTemplateColumns: "22px minmax(0, 1fr) auto",
    minHeight: 40,
    paddingBlock: 6,
    paddingInline: 8,
  },
  grip: {
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "grid",
    placeItems: "center",
  },
  inlineCreate: {
    display: "grid",
    gap: 6,
    gridTemplateColumns: "minmax(0, 1fr) auto",
  },
  form: {
    display: "grid",
    gap: 10,
  },
  fieldRow: {
    display: "grid",
    gap: 10,
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 520px)": "1fr",
    },
  },
  colors: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  swatch: {
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    cursor: "pointer",
    height: 24,
    width: 24,
  },
  swatchActive: {
    borderColor: "rgb(var(--tbr-color-accent))",
    boxShadow: "0 0 0 3px rgb(var(--tbr-color-accent) / 0.18)",
  },
  infoCard: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 8,
    padding: 9,
  },
  infoLine: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    fontSize: 11,
    gap: 10,
    justifyContent: "space-between",
    lineHeight: 1.2,
  },
  infoValue: {
    color: "rgb(var(--tbr-color-text))",
    fontWeight: 650,
  },
  chips: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  chip: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-pill)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    display: "inline-flex",
    fontSize: 10,
    fontWeight: 600,
    height: 24,
    paddingInline: 8,
  },
  chipHidden: {
    opacity: 0.5,
  },
})
