import * as stylex from "@stylexjs/stylex"
import type { CompiledStyles, InlineStyles, StyleXArray } from "@stylexjs/stylex"
import type { JSX } from "solid-js"

type XStyle = StyleXArray<
  (null | undefined | CompiledStyles) | boolean | Readonly<[CompiledStyles, InlineStyles]>
>

export const styles = stylex.create({
  card: {
    display: "grid",
    gap: 8,
    height: "100%",
    minHeight: 0,
  },
  search: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "flex",
    gap: 7,
    height: 30,
    paddingInline: 9,
    ":focus-within": {
      borderColor: "rgb(var(--tbr-color-accent))",
    },
  },
  searchInput: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "rgb(var(--tbr-color-text))",
    flex: 1,
    fontFamily: "inherit",
    fontSize: 11,
    lineHeight: 1,
    minWidth: 0,
    outline: "none",
    padding: 0,
    "::placeholder": {
      color: "rgb(var(--tbr-color-text-subtle))",
    },
  },
  grid: {
    display: "grid",
    gap: 6,
    gridTemplateColumns: "repeat(auto-fill, minmax(72px, 1fr))",
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  gridSmall: {
    gridTemplateColumns: "repeat(auto-fill, minmax(56px, 1fr))",
  },
  item: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    minHeight: 44,
    position: "relative",
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "background-color, border-color",
    transitionTimingFunction: "var(--tbr-ease)",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
  },
  itemSmall: {
    minHeight: 36,
  },
  itemAdd: {
    borderStyle: "dashed",
    color: "rgb(var(--tbr-color-text-subtle))",
  },
  link: {
    alignContent: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "inherit",
    cursor: "pointer",
    display: "grid",
    fontFamily: "inherit",
    gap: 4,
    height: "100%",
    justifyItems: "center",
    paddingBlock: 6,
    paddingInline: 4,
    width: "100%",
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 1,
    },
  },
  mark: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderRadius: "var(--tbr-radius-2)",
    color: "rgb(var(--tbr-color-accent))",
    display: "grid",
    fontSize: 9,
    fontWeight: 700,
    height: 20,
    lineHeight: 1,
    placeItems: "center",
    width: 20,
  },
  addMark: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 16,
    lineHeight: 1,
  },
  label: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 10,
    fontWeight: 600,
    lineHeight: 1.1,
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  labelHidden: {
    display: "none",
  },
  empty: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 12,
    gridColumn: "1 / -1",
    padding: 12,
    textAlign: "center",
  },
  expand: {
    alignItems: "start",
    display: "grid",
    gap: 14,
    gridTemplateColumns: {
      default: "minmax(0, 1fr) 220px",
      "@media (max-width: 640px)": "1fr",
    },
    height: "100%",
    minHeight: 0,
    paddingBlock: 14,
    paddingInline: 16,
  },
  main: {
    alignContent: "start",
    display: "grid",
    gap: 12,
    minWidth: 0,
  },
  side: {
    alignContent: "start",
    display: {
      default: "grid",
      "@media (max-width: 640px)": "none",
    },
    gap: 10,
    minWidth: 0,
  },
  footer: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    display: "flex",
    gap: 12,
    justifyContent: "space-between",
    paddingBlock: 10,
    paddingInline: 16,
    width: "100%",
  },
  footerInfo: {
    flex: 1,
    minWidth: 0,
  },
  footerHint: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 11,
    lineHeight: 1.3,
  },
  footerActions: {
    display: "flex",
    flex: "0 0 auto",
    gap: 8,
  },
  panel: {
    alignContent: "start",
    display: "grid",
    gap: 10,
  },
  sectionHead: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    fontSize: 11,
    gap: 10,
    justifyContent: "space-between",
    lineHeight: 1.2,
  },
  sectionTitle: {
    color: "rgb(var(--tbr-color-text))",
    fontSize: 12,
    fontWeight: 650,
  },
  list: {
    display: "grid",
    gap: 6,
  },
  rowWrap: {
    position: "relative",
  },
  row: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "inherit",
    cursor: "pointer",
    display: "grid",
    fontFamily: "inherit",
    gap: 8,
    gridTemplateColumns: "28px minmax(0, 1fr) auto",
    minHeight: 42,
    paddingBlock: 6,
    paddingInline: 8,
    textAlign: "left",
    transitionDuration: "var(--tbr-dur-fast)",
    transitionProperty: "background-color, border-color",
    transitionTimingFunction: "var(--tbr-ease)",
    width: "100%",
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-surface-hover))",
      borderColor: "rgb(var(--tbr-color-line-strong))",
    },
    ":focus-visible": {
      outline: "2px solid rgb(var(--tbr-color-focus))",
      outlineOffset: 1,
    },
  },
  rowAdd: {
    borderStyle: "dashed",
  },
  rowMark: {
    backgroundColor: "rgb(var(--tbr-color-accent-soft))",
    borderRadius: "var(--tbr-radius-control)",
    color: "rgb(var(--tbr-color-accent))",
    display: "grid",
    fontSize: 10,
    fontWeight: 700,
    height: 24,
    placeItems: "center",
    width: 24,
  },
  copy: {
    display: "grid",
    gap: 2,
    minWidth: 0,
  },
  primary: {
    fontSize: 12,
    fontWeight: 650,
    lineHeight: 1.2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  secondary: {
    color: "rgb(var(--tbr-color-text-subtle))",
    fontSize: 10,
    lineHeight: 1.2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowAction: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    cursor: "pointer",
    display: "inline-flex",
    height: 24,
    justifyContent: "center",
    width: 24,
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-accent) / 0.08)",
      borderColor: "rgb(var(--tbr-color-accent) / 0.3)",
      color: "rgb(var(--tbr-color-accent))",
    },
  },
  rowActions: {
    display: "flex",
    gap: 4,
    marginLeft: 6,
  },
  deleteAction: {
    ":hover": {
      backgroundColor: "rgb(var(--tbr-color-danger) / 0.08)",
      borderColor: "rgb(var(--tbr-color-danger) / 0.3)",
      color: "rgb(var(--tbr-color-danger))",
    },
  },
  groupList: {
    display: "grid",
    gap: 8,
  },
  groupRow: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 8,
    gridTemplateColumns: "22px minmax(0, 1fr) auto",
    minHeight: 40,
    paddingBlock: 6,
    paddingInline: 8,
  },
  grip: {
    color: "rgb(var(--tbr-color-text-subtle))",
    display: "grid",
    placeItems: "center",
  },
  inlineCreate: {
    display: "grid",
    gap: 6,
    gridTemplateColumns: "minmax(0, 1fr) auto",
  },
  form: {
    display: "grid",
    gap: 10,
  },
  fieldRow: {
    display: "grid",
    gap: 10,
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 520px)": "1fr",
    },
  },
  colors: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  swatch: {
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-control)",
    borderStyle: "solid",
    borderWidth: 1,
    cursor: "pointer",
    height: 24,
    width: 24,
  },
  swatchActive: {
    borderColor: "rgb(var(--tbr-color-accent))",
    boxShadow: "0 0 0 3px rgb(var(--tbr-color-accent) / 0.18)",
  },
  infoCard: {
    backgroundColor: "rgb(var(--tbr-color-surface-soft))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-panel)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 8,
    padding: 9,
  },
  infoLine: {
    alignItems: "center",
    color: "rgb(var(--tbr-color-text-muted))",
    display: "flex",
    fontSize: 11,
    gap: 10,
    justifyContent: "space-between",
    lineHeight: 1.2,
  },
  infoValue: {
    color: "rgb(var(--tbr-color-text))",
    fontWeight: 650,
  },
  chips: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  chip: {
    alignItems: "center",
    backgroundColor: "rgb(var(--tbr-color-surface))",
    borderColor: "rgb(var(--tbr-color-line))",
    borderRadius: "var(--tbr-radius-pill)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "rgb(var(--tbr-color-text-muted))",
    display: "inline-flex",
    fontSize: 10,
    fontWeight: 600,
    height: 24,
    paddingInline: 8,
  },
  chipHidden: {
    opacity: 0.5,
  },
})

export function sx(...values: XStyle[]): {
  class: string | undefined
  style: JSX.CSSProperties | undefined
} {
  const compiled = stylex.props(...values)
  return { class: compiled.className, style: compiled.style as JSX.CSSProperties | undefined }
}
